import test from "node:test";
import assert from "node:assert/strict";
import { organizationIndustries, organizationProfiles, organizationRegions, organizationRelationships, organizationSources, organizationTechnologies } from "../data/demo/organizations.ts";
import { compareOrganizations, filterOrganizations, oneHopRelationships, organizationMetrics, parseOrganizationQuery, sortOrganizations, validateOrganizationData } from "../lib/organization-intelligence.ts";

test("ships 65 bilingual demo organizations across 13 regions and nine industries",()=>{assert.equal(organizationProfiles.length,65);assert.equal(organizationRegions.length,13);assert.equal(organizationIndustries.length,9);assert.ok(organizationProfiles.every(p=>p.localizedName.en&&p.localizedName.zh&&p.isDemo));});
test("covers all required initial organization categories",()=>{const types=new Set(organizationProfiles.map(p=>p.organizationType));for(const type of ["STARTUP","CORPORATION","UNIVERSITY","RESEARCH_INSTITUTION","INVESTOR","GOVERNMENT_AGENCY","PUBLIC_PROGRAM"])assert.ok(types.has(type as never));});
test("validates entity, link, relationship and source integrity",()=>{const result=validateOrganizationData(organizationProfiles,organizationRelationships,organizationSources,new Set(organizationIndustries.map(x=>x.id)),new Set(organizationTechnologies.map(x=>x.id)),new Set(organizationRegions.map(x=>x.id)));assert.equal(result.valid,true,JSON.stringify(result));});
test("filters search, type, role, industry, technology, region, ecosystem and evidence",()=>{const first=organizationProfiles[0];assert.ok(filterOrganizations(organizationProfiles,{search:first.localizedName.zh}).some(x=>x.id===first.id));assert.ok(filterOrganizations(organizationProfiles,{type:"STARTUP"}).every(x=>x.organizationType==="STARTUP"));assert.ok(filterOrganizations(organizationProfiles,{role:"RESEARCH"}).every(x=>x.roles.some(r=>r.role==="RESEARCH")));assert.ok(filterOrganizations(organizationProfiles,{industryId:first.industryLinks[0].industryId,technologyId:first.technologyLinks[0].technologyId,regionId:first.regionLinks[0].regionId,evidenceStatus:"DEMO_RECORD"}).length>0);assert.ok(filterOrganizations(organizationProfiles,{ecosystemId:"sf-ai"}).length>0);});
test("parses stable cross-module organization query state",()=>{assert.deepEqual(parseOrganizationQuery("?organization=org-sf-1&industry=ai&technology=ai-agents&region=sf&type=STARTUP&ecosystem=sf-ai"),{organizationId:"org-sf-1",industryId:"ai",technologyId:"ai-agents",regionId:"sf",type:"STARTUP",ecosystemId:"sf-ai"});});
test("looks up detail profiles and preserves missing fields",()=>{const p=organizationProfiles.find(x=>x.id==="org-sf-5");assert.ok(p);assert.equal(p.foundedYear,null);assert.equal(p.website,null);assert.equal(organizationProfiles.find(x=>x.id==="missing"),undefined);});
test("separates demo entity identity from evidence and derived relationships",()=>{assert.ok(organizationProfiles.every(p=>p.entityStatus==="DEMO_ENTITY"&&p.evidenceStatus==="DEMO_RECORD"));assert.ok(organizationRelationships.every(r=>r.isDemo&&r.isDerived));});
test("calculates connectivity only from graph relationships",()=>{const p=organizationProfiles[0],m=organizationMetrics(p,organizationRelationships);assert.equal(m.connectivity,oneHopRelationships(p.id,organizationRelationships).length);assert.ok(m.relationshipDiversity>0);assert.ok(m.evidenceCoverage>=0&&m.evidenceCoverage<=100);});
test("sorts by descriptive dimensions",()=>{const sorted=sortOrganizations(organizationProfiles,"CONNECTIVITY",organizationRelationships);assert.ok(organizationMetrics(sorted[0],organizationRelationships).connectivity>=organizationMetrics(sorted.at(-1)!,organizationRelationships).connectivity);});
test("creates type-aware comparison without a universal quality score",()=>{const university=organizationProfiles.find(x=>x.organizationType==="UNIVERSITY")!,startup=organizationProfiles.find(x=>x.organizationType==="STARTUP")!;const rows=compareOrganizations(university,startup,organizationRelationships);assert.ok(rows.some(x=>x.key==="research"));assert.ok(rows.some(x=>x.key==="policy"));assert.ok(!rows.some(x=>/quality|score/i.test(x.key+x.label.en)));});
test("detects orphan relationships and verified identities without sources",()=>{const badRelations=[...organizationRelationships,{...organizationRelationships[0],id:"bad",targetOrganizationId:"missing"}];const badProfiles=[{...organizationProfiles[0],entityStatus:"VERIFIED_PUBLIC_ENTITY" as const,evidenceStatus:"DEMO_RECORD" as const,website:null},...organizationProfiles.slice(1)];const result=validateOrganizationData(badProfiles,badRelations,organizationSources,new Set(organizationIndustries.map(x=>x.id)),new Set(organizationTechnologies.map(x=>x.id)),new Set(organizationRegions.map(x=>x.id)));assert.ok(result.orphanRelationshipIds.includes("bad"));assert.ok(result.verifiedWithoutSourceIds.includes(organizationProfiles[0].id));});
