import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

async function render(pathname="/"){
 const workerUrl=new URL("../dist/server/index.js",import.meta.url);workerUrl.searchParams.set("test",`${process.pid}-${Date.now()}-${pathname}`);
 const {default:worker}=await import(workerUrl.href);
 return worker.fetch(new Request(`http://localhost${pathname}`,{headers:{accept:"text/html"}}),{ASSETS:{fetch:async()=>new Response("Not found",{status:404})}},{waitUntil(){},passThroughOnException(){}});
}
test("renders the NEXORA product routes",async()=>{
 for(const [path,expected] of [["/","Map what"],["/atlas","NEXORA Atlas"],["/radar","NEXORA Radar"],["/companies","NEXORA Organizations"],["/companies/org-sf-1","NEXORA Organizations"],["/ecosystems","NEXORA Ecosystems"],["/policy","NEXORA Policy Intelligence"],["/simulator","NEXORA Simulator"],["/data-status","NEXORA Data Status"],["/ai","NEXORA AI"]]){const response=await render(path);assert.equal(response.status,200);assert.match(response.headers.get("content-type")??"",/^text\/html\b/i);assert.match(await response.text(),new RegExp(expected,"i"));}
});
test("unknown routes return the intentional bilingual 404",async()=>{const response=await render("/route-that-does-not-exist");assert.equal(response.status,404);const html=await response.text();assert.match(html,/Signal unavailable/i);assert.match(html,/页面未找到/);});
test("home explains the connected evidence journey without fake live coordinates",async()=>{const html=await(await render("/")).text();assert.match(html,/evidence-based future-industry intelligence platform/i);assert.match(html,/One evidence trail, nine connected views/i);assert.match(html,/NO LIVE GEOLOCATION/i);assert.match(html,/DEMO COMPOSITE MODEL/i);assert.doesNotMatch(html,/SYNC 08:42:16|34\.05°N|LIVE SIGNAL MODEL/);});
test("all major routes use consistent future-industry metadata",async()=>{for(const path of ["/","/atlas","/radar","/ecosystems","/policy","/companies","/data-status","/ai","/simulator"]){const html=await(await render(path)).text();assert.match(html,/<title>[^<]*NEXORA[^<]*Future Industry Intelligence[^<]*<\/title>/i,path);}});
test("language preference uses one persistent bilingual control",async()=>{const [hook,components]=await Promise.all([readFile(new URL("../hooks/use-nexora-language.ts",import.meta.url),"utf8"),Promise.all(["dashboard","atlas","radar","ecosystems","policy-intelligence","organization-intelligence","data-status","nexora-ai-workspace","nexora-simulator"].map(name=>readFile(new URL(`../components/${name}.tsx`,import.meta.url),"utf8")))]);assert.match(hook,/localStorage\.setItem\(STORAGE_KEY/);assert.ok(components.every(source=>/useNexoraLanguage\(\)/.test(source)));});
test("NEXORA AI renders a bilingual evidence-first research workspace",async()=>{const html=await(await render("/ai")).text();assert.match(html,/Evidence-based intelligence for emerging industries/i);assert.match(html,/EVIDENCE-FIRST/i);assert.match(html,/NOT CONFIGURED/i);assert.match(html,/Suggested research questions/i);assert.match(html,/Evidence coverage/i);assert.match(html,/Data gaps/i);const [component,css,route]=await Promise.all([readFile(new URL("../components/nexora-ai-workspace.tsx",import.meta.url),"utf8"),readFile(new URL("../components/nexora-ai-workspace.module.css",import.meta.url),"utf8"),readFile(new URL("../app/api/ai/route.ts",import.meta.url),"utf8")]);assert.match(component,/setLang\("zh"\)/);assert.match(component,/Why this answer/);assert.match(css,/prefers-reduced-motion:\s*reduce/);assert.match(route,/maxQueryLength/);assert.doesNotMatch(component,/OPENAI_API_KEY|system prompt/i)});
test("cross-module pages hand stable context into NEXORA AI",async()=>{for(const path of ["/atlas","/radar","/ecosystems","/policy","/companies"]){const html=await(await render(path)).text();assert.match(html,/\/ai\?/i,`${path} must expose a contextual AI handoff`)}const home=await(await render("/")).text();assert.match(home,/action="\/ai"|href="\/ai"/i)});
test("Simulator renders a bilingual transparent scenario lab",async()=>{const html=await(await render("/simulator")).text();assert.match(html,/Explore how innovation ecosystems may evolve/i);assert.match(html,/PARTIALLY CALIBRATED/i);assert.match(html,/Sensitivity/i);assert.match(html,/Uncertainty/i);assert.match(html,/not forecast/i);const [component,css]=await Promise.all([readFile(new URL("../components/nexora-simulator.tsx",import.meta.url),"utf8"),readFile(new URL("../components/nexora-simulator.module.css",import.meta.url),"utf8")]);assert.match(component,/Innovation Ecosystem Evolution Model v1|innovationEcosystemModelV1/);assert.match(component,/SIMULATED/);assert.match(component,/AI scenario interpretation/i);assert.match(component,/no live model provider is configured/i);assert.match(component,/setLang\("zh"\)/);assert.match(component,/oneWaySensitivity|sensitivityRanking/);assert.match(component,/simulationToCsv/);assert.match(component,/window\.print/);assert.match(css,/prefers-reduced-motion:\s*reduce/);assert.match(css,/@media\s*\(max-width:\s*420px\)/)});
test("major intelligence modules expose contextual Simulator handoffs",async()=>{for(const path of ["/atlas","/radar","/ecosystems","/policy","/companies"]){const html=await(await render(path)).text();assert.match(html,/\/simulator\?/i,`${path} must expose a contextual Simulator handoff`)}const home=await(await render("/")).text();assert.match(home,/href="\/simulator/i)});
test("Data Status discloses hybrid coverage, health, quality and licensing",async()=>{const html=await(await render("/data-status")).text();assert.match(html,/Know what is observed, derived, demo, stale or unavailable/i);assert.match(html,/HYBRID MODE/i);assert.match(html,/OPENALEX/i);assert.match(html,/USPTO/i);assert.match(html,/NOT CONFIGURED|Not configured/i);assert.match(html,/Promotion quality gate/i);assert.match(html,/Source &amp; license registry/i);assert.match(html,/Coverage limitations/i);const [component,css]=await Promise.all([readFile(new URL("../components/data-status.tsx",import.meta.url),"utf8"),readFile(new URL("../components/data-status.module.css",import.meta.url),"utf8")]);assert.match(component,/setLang\("zh"\)/);assert.match(css,/prefers-reduced-motion:\s*reduce/);});
test("Organizations exposes bilingual entity intelligence, provenance and cross-navigation",async()=>{
 const html=await(await render("/companies")).text();assert.match(html,/Understand the organizations shaping emerging industries/i);assert.match(html,/Organization Landscape/i);assert.match(html,/Organization Explorer/i);assert.match(html,/Demo Entity/i);assert.match(html,/Entity Identity/i);assert.match(html,/Relationship Claims/i);assert.match(html,/not a quality score/i);assert.match(html,/No private people data/i);assert.match(html,/\/atlas\?region=/i);assert.match(html,/\/radar\?technology=/i);assert.match(html,/\/ecosystems\?/i);assert.match(html,/\/policy\?policy=/i);
 const [component,css]=await Promise.all([readFile(new URL("../components/organization-intelligence.tsx",import.meta.url),"utf8"),readFile(new URL("../components/organization-intelligence.module.css",import.meta.url),"utf8")]);assert.match(component,/setLang\("zh"\)/);assert.match(component,/filterOrganizations/);assert.match(component,/parseOrganizationQuery/);assert.match(component,/compareOrganizations/);assert.match(css,/prefers-reduced-motion:\s*reduce/);
});
test("Ecosystems exposes network intelligence, trust and cross-navigation",async()=>{
 const html=await(await render("/ecosystems")).text();assert.match(html,/Map the networks behind innovation/i);assert.match(html,/Innovation network canvas/i);assert.match(html,/DEMO/i);assert.match(html,/Evidence coverage/i);assert.match(html,/Ecosystem Health/i);assert.match(html,/\/atlas\?region=/i);assert.match(html,/\/radar\?technology=/i);assert.match(html,/\/companies\?region=/i);
 const [component,css]=await Promise.all([readFile(new URL("../components/ecosystems.tsx",import.meta.url),"utf8"),readFile(new URL("../components/ecosystems.module.css",import.meta.url),"utf8")]);assert.match(component,/setLang\("zh"\)/);assert.match(component,/betweennessCentrality/);assert.match(component,/neighborhood/);assert.match(css,/prefers-reduced-motion:\s*reduce/);
});
test("Policy exposes evidence-oriented intelligence and integrated navigation",async()=>{
 const html=await(await render("/policy")).text();assert.match(html,/Understand the policy forces shaping emerging industries/i);assert.match(html,/Policy Landscape/i);assert.match(html,/Policy Explorer/i);assert.match(html,/Observed Public Fact/i);assert.match(html,/Derived Classification/i);assert.match(html,/NEXORA Interpretation/i);assert.match(html,/Jurisdiction Comparison/i);assert.match(html,/not legal or regulatory advice/i);assert.match(html,/\/atlas\?region=/i);assert.match(html,/\/radar\?technology=/i);assert.match(html,/\/ecosystems\?technology=/i);assert.match(html,/\/companies\?industry=/i);
 const [component,css]=await Promise.all([readFile(new URL("../components/policy-intelligence.tsx",import.meta.url),"utf8"),readFile(new URL("../components/policy-intelligence.module.css",import.meta.url),"utf8")]);assert.match(component,/setLang\("zh"\)/);assert.match(component,/filterPolicies/);assert.match(component,/parsePolicyQuery/);assert.match(css,/prefers-reduced-motion:\s*reduce/);
});
test("Radar exposes trust, interaction and cross-navigation",async()=>{
 const html=await(await render("/radar")).text();
 assert.match(html,/Detect the signals shaping tomorrow/i);assert.match(html,/Emerging Opportunity Radar/i);assert.match(html,/Signal Explorer/i);assert.match(html,/DEMO DATA/i);assert.match(html,/\/atlas\?region=/i);assert.match(html,/\/companies\?technology=/i);
 const [component,css]=await Promise.all([readFile(new URL("../components/radar.tsx",import.meta.url),"utf8"),readFile(new URL("../components/radar.module.css",import.meta.url),"utf8")]);
 assert.match(component,/setLang\("zh"\)/);assert.match(component,/setSelectedId/);assert.match(component,/technologyMatchesFilters/);assert.match(css,/prefers-reduced-motion:\s*reduce/);
});
test("does not restore starter preview metadata",async()=>{const layout=await readFile(new URL("../app/layout.tsx",import.meta.url),"utf8");assert.doesNotMatch(layout,/codex-preview|Your site is taking shape|SkeletonPreview/);});
