import type { CalibrationCoverage,CalibrationRecord,ModelEvidence } from "../../domain/simulation.ts";
import { productionSnapshotDate } from "../../data/production/pilot.ts";

export const SIMULATION_SNAPSHOT_IDS=["openalex-production-pilot-2026-08-10","world-bank-production-pilot-2026-08-10","official-policy-pilot-2026-08-10","official-organization-pilot-2026-08-10"];
export const calibrationRecords:CalibrationRecord[]=[
 {id:"cal-research",variableId:"researchCapacity",classification:"OBSERVED_CALIBRATED",sourceId:"openalex-api",metricKey:"publication_count",transformation:"Mapped-topic annual counts normalized to a bounded scenario index; 2025 level anchors 55.",inputSnapshotId:SIMULATION_SNAPSHOT_IDS[0],timeWindow:"2020–2025",confidence:"MEDIUM",limitations:{en:"Topic mappings are curated proxies and global, not region-specific.",zh:"主题映射是策划代理，且为全球数据，并非区域数据。"}},
 {id:"cal-knowledge",variableId:"knowledgeStock",classification:"DERIVED_CALIBRATED",sourceId:"openalex-api",metricKey:"publication_count",transformation:"Lagged cumulative research index with assumed retention; baseline anchor 48.",inputSnapshotId:SIMULATION_SNAPSHOT_IDS[0],timeWindow:"2020–2025",confidence:"LOW",limitations:{en:"Retention and knowledge depreciation are assumptions; patents are absent.",zh:"知识保留与折旧属于假设；专利数据缺失。"}},
 ...["commercializationCapacity","startupBase","talentPool","infrastructure","policySupport","connectivity","marketAdoption"].map((variableId,i):CalibrationRecord=>({id:`cal-assumption-${i+1}`,variableId,classification:"NEXORA_ASSUMPTION",sourceId:variableId==="policySupport"?"official-policy":variableId==="connectivity"?"official-identity":null,metricKey:null,transformation:"Conceptual normalized baseline and bounded scenario range.",inputSnapshotId:variableId==="policySupport"?SIMULATION_SNAPSHOT_IDS[2]:variableId==="connectivity"?SIMULATION_SNAPSHOT_IDS[3]:null,timeWindow:null,confidence:"LOW",limitations:{en:"No sufficient longitudinal production series; this value is a model assumption.",zh:"缺少充分的纵向生产数据序列；该值属于模型假设。"}}))
];
export const calibrationCoverage:CalibrationCoverage={observed:11.1,derived:11.1,assumption:77.8,unavailable:3,basis:"Share of nine initial stock concepts; unavailable is a separate count of critical missing input families."};
export const modelEvidence:ModelEvidence[]=[
 {id:"ev-openalex",title:{en:"OpenAlex mapped-topic research series","zh":"OpenAlex 映射主题科研序列"},classification:"OBSERVED_EVIDENCE",sourceUrl:"https://developers.openalex.org/",sourceId:"openalex-api",snapshotId:SIMULATION_SNAPSHOT_IDS[0],modelVariableIds:["researchCapacity"],notes:{en:`Observed annual publication counts; snapshot ${productionSnapshotDate}.`,zh:`年度学术成果数量观测；快照日期 ${productionSnapshotDate}。`}},
 {id:"ev-knowledge",title:{en:"Derived knowledge-stock initialization","zh":"衍生知识存量初始化"},classification:"DERIVED_INPUT",sourceUrl:"/docs/SIMULATOR_CALIBRATION.md",sourceId:"openalex-api",snapshotId:SIMULATION_SNAPSHOT_IDS[0],modelVariableIds:["knowledgeStock"],notes:{en:"Uses OpenAlex input with explicit retention assumptions.",zh:"使用 OpenAlex 输入并明确知识保留假设。"}},
 {id:"ev-policy",title:{en:"Verified official program identities","zh":"已核验官方项目身份"},classification:"OBSERVED_EVIDENCE",sourceUrl:"https://www.nist.gov/chips",sourceId:"official-policy",snapshotId:SIMULATION_SNAPSHOT_IDS[2],modelVariableIds:["policySupport"],notes:{en:"Program identity is context only and does not calibrate policy effect.",zh:"项目身份仅作为背景，不校准政策效果。"}},
 {id:"ev-assumptions",title:{en:"Conceptual system-dynamics coefficients","zh":"概念系统动力学系数"},classification:"MODEL_ASSUMPTION",sourceUrl:"/docs/SCENARIO_ASSUMPTIONS.md",sourceId:null,snapshotId:null,modelVariableIds:["commercializationCapacity","startupBase","talentPool","infrastructure","policySupport","connectivity","marketAdoption"],notes:{en:"Bounded research-model assumptions, not empirical estimates.",zh:"有界研究模型假设，并非实证估计。"}},
 {id:"ev-missing-patents",title:{en:"Patent calibration unavailable","zh":"专利校准不可用"},classification:"UNAVAILABLE_INPUT",sourceUrl:"https://data.uspto.gov/",sourceId:"uspto-odp",snapshotId:null,modelVariableIds:["knowledgeStock","commercializationCapacity"],notes:{en:"USPTO production access is not configured; missing is not zero.",zh:"USPTO 生产访问尚未配置；缺失不等于零。"}},
 {id:"ev-missing-capital",title:{en:"Capital-flow calibration unavailable","zh":"资本流校准不可用"},classification:"UNAVAILABLE_INPUT",sourceUrl:null,sourceId:null,snapshotId:null,modelVariableIds:["startupBase"],notes:{en:"No verified capital-flow dataset is integrated.",zh:"尚未接入已核验资本流数据集。"}},
 {id:"ev-missing-network",title:{en:"Longitudinal ecosystem graph unavailable","zh":"纵向生态关系图不可用"},classification:"UNAVAILABLE_INPUT",sourceUrl:"/docs/ECOSYSTEMS_METHOD.md",sourceId:null,snapshotId:null,modelVariableIds:["connectivity"],notes:{en:"One verified relationship cannot calibrate aggregate network dynamics.",zh:"一条已核验关系不足以校准聚合网络动力。"}}
];
