import type { AuxiliaryVariable,CausalAssumption,CausalLink,FeedbackLoop,FlowVariable,ModelEquation,NetworkModifierConfig,SimulationModel,StockVariable } from "../../domain/simulation.ts";
import { modelParameters } from "../parameters/parameters.ts";

const stock=(id:StockVariable["id"],en:string,zh:string,initialValue:number,evidenceStatus:StockVariable["evidenceStatus"]):StockVariable=>({id,name:{en,zh},description:{en:`Normalized ${en.toLowerCase()} stock for scenario comparison.`,zh:`用于情景比较的标准化${zh}存量。`},unit:"bounded index (0–120)",equationId:`eq-${id}`,evidenceStatus,kind:"STOCK",initialValue,minimum:0,maximum:120});
export const stocks:StockVariable[]=[
 stock("researchCapacity","Research Capacity","科研能力",55,"OBSERVED_CALIBRATED"),stock("knowledgeStock","Technology Knowledge Stock","技术知识存量",48,"DERIVED_CALIBRATED"),stock("commercializationCapacity","Commercialization Capacity","商业化能力",40,"NEXORA_ASSUMPTION"),stock("startupBase","Startup Base","创业企业基础",35,"NEXORA_ASSUMPTION"),stock("talentPool","Skilled Talent Pool","高技能人才池",50,"NEXORA_ASSUMPTION"),stock("infrastructure","Innovation Infrastructure","创新基础设施",46,"NEXORA_ASSUMPTION"),stock("policySupport","Policy Support Capacity","政策支持能力",42,"NEXORA_ASSUMPTION"),stock("connectivity","Ecosystem Connectivity","生态连接能力",38,"NEXORA_ASSUMPTION"),stock("marketAdoption","Market Adoption Capacity","市场吸纳能力",34,"NEXORA_ASSUMPTION")
];
const flow=(id:string,en:string,zh:string,fromStock:FlowVariable["fromStock"],toStock:FlowVariable["toStock"]):FlowVariable=>({id,name:{en,zh},description:{en:`Annual ${en.toLowerCase()} flow.`,zh:`年度${zh}流量。`},unit:"index points / year",equationId:`eq-${id}`,evidenceStatus:id==="researchCreation"?"DERIVED_CALIBRATED":"NEXORA_ASSUMPTION",kind:"FLOW",fromStock,toStock});
export const flows:FlowVariable[]=[flow("researchCreation","Research Creation","研究创造",null,"researchCapacity"),flow("knowledgeCreation","Knowledge Creation","知识创造",null,"knowledgeStock"),flow("knowledgeDecay","Knowledge Decay","知识衰减","knowledgeStock",null),flow("commercializationFlow","Commercialization Flow","商业化流动",null,"commercializationCapacity"),flow("startupFormation","Startup Formation","创业形成",null,"startupBase"),flow("startupAttrition","Startup Attrition","创业退出","startupBase",null),flow("talentInflow","Talent Inflow","人才流入",null,"talentPool"),flow("talentOutflow","Talent Outflow","人才流出","talentPool",null),flow("infrastructureExpansion","Infrastructure Expansion","基础设施扩张",null,"infrastructure"),flow("policyImplementation","Policy Implementation","政策实施",null,"policySupport"),flow("connectivityFormation","Connectivity Formation","连接形成",null,"connectivity"),flow("technologyAdoption","Technology Adoption","技术吸纳",null,"marketAdoption")];
const aux=(id:string,en:string,zh:string):AuxiliaryVariable=>({id,name:{en,zh},description:{en:`Derived ${en.toLowerCase()} used by the scenario engine.`,zh:`情景引擎使用的衍生${zh}。`},unit:"index",equationId:`eq-${id}`,evidenceStatus:"NEXORA_ASSUMPTION",kind:"AUXILIARY"});
export const auxiliaries=[aux("innovationOutput","Innovation Output","创新产出"),aux("talentPressure","Talent Pressure","人才压力"),aux("policySaturation","Policy Saturation","政策饱和"),aux("networkModifier","Network Modifier","网络修正项")];

export const causalAssumptions:CausalAssumption[]=[
 {id:"ca-research-knowledge",sourceVariable:"researchCapacity",targetVariable:"knowledgeStock",direction:"POSITIVE",functionalForm:"bounded multiplicative flow",lag:0,evidenceBasis:{en:"Theory-supported stock-flow relationship; coefficient is not empirically validated.",zh:"理论支持的存量—流量关系；系数未经实证验证。"},confidence:"MEDIUM",assumptionStatus:"THEORY_SUPPORTED",methodologyReference:"/docs/SYSTEM_DYNAMICS_MODEL.md"},
 {id:"ca-knowledge-commercialization",sourceVariable:"knowledgeStock",targetVariable:"commercializationCapacity",direction:"POSITIVE",functionalForm:"delayed saturating transfer",lag:2,evidenceBasis:{en:"Conceptual research-to-commercialization pathway.",zh:"概念性的科研到商业化路径。"},confidence:"LOW",assumptionStatus:"NEXORA_ASSUMPTION",methodologyReference:"/docs/SYSTEM_DYNAMICS_MODEL.md"},
 {id:"ca-connectivity-diffusion",sourceVariable:"connectivity",targetVariable:"knowledgeStock",direction:"POSITIVE",functionalForm:"bounded modifier",lag:0,evidenceBasis:{en:"Network theory; current production graph is insufficient for causal calibration.",zh:"基于网络理论；当前生产关系图不足以进行因果校准。"},confidence:"LOW",assumptionStatus:"THEORY_SUPPORTED",methodologyReference:"/docs/SYSTEM_DYNAMICS_MODEL.md"},
 {id:"ca-talent-constraint",sourceVariable:"talentPressure",targetVariable:"researchCapacity",direction:"NEGATIVE",functionalForm:"balancing penalty",lag:0,evidenceBasis:{en:"Conceptual capacity constraint.",zh:"概念性的能力约束。"},confidence:"LOW",assumptionStatus:"NEXORA_ASSUMPTION",methodologyReference:"/docs/SCENARIO_ASSUMPTIONS.md"},
 {id:"ca-policy-research",sourceVariable:"policySupport",targetVariable:"researchCapacity",direction:"POSITIVE",functionalForm:"delayed diminishing return",lag:1,evidenceBasis:{en:"Policy mechanism hypothesis; verified program identity is not effect evidence.",zh:"政策机制假设；已核验项目身份并非效果证据。"},confidence:"LOW",assumptionStatus:"NEXORA_ASSUMPTION",methodologyReference:"/docs/POLICY_SCENARIO_METHOD.md"},
 {id:"ca-adoption-startups",sourceVariable:"marketAdoption",targetVariable:"startupBase",direction:"POSITIVE",functionalForm:"bounded survival modifier",lag:0,evidenceBasis:{en:"Conceptual market reinforcement.",zh:"概念性的市场强化机制。"},confidence:"LOW",assumptionStatus:"NEXORA_ASSUMPTION",methodologyReference:"/docs/SYSTEM_DYNAMICS_MODEL.md"}
];
export const equations:ModelEquation[]=[
 {id:"eq-policySupport",targetVariable:"policySupport",expression:"P(t+1)=P(t)+η·(bundle(t−lag)·100−P(t))·0.12·(1−P/140)−0.01P",description:{en:"Delayed policy implementation with diminishing returns.",zh:"包含时滞与边际递减的政策实施。"},units:"index",dependencies:["policyImplementationEfficiency","policyImplementationLag"],version:"eq-v1.0.0",assumptionIds:["ca-policy-research"]},
 {id:"eq-researchCapacity",targetVariable:"researchCapacity",expression:"R(t+1)=R(t)+R·ρ·policy·talent·infrastructure·(1−R/140)−0.015R",description:{en:"Research creation is bounded by capacity, talent and infrastructure.",zh:"研究创造受能力、人才与基础设施约束。"},units:"index",dependencies:["researchProductivity","publicResearchSupport"],version:"eq-v1.0.0",assumptionIds:["ca-policy-research","ca-talent-constraint"]},
 {id:"eq-knowledgeStock",targetVariable:"knowledgeStock",expression:"K(t+1)=K(t)+researchCreation·(0.55+diffusionModifier)−(1−retention)·K",description:{en:"Knowledge accumulates from research and decays at an assumed rate.",zh:"知识由研究积累并按假设速率衰减。"},units:"index",dependencies:["knowledgeRetention","knowledgeDiffusionRate"],version:"eq-v1.0.0",assumptionIds:["ca-research-knowledge","ca-connectivity-diffusion"]},
 {id:"eq-commercializationCapacity",targetVariable:"commercializationCapacity",expression:"C(t+1)=C(t)+K(t−lag)·transfer·efficiency·network·(1−C/135)−0.02C",description:{en:"Delayed, saturating knowledge transfer builds commercialization capacity.",zh:"延迟且趋于饱和的知识转移形成商业化能力。"},units:"index",dependencies:["technologyTransferRate","commercializationEfficiency","researchCommercializationLag"],version:"eq-v1.0.0",assumptionIds:["ca-knowledge-commercialization","ca-connectivity-diffusion"]},
 {id:"eq-startupBase",targetVariable:"startupBase",expression:"S(t+1)=S(t)+C·formation·market·capital−S·(1−survival)·constraint",description:{en:"Startup formation and attrition are aggregate scenario flows, not company forecasts.",zh:"创业形成与退出是聚合情景流量，并非企业预测。"},units:"index",dependencies:["startupFormationRate","startupSurvivalRate","capitalAvailability"],version:"eq-v1.0.0",assumptionIds:["ca-adoption-startups"]},
 {id:"eq-talentPool",targetVariable:"talentPool",expression:"T(t+1)=T(t)+growth·workforce(t−lag)·(110−T)−constraint·0.02T",description:{en:"Talent supply responds with delay and a scenario constraint.",zh:"人才供给存在时滞并受到情景约束。"},units:"index",dependencies:["talentGrowthRate","talentConstraint","talentDevelopmentLag"],version:"eq-v1.0.0",assumptionIds:["ca-talent-constraint"]},
 {id:"eq-infrastructure",targetVariable:"infrastructure",expression:"I(t+1)=I(t)+0.08·infra(t−lag)·(110−I)·(1−I/145)−0.01I",description:{en:"Infrastructure investment has a lag and diminishing marginal effect.",zh:"基础设施投入具有时滞与边际递减。"},units:"index",dependencies:["researchInfrastructure","infrastructureLag"],version:"eq-v1.0.0",assumptionIds:["ca-policy-research"]},
 {id:"eq-connectivity",targetVariable:"connectivity",expression:"N(t+1)=N(t)+0.04·coordination·diversity·(115−N)−0.025·bridgeDependency·N",description:{en:"Aggregate connectivity gains are offset by bridge concentration fragility.",zh:"聚合连接增长会受到桥接集中脆弱性的抵消。"},units:"index",dependencies:["coordinationSupport","relationshipDiversity","bridgeDependency"],version:"eq-v1.0.0",assumptionIds:["ca-connectivity-diffusion"]},
 {id:"eq-marketAdoption",targetVariable:"marketAdoption",expression:"A(t+1)=A(t)+rate·(commercialization+procurement)·(110−A)/100−0.01A",description:{en:"Adoption responds to commercialization and procurement assumptions.",zh:"市场吸纳响应商业化与采购假设。"},units:"index",dependencies:["marketAdoptionRate","publicProcurement"],version:"eq-v1.0.0",assumptionIds:["ca-adoption-startups"]},
 {id:"eq-innovationOutput",targetVariable:"innovationOutput",expression:"0.28R+0.22K+0.18C+0.12S+0.10N+0.10A",description:{en:"Descriptive scenario output index; not a forecast or universal score.",zh:"描述性情景产出指数；不是预测或通用评分。"},units:"index",dependencies:["researchCapacity","knowledgeStock","commercializationCapacity","startupBase","connectivity","marketAdoption"],version:"eq-v1.0.0",assumptionIds:[]}
];
export const causalLinks:CausalLink[]=causalAssumptions.map(a=>({id:`link-${a.id}`,from:a.sourceVariable,to:a.targetVariable,direction:a.direction,lag:a.lag,assumptionId:a.id}));
export const feedbackLoops:FeedbackLoop[]=[
 {id:"loop-r1",name:{en:"Research reinforcement","zh":"科研强化回路"},type:"REINFORCING",variableIds:["researchCapacity","knowledgeStock","commercializationCapacity","startupBase","connectivity"],description:{en:"Research can increase knowledge, commercialization, ecosystem activity and collaboration capacity.",zh:"科研可能提升知识、商业化、生态活动与协作能力。"}},
 {id:"loop-r2",name:{en:"Commercialization reinforcement","zh":"商业化强化回路"},type:"REINFORCING",variableIds:["commercializationCapacity","marketAdoption","startupBase"],description:{en:"Commercialization and adoption can reinforce aggregate startup activity.",zh:"商业化与市场吸纳可能强化聚合创业活动。"}},
 {id:"loop-b1",name:{en:"Talent capacity balance","zh":"人才能力平衡回路"},type:"BALANCING",variableIds:["researchCapacity","talentPressure","talentPool"],description:{en:"Growth raises capacity pressure when talent supply lags.",zh:"当人才供给滞后时，增长会提高能力压力。"}},
 {id:"loop-b2",name:{en:"Policy saturation balance","zh":"政策饱和平衡回路"},type:"BALANCING",variableIds:["policySupport","infrastructure","researchCapacity"],description:{en:"Additional support has lower incremental effect as capacity saturates.",zh:"随着能力趋于饱和，新增支持的边际效果下降。"}}
];
export const networkModifiers:NetworkModifierConfig[]=[{id:"knowledge-diffusion-modifier",targetParameter:"knowledgeDiffusionRate",input:"normalized aggregate connectivity scenario index",formula:"base diffusion × (1 + connectivity/100 × networkConnectivityEffect) × (1 − 0.25 × bridgeDependency)",minimum:.5,maximum:1.5,status:"NEXORA_ASSUMPTION",limitations:{en:"Not calibrated from the current Demo graph; centrality is not treated as causal.",zh:"未使用当前 Demo 关系图校准；中心性不被视为因果。"}}];

export const innovationEcosystemModelV1:SimulationModel={id:"innovation-ecosystem-evolution-v1",name:{en:"Innovation Ecosystem Evolution Model v1","zh":"创新生态演化模型 v1"},version:"sim-model-v1.0.0",equationVersion:"eq-v1.0.0",solverVersion:"euler-annual-v1.0.0",status:"PARTIALLY_CALIBRATED",modelType:"CONCEPTUAL_RESEARCH_MODEL",timeStep:"ANNUAL",supportedHorizons:[5,10,15],stocks,flows,auxiliaries,parameters:modelParameters,equations,causalAssumptions,causalLinks,feedbackLoops,networkModifiers};
