"use client";
import Link from "@/components/safe-link";
import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { atlasHotspots, atlasIndustries, metricOrder, type AtlasHotspot, type IndustryId } from "@/data/demo/atlas";
import { useNexoraLanguage } from "@/hooks/use-nexora-language";
import { parseAtlasQuery } from "@/lib/product-query";
import styles from "./atlas.module.css";

type Lang="en"|"zh"; type Layer=IndustryId|"all"; type PanelTab="overview"|"ecosystem"|"evidence";
const ui={
 en:{atlas:"NEXORA Atlas",tagline:"Map the geography of emerging industries.",back:"Intelligence overview",live:"GLOBAL PROTOTYPE / 18 ECOSYSTEMS",all:"All industries",filters:"Industry layers",zoomIn:"Zoom in",zoomOut:"Zoom out",reset:"Reset world view",strength:"Relative ecosystem strength",demo:"DEMO DATA",region:"Region intelligence",close:"Close panel",tabs:["Overview","Ecosystem","Evidence"],primary:"Primary strengths",metrics:"Prototype intelligence metrics",tech:"Emerging technologies",universities:"Research institutions",organizations:"Representative organizations",policy:"Public policy",signals:"Emerging signals",sources:"Sources & method",sourceText:"Current values are structured prototype indices. They demonstrate product behavior and are not verified production facts.",compare:"Regional comparison",compareSub:"Compare ecosystem capabilities across a common prototype index",versus:"VERSUS",industry:"Industry view",industrySub:"Start with a technology layer and identify its strongest ecosystems",top:"Leading ecosystems",specialization:"Technology specialization",method:"Sources, confidence & methodology",methodSub:"Designed for source-level traceability and transparent interpretation",observed:"Observed public data",derived:"Derived metric",composite:"NEXORA composite score",interpretation:"AI interpretation",observedDesc:"Directly retrieved from an authoritative public source.",derivedDesc:"Calculated from observed public records with documented method.",compositeDesc:"A transparent combination of multiple comparable metrics.",interpretationDesc:"Model-generated analysis, always labeled separately.",mapLabel:"Interactive world innovation map",textAlt:"Text view of strongest ecosystems",mapHint:"SELECT A SIGNAL TO OPEN REGIONAL INTELLIGENCE",retrieved:"Prototype snapshot · Aug 2026",confidence:"Prototype confidence",showMap:"Return to map"},
 zh:{atlas:"NEXORA 全球产业图谱",tagline:"探索未来产业的全球创新地理。",back:"返回情报总览",live:"全球原型数据 / 18 个创新生态",all:"全部产业",filters:"产业图层",zoomIn:"放大",zoomOut:"缩小",reset:"重置全球视图",strength:"相对生态强度",demo:"演示数据",region:"区域情报",close:"关闭面板",tabs:["概览","创新生态","证据来源"],primary:"优势产业",metrics:"原型情报指标",tech:"新兴技术",universities:"科研机构",organizations:"代表性组织",policy:"公共政策",signals:"新兴信号",sources:"来源与方法",sourceText:"当前数值为结构化原型指数，仅用于展示产品能力，并非经过验证的生产数据事实。",compare:"区域比较",compareSub:"在统一的原型指数体系下比较创新生态能力",versus:"对比",industry:"产业视角",industrySub:"从技术图层出发，识别全球领先创新生态",top:"领先创新生态",specialization:"技术专长",method:"来源、置信度与方法",methodSub:"面向来源级可追溯性与透明解读而设计",observed:"公共观测数据",derived:"衍生指标",composite:"NEXORA 综合评分",interpretation:"AI 解读",observedDesc:"直接来自权威公共来源的观测记录。",derivedDesc:"依据公开记录和文档化方法计算的指标。",compositeDesc:"由多个可比指标透明组合形成的综合评分。",interpretationDesc:"由模型生成并始终单独标识的分析。",mapLabel:"全球创新交互地图",textAlt:"领先创新生态文本视图",mapHint:"选择热点以打开区域情报",retrieved:"原型快照 · 2026 年 8 月",confidence:"原型置信度",showMap:"返回地图"}
} as const;

const lands=["northAmerica","southAmerica","greenland","europe","africa","asia","india","australia"] as const;
const pos=(h:AtlasHotspot)=>({"--x":`${((h.longitude+180)/360)*100}%`,"--y":`${((90-h.latitude)/180)*100}%`} as CSSProperties);
const policyJurisdiction=(region:AtlasHotspot)=>region.id==="sf"||region.id==="la"?"california":["paris","berlin"].includes(region.id)?"european-union":region.country.en.toLowerCase().replaceAll(" ","-");

export function Atlas(){
 const [lang,setLang]=useNexoraLanguage(),[layer,setLayer]=useState<Layer>("all"),[selectedId,setSelectedId]=useState("sf"),[zoom,setZoom]=useState(1),[tab,setTab]=useState<PanelTab>("overview"),[panel,setPanel]=useState(true),[left,setLeft]=useState("sf"),[right,setRight]=useState("shenzhen");
 useEffect(()=>{const timer=window.setTimeout(()=>{const query=parseAtlasQuery(window.location.search);if(query.regionId){setSelectedId(query.regionId);setPanel(true)}if(query.industryId)setLayer(query.industryId)},0);return()=>window.clearTimeout(timer)},[]);
 const t=lang==="zh"?{...ui.zh,tagline:"解析未来产业的全球创新版图"}:ui.en, selected=atlasHotspots.find(h=>h.id===selectedId)??atlasHotspots[0], leftRegion=atlasHotspots.find(h=>h.id===left)!,rightRegion=atlasHotspots.find(h=>h.id===right)!;
 const focusIndustry=layer==="all"?atlasIndustries[0]:atlasIndustries.find(i=>i.id===layer)!;
 const ranked=useMemo(()=>[...atlasHotspots].sort((a,b)=>(b.industries[focusIndustry.id]??0)-(a.industries[focusIndustry.id]??0)).slice(0,6),[focusIndustry.id]);
 const select=(id:string)=>{setSelectedId(id);setPanel(true);setTab("overview")};
 return <main className={styles.atlas}>
  <header className={styles.header}><div className={styles.brandLine}><Link href="/" className={styles.brand}><span>N</span>NEXORA</Link><span className={styles.divider}/><Link href="/" className={styles.back}>← {t.back}</Link></div><div className={styles.headerActions}><span className={styles.live}><i/>{t.live}</span><div className={styles.lang}><button className={lang==="en"?styles.active:""} onClick={()=>setLang("en")}>EN</button><button className={lang==="zh"?styles.active:""} onClick={()=>setLang("zh")}>中文</button></div></div></header>
  <section className={styles.intro}><div><p>GLOBAL INDUSTRY GEOGRAPHY / 02</p><h1>{t.atlas}</h1><h2>{t.tagline}</h2></div><div className={styles.coordinates}>WORLD VIEW<br/>LAYER 09 / REGION 18<br/>UTC 23:24:08</div></section>
  <section className={styles.mapSection} aria-label={t.mapLabel}>
   <div className={styles.filterBar}><div className={styles.filterTitle}>{t.filters}<span>09 ACTIVE LAYERS</span></div><div className={styles.filters}><button className={layer==="all"?styles.selectedFilter:""} onClick={()=>setLayer("all")}>{t.all}</button>{atlasIndustries.map(i=><button key={i.id} className={layer===i.id?styles.selectedFilter:""} onClick={()=>setLayer(i.id)}><b>{i.code}</b>{i.name[lang]}</button>)}</div></div>
   <div className={styles.mapViewport}>
    <div className={styles.mapGrid}/><div className={styles.mapGlow}/>
    <div className={styles.mapInner} style={{transform:`scale(${zoom})`}}>{lands.map(l=><i key={l} className={`${styles.land} ${styles[l]}`}/>)}<i className={styles.equator}/><i className={styles.meridian}/>{atlasHotspots.map(h=>{const strength=layer==="all"?Math.round(h.metrics.reduce((n,m)=>n+m.value,0)/h.metrics.length):(h.industries[layer]??38);return <button key={h.id} onClick={()=>select(h.id)} className={`${styles.hotspot} ${h.id===selectedId?styles.hotspotActive:""}`} style={{...pos(h),"--strength":strength,"--size":`${8+strength/12}px`} as CSSProperties} aria-label={`${h.name[lang]} — ${t.strength} ${strength}`}><i/><span>{h.name[lang]}</span></button>})}</div>
    <div className={styles.mapMeta}><span>{t.mapHint}</span><b>{layer==="all"?t.all:focusIndustry.name[lang]}</b><small>{t.retrieved}</small></div>
    <div className={styles.zoom}><button onClick={()=>setZoom(z=>Math.min(1.8,+(z+.2).toFixed(1)))} aria-label={t.zoomIn}>+</button><span>{Math.round(zoom*100)}%</span><button onClick={()=>setZoom(z=>Math.max(1,+(z-.2).toFixed(1)))} aria-label={t.zoomOut}>−</button><button onClick={()=>setZoom(1)} aria-label={t.reset}>◎</button></div>
    <div className={styles.mapLegend}><span><i className={styles.legendHigh}/>{t.strength}</span><span><i className={styles.legendDemo}/>{t.demo}</span></div>
    <div className={styles.textHotspots}><strong>{t.textAlt}</strong>{ranked.slice(0,5).map((h,i)=><button key={h.id} onClick={()=>select(h.id)}><b>0{i+1}</b><span>{h.name[lang]}</span><em>{h.industries[focusIndustry.id]??"—"}</em></button>)}</div>
    {panel&&<RegionPanel region={selected} lang={lang} t={t} tab={tab} setTab={setTab} close={()=>setPanel(false)}/>} {!panel&&<button className={styles.restorePanel} onClick={()=>setPanel(true)}>{t.region} →</button>}
   </div>
  </section>
  <section className={styles.analysisSection}><div className={styles.sectionHeading}><span>03 / COMPARE</span><div><h2>{t.compare}</h2><p>{t.compareSub}</p></div></div><div className={styles.compareControls}><select value={left} onChange={e=>setLeft(e.target.value)} aria-label={t.compare}>{atlasHotspots.map(h=><option value={h.id} key={h.id}>{h.name[lang]}</option>)}</select><span>{t.versus}</span><select value={right} onChange={e=>setRight(e.target.value)} aria-label={t.compare}>{atlasHotspots.map(h=><option value={h.id} key={h.id}>{h.name[lang]}</option>)}</select></div><div className={styles.comparison}><div className={styles.compareNames}><strong>{leftRegion.name[lang]}</strong><strong>{rightRegion.name[lang]}</strong></div>{metricOrder.map(key=>{const a=leftRegion.metrics.find(m=>m.key===key)!,b=rightRegion.metrics.find(m=>m.key===key)!;return <div className={styles.compareRow} key={key}><div><b>{a.value}</b><i style={{width:`${a.value}%`}}/></div><span>{a.name[lang]}</span><div><b>{b.value}</b><i style={{width:`${b.value}%`}}/></div></div>})}</div></section>
  <section className={`${styles.analysisSection} ${styles.industrySection}`}><div className={styles.sectionHeading}><span>04 / INDUSTRY</span><div><h2>{t.industry}</h2><p>{t.industrySub}</p></div></div><div className={styles.industryView}><div className={styles.industryLead}><span>{focusIndustry.code}</span><h3>{focusIndustry.name[lang]}</h3><p>{t.specialization}</p><div className={styles.techTags}>{selected.technologies.map(x=><i key={x.en}>{x[lang]}</i>)}</div></div><div className={styles.topEcosystems}><h3>{t.top}</h3>{ranked.map((h,i)=><button key={h.id} onClick={()=>{select(h.id);window.scrollTo({top:260,behavior:"smooth"})}}><span>0{i+1}</span><b>{h.name[lang]}</b><i><em style={{width:`${h.industries[focusIndustry.id]??0}%`}}/></i><strong>{h.industries[focusIndustry.id]??"—"}</strong></button>)}</div></div></section>
  <section className={`${styles.analysisSection} ${styles.methodSection}`}><div className={styles.sectionHeading}><span>05 / METHOD</span><div><h2>{t.method}</h2><p>{t.methodSub}</p></div></div><div className={styles.confidenceGrid}>{[[t.observed,t.observedDesc,"01"],[t.derived,t.derivedDesc,"02"],[t.composite,t.compositeDesc,"03"],[t.interpretation,t.interpretationDesc,"04"]].map(x=><article key={x[2]}><span>{x[2]}</span><h3>{x[0]}</h3><p>{x[1]}</p></article>)}</div><div className={styles.methodFoot}><span>NEXORA ATLAS METHOD / PROTOTYPE v0.2</span><span>{t.sourceText}</span></div></section>
  <footer className={styles.footer}><span>NEXORA / FUTURE INDUSTRY INTELLIGENCE</span><span>PUBLIC DATA · TRACEABLE METHODS · RESPONSIBLE INTERPRETATION</span></footer>
 </main>
}

function RegionPanel({region,lang,t,tab,setTab,close}:{region:AtlasHotspot;lang:Lang;t:typeof ui[Lang];tab:PanelTab;setTab:(x:PanelTab)=>void;close:()=>void}){
 const strengths=atlasIndustries.filter(i=>region.industries[i.id]).sort((a,b)=>(region.industries[b.id]??0)-(region.industries[a.id]??0)).slice(0,4);
 return <aside className={styles.regionPanel} aria-label={`${t.region}: ${region.name[lang]}`}><div className={styles.panelHead}><span>{t.region}<i>{t.demo}</i></span><button onClick={close} aria-label={t.close}>×</button></div><div className={styles.regionTitle}><small>{region.zone} / {region.country[lang]}</small><h2>{region.name[lang]}</h2><p>{region.overview[lang]}</p></div><div className={styles.panelTabs}>{(["overview","ecosystem","evidence"] as PanelTab[]).map((x,i)=><button className={tab===x?styles.tabActive:""} onClick={()=>setTab(x)} key={x}>{t.tabs[i]}</button>)}</div>
{tab==="overview"&&<><div className={styles.panelLabel}>{t.primary}</div><div className={styles.strengths}>{strengths.map(i=><span key={i.id}>{i.name[lang]}<b>{region.industries[i.id]}</b></span>)}</div><div className={styles.panelLabel}>{t.metrics}</div><div className={styles.metrics}>{region.metrics.map(m=><div key={m.id}><span>{m.name[lang]}<i>{m.isDemo?t.demo:""}</i></span><b>{m.value}</b><em><i style={{width:`${m.value}%`}}/></em></div>)}</div><Link className={styles.radarLink} href={`/radar?region=${encodeURIComponent(region.name.en)}`}>{lang==="en"?"View emerging technologies":"查看新兴技术"} →</Link><Link className={styles.radarLink} href={`/ecosystems?region=${encodeURIComponent(region.id)}`}>{lang==="en"?"Map ecosystem relationships":"绘制生态关系网络"} →</Link><Link className={styles.radarLink} href={`/policy?jurisdiction=${policyJurisdiction(region)}`}>{lang==="en"?"View Policy Landscape":"查看政策图谱"} →</Link><Link className={styles.radarLink} href={`/companies?region=${region.id}`}>{lang==="en"?"Explore Organizations":"探索相关组织"} →</Link><Link className={styles.radarLink} href={`/ai?region=${region.id}`}>{lang==="en"?"Ask NEXORA about this region":"询问 NEXORA 此区域"} →</Link><Link className={styles.radarLink} href={`/simulator?region=${region.id}`}>{lang==="en"?"Simulate ecosystem scenario":"模拟生态情景"} →</Link></>}
 {tab==="ecosystem"&&<div className={styles.detailGroups}><Detail title={t.tech} items={region.technologies} lang={lang}/><Detail title={t.universities} items={region.universities} lang={lang}/><Detail title={t.organizations} items={region.organizations} lang={lang}/><Detail title={t.policy} items={region.policies} lang={lang}/><Detail title={t.signals} items={region.signals} lang={lang}/></div>}
 {tab==="evidence"&&<div className={styles.evidence}><h3>{t.sources}</h3><p>{t.sourceText}</p><div><span>NEXORA Prototype Method</span><b>METHOD / COMPOSITE</b></div><div><span>{t.retrieved}</span><b>{t.confidence}: 55%</b></div><code>OBSERVED → DERIVED → COMPOSITE → INTERPRETATION</code></div>}
 </aside>
}
function Detail({title,items,lang}:{title:string;items:{en:string;zh:string}[];lang:Lang}){return <section><h3>{title}</h3>{items.map(i=><p key={i.en}>↗ {i[lang]}</p>)}</section>}
