"use client";
import { useState } from "react";
import Link from "next/link";
import { hotspots, kpis, opportunities, policies } from "@/data/demo/dashboard";

const copy = {
  en:{ home:"Home", overview:"Intelligence Overview", nav:[["Atlas","Global Industry Map"],["Radar","Emerging Opportunities"],["Companies","Startup Explorer"],["Ecosystems","Innovation Networks"],["Policy","Policy Intelligence"],["Simulator","Ecosystem Simulator"],["Nexora AI","Research Copilot"]], eyebrow:"GLOBAL FUTURE INDUSTRY INTELLIGENCE", h1a:"Map what’s emerging.",h1b:"Understand what drives it.",h1c:"See what comes next.", intro:"NEXORA is an intelligence platform for exploring emerging industries, technologies, innovation ecosystems, and public policy.", atlas:"Explore the Atlas",signals:"Explore Emerging Signals",live:"PROTOTYPE DATA ACTIVE", kpi:["Startups","Funding","Patents","Research Papers","Policies Tracked","Talent"], intelligence:"Global intelligence signals", demo:"Structured prototype dataset", opportunity:"Emerging Opportunities Radar",opSub:"Signals across science, capital, policy and talent",ranking:"Opportunity Ranking",network:"Innovation Ecosystem Network",netSub:"A connected view of institutions shaping the frontier",hotspots:"Global Innovation Hotspots",hotSub:"Regional capability and momentum indicators",policy:"Policy Intelligence",policySub:"Official public policy signal preview",ai:"Nexora AI Research Copilot", aiSub:"Ask cross-domain questions across the intelligence graph", questions:["Which industries are accelerating fastest?","Compare AI ecosystems across regions.","Which policies support biotechnology startups?"], placeholder:"Ask NEXORA a research question...", send:"Ask",source:"Official source",note:"All values shown are structured demo data for product prototyping — not production facts.",provenance:"Source facts · Derived metrics · AI interpretation are kept distinct."},
  zh:{ home:"首页", overview:"情报总览", nav:[["产业图谱","全球产业地图"],["趋势雷达","新兴机会信号"],["公司","创新企业探索"],["创新生态","创新网络"],["政策","政策情报"],["模拟器","生态系统模拟"],["Nexora AI","研究智能助手"]], eyebrow:"全球未来产业情报平台", h1a:"洞察正在崛起的产业。",h1b:"理解背后的驱动力。",h1c:"预见未来的方向。", intro:"NEXORA 是用于探索新兴产业、前沿技术、创新生态系统与公共政策的全球情报平台。", atlas:"探索产业图谱",signals:"查看新兴信号",live:"原型数据已启用", kpi:["创新企业","融资规模","专利","研究论文","追踪政策","专业人才"], intelligence:"全球情报信号", demo:"结构化原型数据集", opportunity:"新兴机会雷达",opSub:"跨科研、资本、政策与人才的综合信号",ranking:"机会潜力排名",network:"创新生态网络",netSub:"洞察塑造产业前沿的机构连接",hotspots:"全球创新热点",hotSub:"区域创新能力与发展动能指标",policy:"政策情报",policySub:"权威公共政策信号预览",ai:"Nexora AI 研究助手", aiSub:"基于未来产业知识图谱进行跨领域提问", questions:["哪些产业正在加速发展？","比较不同地区的 AI 创新生态。","哪些公共政策支持生物技术初创企业？"], placeholder:"向 NEXORA 提出研究问题…", send:"提问",source:"官方来源",note:"当前全部数值均为产品原型所用的结构化演示数据，并非生产环境事实。",provenance:"来源事实 · 衍生指标 · AI 解读在架构中严格区分。"}
} as const;

export function Dashboard(){
 const [lang,setLang]=useState<"en"|"zh">("en"); const [menu,setMenu]=useState(false); const t=copy[lang];
 return <div className="app">
  <aside className={`sidebar ${menu?"open":""}`}><div className="brand"><span className="brand-mark">N</span>NEXORA</div><nav className="nav" aria-label="Primary navigation"><Link className="nav-link active" href="/"><span className="nav-icon">01</span><span><span className="nav-title">{t.home}</span><span className="nav-sub">{t.overview}</span></span></Link>{t.nav.map((n,i)=><Link className="nav-link" href={`/${["atlas","radar","companies","ecosystems","policy","simulator","ai"][i]}`} key={n[0]}><span className="nav-icon">{String(i+2).padStart(2,"0")}</span><span><span className="nav-title">{n[0]}</span><span className="nav-sub">{n[1]}</span></span></Link>)}</nav><div className="side-foot">NEXORA FOUNDATION<br/>INTELLIGENCE SYSTEM / 01</div></aside>
  <main className="main"><header className="topbar"><div className="top-actions"><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation">☰</button><span className="crumb">NEXORA / {t.overview}</span></div><div className="top-actions"><span className="live">{t.live}</span><div className="lang" aria-label="Language"><button className={lang==="en"?"on":""} onClick={()=>setLang("en")}>EN</button><button className={lang==="zh"?"on":""} onClick={()=>setLang("zh")}>中文</button></div></div></header>
  <div className="content"><section className="hero"><div className="hero-copy"><div className="eyebrow">{t.eyebrow}</div><h1><span>{t.h1a}</span><br/><span>{t.h1b}</span><br/><span className="accent">{t.h1c}</span></h1><p className="hero-p">{t.intro}</p><div className="btns"><Link className="btn primary" href="/atlas">{t.atlas} →</Link><a className="btn" href="#radar">{t.signals}</a></div></div><div className="hero-viz" aria-label="Stylized global innovation visualization"><div className="orbit o1"/><div className="orbit o2"/><div className="orbit o3"/><div className="globe"><i className="land a"/><i className="land b"/><i className="land c"/><i className="pulse p1"/><i className="pulse p2"/><i className="pulse p3"/></div><div className="viz-label">GLOBAL SIGNAL FIELD<br/>34.05°N / 118.24°W<br/>SYNC 08:42:16 UTC</div></div></section>
  <div className="section-head"><div><h2>{t.intelligence}</h2><p>{t.demo}</p></div><span className="section-tag">SIGNAL INDEX / 2026</span></div><section className="kpis">{kpis.map((k,i)=><article className="card kpi" key={k.key}><div className="kpi-label">{t.kpi[i]}</div><div className="kpi-value">{k.value}</div><div className="delta">↗ {k.delta}</div></article>)}</section>
  <div className="section-head" id="radar"><div><h2>{t.opportunity}</h2><p>{t.opSub}</p></div><span className="section-tag">LIVE SIGNAL MODEL</span></div><section className="grid-2"><article className="card panel"><div className="panel-title"><h3>{t.opportunity}</h3><span className="mini">MOMENTUM × MATURITY</span></div><div className="radar-wrap"><div className="radar"><i className="dot d1"/><i className="dot d2"/><i className="dot d3"/><i className="dot d4"/><i className="dot d5"/><span className="radar-label r1">AI AGENTS</span><span className="radar-label r2">QUANTUM</span><span className="radar-label r3">SYNBIO</span><span className="radar-label r4">BATTERIES</span><span className="radar-label r5">ROBOTICS</span></div></div></article><article className="card panel"><div className="panel-title"><h3>{t.ranking}</h3><span className="mini">NEXORA SCORE</span></div><div className="ranking">{opportunities.map((o,i)=><div className="rank-row" key={o.name}><span className="rank-num">0{i+1}</span><span className="rank-name">{lang==="zh"?o.zh:o.name}<small>{o.sector}</small></span><span><span className="score">{o.score}</span><span className="bar"><i style={{width:`${o.score}%`}}/></span></span><span className="trend">{o.trend}</span></div>)}</div></article></section>
  <div className="section-head"><div><h2>{t.network}</h2><p>{t.netSub}</p></div><div><span className="section-tag">KNOWLEDGE GRAPH PREVIEW</span><Link className="section-link" href="/ecosystems">{lang==="en"?"Explore ecosystems":"探索创新生态"} →</Link></div></div><section className="grid-2"><article className="card panel"><Link className="network" href="/ecosystems" aria-label={lang==="en"?"Open NEXORA Ecosystems":"打开 NEXORA 创新生态"}><i className="link l1"/><i className="link l2"/><i className="link l3"/><span className="node core">NEXORA</span><span className="node n1">UNIVERSITY</span><span className="node n2">STARTUP</span><span className="node n3">POLICY</span><span className="node n4">CAPITAL</span></Link></article><article className="card panel copilot"><div className="panel-title"><h3>{t.ai}</h3><span className="mini">PREVIEW</span></div><div className="ai-badge">NX·AI</div><p className="ai-copy">{t.aiSub}</p><div className="questions">{t.questions.map(q=><button className="question" key={q}>{q} →</button>)}</div><div className="ai-input"><input aria-label={t.placeholder} placeholder={t.placeholder}/><button>{t.send}</button></div></article></section>
  <div className="section-head"><div><h2>{t.hotspots}</h2><p>{t.hotSub}</p></div><span className="section-tag">REGIONAL INDEX</span></div><section className="hotspots">{hotspots.map(h=><article className="card hotspot" key={h.city}><div className="city-top"><div><div className="city">{lang==="zh"?h.zh:h.city}</div><div className="country">{h.country}</div></div><span className="city-score">{h.score}</span></div><div className="city-metrics"><span><b>{h.startups}</b>STARTUPS</span><span><b>{h.research}</b>RESEARCH</span></div></article>)}</section>
  <div className="section-head"><div><h2>{t.policy}</h2><p>{t.policySub}</p></div><div><span className="section-tag">PUBLIC SOURCES</span><Link className="section-link" href="/policy">{lang==="en"?"Explore Policy Intelligence":"探索政策智能"} →</Link></div></div><section className="card panel policy">{policies.map(p=><div className="policy-row" key={p.name}><span className="policy-type">{lang==="zh"?p.zhType:p.type}</span><span className="policy-name">{lang==="zh"?p.zh:p.name}<small>{p.org} · {p.year}</small></span><Link className="policy-source" href="/policy">↗ {t.source}</Link></div>)}</section>
  <footer className="demo-note"><span>{t.note}</span><span>{t.provenance}</span></footer></div></main>
 </div>
}
