"use client";
import { useState } from "react";
import Link from "@/components/safe-link";
import { useNexoraLanguage } from "@/hooks/use-nexora-language";
import { flagshipJourney, integrationRelease, productJourney } from "@/domain/product";
import { hotspots, kpis, opportunities, policies } from "@/data/demo/dashboard";
import { californiaAIFundingSnapshot } from "@/data/cases/california-ai/funding";

const copy = {
  en:{ home:"Home", overview:"Intelligence Overview", nav:[["Atlas","Global Industry Map"],["Radar","Emerging Opportunities"],["Companies","Startup Explorer"],["Ecosystems","Innovation Networks"],["Policy","Policy Intelligence"],["Simulator","Ecosystem Simulator"],["Nexora AI","Research Copilot"]], eyebrow:"GLOBAL FUTURE INDUSTRY INTELLIGENCE", h1a:"Map what’s emerging.",h1b:"Understand what drives it.",h1c:"See what comes next.", intro:"NEXORA is an intelligence platform for exploring emerging industries, technologies, innovation ecosystems, and public policy.", atlas:"Explore the Atlas",signals:"Explore Emerging Signals",live:"PROTOTYPE DATA ACTIVE", kpi:["Startups","Funding","Patents","Research Papers","Policies Tracked","Talent"], intelligence:"Global intelligence signals", demo:"Structured prototype dataset", opportunity:"Emerging Opportunities Radar",opSub:"Signals across science, capital, policy and talent",ranking:"Opportunity Ranking",network:"Innovation Ecosystem Network",netSub:"A connected view of institutions shaping the frontier",hotspots:"Global Innovation Hotspots",hotSub:"Regional capability and momentum indicators",policy:"Policy Intelligence",policySub:"Official public policy signal preview",ai:"Nexora AI Research Copilot", aiSub:"Ask cross-domain questions across the intelligence graph", questions:["Which industries are accelerating fastest?","Compare AI ecosystems across regions.","Which policies support biotechnology startups?"], placeholder:"Ask NEXORA a research question...", send:"Ask",source:"Official source",note:"All values shown are structured demo data for product prototyping — not production facts.",provenance:"Source facts · Derived metrics · AI interpretation are kept distinct."},
  zh:{ home:"首页", overview:"情报总览", nav:[["产业图谱","全球产业地图"],["趋势雷达","新兴机会信号"],["公司","创新企业探索"],["创新生态","创新网络"],["政策","政策情报"],["模拟器","生态系统模拟"],["Nexora AI","研究智能助手"]], eyebrow:"全球未来产业情报平台", h1a:"洞察正在崛起的产业。",h1b:"理解背后的驱动力。",h1c:"预见未来的方向。", intro:"NEXORA 是用于探索新兴产业、前沿技术、创新生态系统与公共政策的全球情报平台。", atlas:"探索产业图谱",signals:"查看新兴信号",live:"原型数据已启用", kpi:["创新企业","融资规模","专利","研究论文","追踪政策","专业人才"], intelligence:"全球情报信号", demo:"结构化原型数据集", opportunity:"新兴机会雷达",opSub:"跨科研、资本、政策与人才的综合信号",ranking:"机会潜力排名",network:"创新生态网络",netSub:"洞察塑造产业前沿的机构连接",hotspots:"全球创新热点",hotSub:"区域创新能力与发展动能指标",policy:"政策情报",policySub:"权威公共政策信号预览",ai:"Nexora AI 研究助手", aiSub:"基于未来产业知识图谱进行跨领域提问", questions:["哪些产业正在加速发展？","比较不同地区的 AI 创新生态。","哪些公共政策支持生物技术初创企业？"], placeholder:"向 NEXORA 提出研究问题…", send:"提问",source:"官方来源",note:"当前全部数值均为产品原型所用的结构化演示数据，并非生产环境事实。",provenance:"来源事实 · 衍生指标 · AI 解读在架构中严格区分。"}
} as const;

const professionalChineseHomeCopy = {
  home: "首页",
  overview: "情报总览",
  eyebrow: "全球未来产业情报平台",
  h1a: "洞察新兴产业",
  h1b: "解读发展动能",
  h1c: "研判未来趋势",
  intro: "NEXORA 是面向新兴产业、前沿技术、创新生态与公共政策的全球情报平台。",
  intelligence: "全球产业情报信号",
  opportunity: "新兴产业机会雷达",
  opSub: "融合科研、资本、政策与人才的综合信号",
  ranking: "机会潜力排序",
  network: "创新生态网络",
  netSub: "解析塑造产业前沿的机构连接",
  policy: "政策智能",
  policySub: "权威公共政策信号概览",
  ai: "NEXORA AI 研究助理",
  aiSub: "基于未来产业知识图谱开展跨领域研究",
} as const;

export function Dashboard(){
 const [lang,setLang]=useNexoraLanguage(); const [menu,setMenu]=useState(false); const [aiQuestion,setAiQuestion]=useState(""); const base=lang==="zh"?{...copy.zh,...professionalChineseHomeCopy}:copy.en; const t={...base,nav:productJourney.slice(1).map(item=>[item.name[lang],item.description[lang]])}; const journey=[...productJourney,flagshipJourney];
 return <div className={`app ${lang==="zh"?"lang-zh":"lang-en"}`}>
  <aside id="primary-navigation" className={`sidebar ${menu?"open":""}`}><button className="nav-close" onClick={()=>setMenu(false)} aria-label={lang==="en"?"Close navigation":"关闭导航"}>×</button><div className="brand"><span className="brand-mark">N</span>NEXORA</div><nav className="nav" aria-label="Primary navigation"><Link className="nav-link active" href="/" onClick={()=>setMenu(false)}><span className="nav-icon">01</span><span><span className="nav-title">{t.home}</span><span className="nav-sub">{t.overview}</span></span></Link>{journey.map((item,i)=><Link className="nav-link" href={item.href} key={item.id} onClick={()=>setMenu(false)}><span className="nav-icon">{String(i+2).padStart(2,"0")}</span><span><span className="nav-title">{item.name[lang]}</span><span className="nav-sub">{item.description[lang]}</span></span></Link>)}</nav><div className="side-foot">{integrationRelease.label}<br/>EVIDENCE-BASED INTELLIGENCE</div></aside>
  <main className="main"><header className="topbar"><div className="top-actions"><button className="menu-btn" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu} aria-controls="primary-navigation">☰</button><span className="crumb">NEXORA / {t.overview}</span></div><div className="top-actions"><span className="live">{t.live}</span><div className="lang" aria-label="Language"><button className={lang==="en"?"on":""} onClick={()=>setLang("en")}>EN</button><button className={lang==="zh"?"on":""} onClick={()=>setLang("zh")}>中文</button></div></div></header>
  <div className="content"><section className="hero"><div className="hero-copy"><div className="eyebrow">{t.eyebrow}</div><h1><span>{t.h1a}</span><br/><span>{t.h1b}</span><br/><span className="accent">{t.h1c}</span></h1><p className="hero-p">{lang==="en"?"NEXORA is an evidence-based future-industry intelligence platform connecting public data, geography, emerging signals, ecosystems, policy, organizations, research and scenario exploration.":"NEXORA 是一个基于证据的未来产业情报平台，连接公共数据、产业地理、新兴信号、创新生态、政策、组织、研究与情景探索。"}</p><div className="btns"><Link className="btn primary" href="/data-status">{lang==="en"?"Start with evidence status":"先查看证据状态"} →</Link><Link className="btn" href="/atlas">{t.atlas} →</Link><a className="btn" href="#journey">{lang==="en"?"See the product journey":"查看产品旅程"}</a></div><p className="hero-trust" role="note">{lang==="en"?"Observed public data, derived metrics, AI interpretation and scenario output are labeled separately.":"观测公共数据、衍生指标、AI 解读与情景输出均分开标注。"}</p></div><div className="hero-viz" aria-label="Stylized global innovation visualization"><div className="orbit o1"/><div className="orbit o2"/><div className="orbit o3"/><div className="globe"><i className="land a"/><i className="land b"/><i className="land c"/><i className="pulse p1"/><i className="pulse p2"/><i className="pulse p3"/></div><div className="viz-label">GLOBAL SIGNAL FIELD<br/>DEMO VISUAL<br/>NO LIVE GEOLOCATION</div></div></section>
  <section id="journey" className="journey" aria-labelledby="journey-title"><div className="section-head"><div><h2 id="journey-title">{lang==="en"?"One evidence trail, nine connected views":"一条证据链，九个互联视图"}</h2><p>{lang==="en"?"Public Data → Atlas → Radar → Ecosystems → Policy → Organizations → NEXORA AI → Simulator → California AI case":"公共数据 → 产业图谱 → 机会雷达 → 创新生态 → 政策 → 组织 → NEXORA AI → 情景模拟 → 加州 AI 案例"}</p></div><span className="section-tag">{integrationRelease.version.toUpperCase()}</span></div><div className="journey-grid">{journey.map((item,index)=><Link href={item.href} className="journey-step" key={item.id}><span>{String(index+1).padStart(2,"0")} / {item.action[lang]}</span><b>{item.name[lang]}</b><small>{item.description[lang]}</small></Link>)}</div></section>
  <section className="featured-case" aria-labelledby="featured-case-title"><div><span>FEATURED RESEARCH CASE / 旗舰研究案例</span><b>EMPIRICAL FLAGSHIP CASE v2</b></div><h2 id="featured-case-title">{lang==="en"?"California AI Innovation Ecosystem":"加州人工智能创新生态系统"}</h2><p>{lang==="en"?"A multi-layer case connecting OpenAlex research and networks, BLS AI-adjacent talent, NSF awards, official policy, explicit gaps and a partially calibrated empirical scenario baseline.":"一个连接 OpenAlex 科研与网络、BLS AI 邻近人才、NSF 奖项、官方政策、明确证据缺口与部分校准实证情景基线的多层案例。"}</p><dl><div><dt>2015—2025</dt><dd>{lang==="en"?"Complete research years · 2026 partial":"完整科研年度 · 2026 部分年度"}</dd></div><div><dt>31</dt><dd>{lang==="en"?"Verified organizations":"已核验组织"}</dd></div><div><dt>{californiaAIFundingSnapshot.totals.awardCount}</dt><dd>{lang==="en"?"NSF award records":"NSF 奖项记录"}</dd></div><div><dt>40</dt><dd>{lang==="en"?"Promoted relationships":"纳入关系"}</dd></div></dl><Link className="btn primary" href="/cases/california-ai">{lang==="en"?"Open flagship case":"打开旗舰案例"} →</Link></section>
  <div className="section-head"><div><h2>{t.intelligence}</h2><p>{t.demo}</p></div><span className="section-tag">SIGNAL INDEX / 2026</span></div><section className="kpis">{kpis.map((k,i)=><article className="card kpi" key={k.key}><div className="kpi-label">{t.kpi[i]}</div><div className="kpi-value">{k.value}</div><div className="delta">↗ {k.delta}</div></article>)}</section>
  <div className="section-head" id="radar"><div><h2>{t.opportunity}</h2><p>{t.opSub}</p></div><span className="section-tag">DEMO COMPOSITE MODEL</span></div><section className="grid-2"><article className="card panel"><div className="panel-title"><h3>{t.opportunity}</h3><span className="mini">MOMENTUM × MATURITY</span></div><div className="radar-wrap"><div className="radar"><i className="dot d1"/><i className="dot d2"/><i className="dot d3"/><i className="dot d4"/><i className="dot d5"/><span className="radar-label r1">AI AGENTS</span><span className="radar-label r2">QUANTUM</span><span className="radar-label r3">SYNBIO</span><span className="radar-label r4">BATTERIES</span><span className="radar-label r5">ROBOTICS</span></div></div></article><article className="card panel"><div className="panel-title"><h3>{t.ranking}</h3><span className="mini">NEXORA SCORE</span></div><div className="ranking">{opportunities.map((o,i)=><div className="rank-row" key={o.name}><span className="rank-num">0{i+1}</span><span className="rank-name">{lang==="zh"?o.zh:o.name}<small>{o.sector}</small></span><span><span className="score">{o.score}</span><span className="bar"><i style={{width:`${o.score}%`}}/></span></span><span className="trend">{o.trend}</span></div>)}</div></article></section>
  <div className="section-head"><div><h2>{t.network}</h2><p>{t.netSub}</p></div><div><span className="section-tag">KNOWLEDGE GRAPH PREVIEW</span><Link className="section-link" href="/ecosystems">{lang==="en"?"Explore ecosystems":"探索创新生态"} →</Link></div></div><section className="grid-2"><article className="card panel"><Link className="network" href="/ecosystems" aria-label={lang==="en"?"Open NEXORA Ecosystems":"打开 NEXORA 创新生态"}><i className="link l1"/><i className="link l2"/><i className="link l3"/><span className="node core">NEXORA</span><span className="node n1">UNIVERSITY</span><span className="node n2">STARTUP</span><span className="node n3">POLICY</span><span className="node n4">CAPITAL</span></Link></article><article className="card panel copilot"><div className="panel-title"><h3>{t.ai}</h3><span className="mini">EVIDENCE-FIRST</span></div><div className="ai-badge">NX·AI</div><p className="ai-copy">{t.aiSub}</p><div className="questions">{t.questions.map(q=><Link className="question" href={`/ai?q=${encodeURIComponent(q)}`} key={q}>{q} →</Link>)}</div><form className="ai-input" action="/ai"><input name="q" value={aiQuestion} onChange={e=>setAiQuestion(e.target.value)} aria-label={t.placeholder} placeholder={t.placeholder}/><button>{t.send}</button></form></article></section>
  <div className="section-head"><div><h2>{t.hotspots}</h2><p>{t.hotSub}</p></div><span className="section-tag">REGIONAL INDEX</span></div><section className="hotspots">{hotspots.map(h=><article className="card hotspot" key={h.city}><div className="city-top"><div><div className="city">{lang==="zh"?h.zh:h.city}</div><div className="country">{h.country}</div></div><span className="city-score">{h.score}</span></div><div className="city-metrics"><span><b>{h.startups}</b>STARTUPS</span><span><b>{h.research}</b>RESEARCH</span></div></article>)}</section>
  <div className="section-head"><div><h2>{t.policy}</h2><p>{t.policySub}</p></div><div><span className="section-tag">PUBLIC SOURCES</span><Link className="section-link" href="/policy">{lang==="en"?"Explore Policy Intelligence":"探索政策智能"} →</Link></div></div><section className="card panel policy">{policies.map(p=><div className="policy-row" key={p.name}><span className="policy-type">{lang==="zh"?p.zhType:p.type}</span><span className="policy-name">{lang==="zh"?p.zh:p.name}<small>{p.org} · {p.year}</small></span><Link className="policy-source" href="/policy">↗ {t.source}</Link></div>)}</section>
  <div className="section-head"><div><h2>{lang==="en"?"NEXORA Simulator":"NEXORA 情景模拟器"}</h2><p>{lang==="en"?"Explore how innovation ecosystems may evolve under explicit assumptions.":"探索创新生态在明确假设下可能如何演化。"}</p></div><div><span className="section-tag">SYSTEM DYNAMICS · MODEL v1.0</span><Link className="section-link" href="/simulator">{lang==="en"?"Open Simulator":"打开情景模拟器"} →</Link></div></div><section className="card panel"><div className="panel-title"><h3>{lang==="en"?"Scenario research lab":"情景研究实验室"}</h3><span className="mini">SIMULATION ≠ PREDICTION</span></div><p className="ai-copy">{lang==="en"?"Compare baseline, policy, research, commercialization, talent and constraint scenarios with transparent equations, sensitivity and uncertainty.":"使用透明方程、敏感性与不确定性，对比基准、政策、科研、商业化、人才与约束情景。"}</p><div className="btns"><Link className="btn primary" href="/simulator">{lang==="en"?"Run a scenario":"运行情景"} →</Link><Link className="btn" href="/docs/SYSTEM_DYNAMICS_MODEL.md">{lang==="en"?"Review model":"查看模型"} →</Link></div></section>
  <footer className="demo-note"><span>{t.note}</span><span>{t.provenance}</span></footer></div></main>
 </div>
}
