"use client";
import Link from "@/components/safe-link";
import { useNexoraLanguage } from "@/hooks/use-nexora-language";
import { canonicalSources,dataGovCatalogRecords,openAlexResearchObservations,productionSnapshotDate,providerHealth,verifiedOrganizations,verifiedPolicies,verifiedRelationships,worldBankObservations } from "@/data/production/pilot";
import { runPilotIngestion } from "@/services/public-data/pipeline";
import { calibrationCoverage } from "@/simulation/calibration/calibration";
import { innovationEcosystemModelV1 } from "@/simulation/model/model-v1";
import styles from "./data-status.module.css";
import { ResearchModuleShell } from "./editorial/ResearchModuleShell";
import { BoundaryNote, ChartExplanation } from "./editorial/ResearchFindings";
import pilotStyles from "./data-status-pilot.module.css";

const T={
 en:{back:"Intelligence overview",title:"NEXORA Data Status",tagline:"Know what is observed, derived, demo, stale or unavailable.",support:"Provider health, freshness, coverage, quality, licensing and provenance for the production pilot.",mode:"HYBRID MODE",provider:"Provider health",quality:"Promotion quality gate",sources:"Source & license registry",pilot:"Verified pilot records",coverage:"Coverage currently includes",limits:"Coverage limitations",demo:"Demo data remains available and never silently replaces production data.",records:"records",fresh:"Freshness",license:"License",last:"Last successful refresh",none:"No successful live refresh",ready:"PROMOTION READY",blocked:"PROMOTION BLOCKED",official:"Official source",orgs:"Official organization identities",policies:"Official policy and program records",footer:"PUBLIC DATA · TRACEABLE CLAIMS · NO PERSONAL PROFILES"},
 zh:{back:"返回情报总览",title:"NEXORA 数据状态",tagline:"明确区分公开观测、衍生、演示、过期与不可用数据。",support:"展示生产试点的数据源健康度、新鲜度、覆盖、质量、许可与来源链。",mode:"混合模式",provider:"数据源健康",quality:"晋级质量门禁",sources:"来源与许可注册表",pilot:"已核验试点记录",coverage:"当前覆盖范围",limits:"覆盖局限",demo:"演示数据继续可用，且绝不会静默替代生产数据。",records:"条记录",fresh:"新鲜度",license:"许可",last:"最近成功刷新",none:"尚无成功实时刷新",ready:"允许晋级",blocked:"禁止晋级",official:"官方来源",orgs:"官方组织身份",policies:"官方政策与项目记录",footer:"公共数据 · 可追溯声明 · 无个人画像"}
};
const labels={HEALTHY:{en:"Healthy",zh:"健康"},DEGRADED:{en:"Degraded",zh:"降级"},STALE:{en:"Stale",zh:"可能过期"},UNAVAILABLE:{en:"Unavailable",zh:"不可用"},NOT_CONFIGURED:{en:"Not configured",zh:"未配置"}} as const;

export function DataStatus(){
 const [lang,setLang]=useNexoraLanguage(),t=lang==="zh"?{...T.zh,tagline:"清晰区分公开观测、衍生、演示、过期与不可用数据"}:T.en,runs=runPilotIngestion(true);
 const totals={research:openAlexResearchObservations.length,macro:worldBankObservations.length,organizations:verifiedOrganizations.length,policies:verifiedPolicies.length,catalog:dataGovCatalogRecords.length,relationships:verifiedRelationships.length};
 return <main className={styles.page}>
  <ResearchModuleShell image="/data-status-og.png" eyebrow="NEXORA / FUTURE INDUSTRY INTELLIGENCE" title={lang==="en"?"NEXORA DATA STATUS":"NEXORA 数据状态"} subtitle={lang==="en"?"Public data. Provenance. Quality. Freshness.":"公共数据、来源与时效"} description={lang==="en"?"Inspect provider coverage, provenance, freshness, limitations and system health.":"审视数据覆盖、来源、时效、局限与系统状态。"} enterLabel={lang==="en"?"Enter data workspace":"进入数据工作台"} insightLabel={lang==="en"?"Methods & evidence":"方法与证据"} lang={lang}/>
  <div id="workspace"/>
  <DataTrustExperience lang={lang}/>
  <header><div><Link prefetch={false} href="/">N <b>NEXORA</b></Link><Link prefetch={false} href="/">← {t.back}</Link></div><div><span><i/>PUBLIC DATA PIPELINE / 07</span><nav aria-label="Language"><button className={lang==="en"?styles.on:""} onClick={()=>setLang("en")}>EN</button><button className={lang==="zh"?styles.on:""} onClick={()=>setLang("zh")}>中文</button></nav></div></header>
  <section className={styles.hero}><p>PROVENANCE · QUALITY · FRESHNESS · RELIABILITY</p><h1>{t.title}</h1><h2>{t.tagline}</h2><h3>{t.support}</h3><div className={styles.mode}><span>{t.mode}</span><b>{productionSnapshotDate}</b><small>PRODUCTION → CACHE → LAST KNOWN GOOD → DEMO → UNAVAILABLE</small></div></section>
  <section className={styles.coverage}><h2>{t.coverage}</h2><div>{Object.entries(totals).map(([k,v])=><span key={k}><b>{v}</b>{k.toUpperCase()}</span>)}</div><p>{t.demo}</p><small>{lang==="en"?"Trust vocabulary: Public Data · Normalized · Derived · Composite · Demo · Simulated · AI Interpretation · Unavailable · Degraded · Stale · Not Configured":"信任状态：公共数据 · 规范化 · 衍生 · 综合指标 · 演示 · 模拟 · AI 解读 · 不可用 · 降级 · 过期 · 未配置"}</small></section>
  <section className={`${styles.coverage} ${styles.researchReady}`}><h2>{lang==="en"?"Research readiness":"研究就绪度"}</h2><div><span><b>13</b>{lang==="en"?"PROVIDER SPECS":"数据源规格"}</span><span><b>4</b>{lang==="en"?"EVIDENCE LAYERS":"证据层级"}</span><span><b>1</b>{lang==="en"?"PUBLIC MODEL":"公开模型"}</span><span><b>4</b>{lang==="en"?"UNCERTAINTY CLASSES":"不确定性类型"}</span></div><p>{lang==="en"?"Provider availability is not the same as research readiness. A dataset must also pass scope, license/terms, lineage, schema, geography, time, missingness and interpretation checks.":"数据源可访问并不等于达到研究要求。数据还必须通过范围、许可条款、来源链、模式、地理、时间、缺失值与解释边界检查"}</p><nav><a href="/research/PUBLIC_DATA_PROVIDER_REGISTRY.md" download>{lang==="en"?"Provider registry":"数据源注册表"} ↓</a><a href="/research/INDICATOR_DICTIONARY.md" download>{lang==="en"?"Indicator dictionary":"指标字典"} ↓</a><a href="/research/REPRODUCIBILITY_PROTOCOL.md" download>{lang==="en"?"Reproducibility protocol":"可复现协议"} ↓</a></nav></section>
  <section className={styles.coverage}><h2>{lang==="en"?"Simulation Model":"模拟模型"}</h2><div><span><b>{innovationEcosystemModelV1.version}</b>MODEL VERSION</span><span><b>{innovationEcosystemModelV1.status}</b>MODEL STATUS</span><span><b>{calibrationCoverage.observed}%</b>OBSERVED CALIBRATION</span><span><b>{calibrationCoverage.derived}%</b>DERIVED CALIBRATION</span><span><b>{calibrationCoverage.assumption}%</b>ASSUMPTION SHARE</span></div><p>{lang==="en"?"Innovation Ecosystem Evolution Model v1 is a partially calibrated conceptual research model. Simulation is not prediction.":"创新生态演化模型 v1 是部分校准的概念研究模型。模拟不是预测。"} <Link href="/simulator">{lang==="en"?"Open Simulator":"打开模拟器"} →</Link></p></section>
  <section className={styles.coverage}><h2>{lang==="en"?"AI Provider Availability":"AI 服务可用性"}</h2><div><span><b>NOT CONFIGURED</b>MODEL PROVIDER</span><span><b>AVAILABLE</b>DETERMINISTIC RETRIEVAL</span><span><b>SERVER ONLY</b>FUTURE SECRETS</span></div><p>{lang==="en"?"No live model provider is configured. NEXORA AI uses an evidence-first deterministic fallback and never exposes provider secrets in the client bundle.":"当前未配置实时模型服务。NEXORA AI 使用证据优先的确定性回退，并且不会在客户端构建中暴露服务密钥。"} <Link href="/ai">{lang==="en"?"Open NEXORA AI":"打开 NEXORA AI"} →</Link></p></section>
  <section className={styles.section}><Title n="01" title={t.provider} sub="Semantic status text—not color alone."/><div className={styles.providers}>{providerHealth.map(p=><article key={p.provider} data-state={p.status}><div><span>{p.provider}</span><b>{labels[p.status][lang]}</b></div><strong>{p.recordCount} {t.records}</strong><p>{p.coverage[lang]}</p><dl><Fact k={t.last} v={p.lastSuccessAt?.slice(0,10)??t.none}/><Fact k={t.fresh} v={p.freshness}/><Fact k={t.license} v={p.licenseStatus.replaceAll("_"," ")}/></dl>{p.errorSummary&&<small>{p.errorSummary}</small>}</article>)}</div></section>
  <section className={styles.section}><Title n="02" title={t.quality} sub="Validate → quarantine → quality check → atomic promotion."/><div className={styles.quality}>{runs.map(({run,quality,checksum})=><article key={run.id}><span>{run.provider}</span><h3>{quality.promotionAllowed?t.ready:t.blocked}</h3><b>{quality.recordCount} / {quality.rejectedRecords}</b><p>ACCEPTED / REJECTED · CHECKSUM {checksum}</p><div>{[["Completeness",quality.completeness],["Validity",quality.validity],["Provenance",quality.provenanceCoverage],["Uniqueness",quality.uniqueness]].map(([k,v])=><span key={String(k)}>{k}<b>{v}%</b></span>)}</div></article>)}</div></section>
  <section className={styles.section}><Title n="03" title={t.sources} sub="Catalog availability never implies unrestricted reuse."/><div className={styles.sources}>{canonicalSources.map(s=><article key={s.id}><span>TIER {s.tier} · {s.provider}</span><h3>{s.name}</h3><p>{s.attributionText}</p><dl><Fact k={t.license} v={s.license.status.replaceAll("_"," ")}/><Fact k="Retrieved" v={s.retrievedAt}/></dl><a href={s.url} rel="noreferrer">{t.official} →</a></article>)}</div></section>
  <section className={styles.section}><Title n="04" title={t.pilot} sub="Identity and policy facts only; no personal profiles."/><div className={pilotStyles.pilot}><details open><summary>{t.orgs} · {verifiedOrganizations.length}</summary><div>{verifiedOrganizations.map(o=><a key={o.id} href={o.officialUrl} rel="noreferrer"><span>{o.status} · {o.countryCode}</span><b>{o.name[lang]}</b><small>{o.officialDomain}</small></a>)}</div></details><details open><summary>{t.policies} · {verifiedPolicies.length}</summary><div>{verifiedPolicies.map(p=><a key={p.id} href={p.officialUrl} rel="noreferrer"><span>{p.status} · {p.currentStatus}</span><b>{p.title[lang]}</b><small>{p.agency} · {p.lastVerified}</small></a>)}</div></details></div></section>
  <section className={styles.limits}><h2>{t.limits}</h2><p>{lang==="en"?"Not globally complete. OpenAlex topic mappings are curated proxies; World Bank values are country-level and may lag; Data.gov is catalog metadata; USPTO production access is not configured; official identities do not verify every activity; most ecosystem edges and product KPIs remain Demo.":"并非全球完整数据。OpenAlex 主题映射属于策划代理；World Bank 数值位于国家层面且可能滞后；Data.gov 仅提供目录元数据；USPTO 生产访问尚未配置；官方身份并不能核验所有活动；多数生态关系与产品 KPI 仍为演示状态"}</p><div><Link prefetch={false} href="/methodology">Research Methodology</Link><a href="/research/PUBLIC_DATA_PROVIDER_REGISTRY.md" download>Provider Registry ↓</a><a href="/research/REPRODUCIBILITY_PROTOCOL.md" download>Reproducibility Protocol ↓</a></div></section>
  <footer><span>NEXORA DATA STATUS / SNAPSHOT {productionSnapshotDate}</span><span>{t.footer}</span></footer>
 </main>;
}
function DataTrustExperience({lang}:{lang:"en"|"zh"}){return <section className={styles.trustExperience} aria-labelledby="provenance-pipeline">
  <div className={styles.trustHead}><span>01 / PROVENANCE PIPELINE</span><h2 id="provenance-pipeline">{lang==="en"?"From public source to bounded analysis":"从公共来源到有边界的分析"}</h2><p>{lang==="en"?"Every record retains its source, transformation state and quality context before it can support analysis.":"每条记录只有在保留来源、转换状态与质量语境后，才可进入分析"}</p></div>
  <ol className={styles.pipeline}>{[["PUBLIC SOURCE","公共来源","OBSERVED"],["INGESTION","数据接入","OBSERVED"],["NORMALIZATION","规范化","DERIVED"],["QUALITY","质量检查","DERIVED"],["DERIVATION","指标衍生","DERIVED"],["ANALYSIS","分析解读","INTERPRETATION"]].map(([en,zh,state],index)=><li key={en}><span>{String(index+1).padStart(2,"0")}</span><b>{lang==="en"?en:zh}</b><small>{state}</small></li>)}</ol>
  <ChartExplanation shows={lang==="en"?"The pipeline distinguishes source records, transformations and interpretation.":"流程明确区分来源记录、转换过程与分析解读"} matters={lang==="en"?"Users can trace which layer supports a claim and where uncertainty enters.":"用户可以追踪结论由哪一层证据支持，以及不确定性从何进入"} boundary={lang==="en"?"Pipeline completion does not make incomplete coverage representative or causal.":"流程完整并不意味着有限覆盖具有代表性或因果意义"}/>
  <div className={styles.taxonomy}>{[["OBSERVED","Direct public evidence","公共来源的直接证据"],["DERIVED","Declared transformation","按声明规则生成"],["PROXY","Imperfect substitute","有限替代指标"],["DEMO","Interface demonstration","界面演示数据"],["SIMULATED","Model-generated result","模型生成结果"],["AI INTERPRETATION","Bounded synthesis","有边界的综合解读"],["UNAVAILABLE","No support configured","尚无可用支持"]].map(([state,en,zh])=><article key={state} data-state={state}><span>{state}</span><p>{lang==="en"?en:zh}</p></article>)}</div>
  <div className={styles.readinessMatrix}><h3>{lang==="en"?"Research readiness by construct":"按研究构念查看就绪度"}</h3><div>{[["Research","科研","READY"],["Talent","人才","PARTIAL"],["Funding","资助","PARTIAL"],["Policy","政策","PARTIAL"],["Organizations","组织","PARTIAL"],["Networks","网络","PROXY"],["Patents","专利","UNAVAILABLE"],["Entrepreneurship","创业","PROXY"],["Capital","资本","NOT_CONFIGURED"]].map(([en,zh,state])=><span key={en} data-state={state}><b>{lang==="en"?en:zh}</b><small>{state}</small></span>)}</div></div>
  <BoundaryNote title={lang==="en"?"Inference remains narrower than interface coverage":"可推断范围小于界面覆盖范围"}><p>{lang==="en"?"Users may compare documented public observations within their declared scope. They should not treat demo, proxy or unavailable constructs as measured facts, causal effects or forecasts.":"用户可以在声明范围内比较已记录的公共观测，但不应将演示、代理或不可用构念视为测量事实、因果效应或预测"}</p></BoundaryNote>
 </section>}
function Title({n,title,sub}:{n:string;title:string;sub:string}){return <div className={styles.title}><span>{n}</span><div><h2>{title}</h2><p>{sub}</p></div></div>}
function Fact({k,v}:{k:string;v:string}){return <div><dt>{k}</dt><dd>{v}</dd></div>}
