"use client";
import Link from "@/components/safe-link";
import { useNexoraLanguage } from "@/hooks/use-nexora-language";
import { canonicalSources,dataGovCatalogRecords,openAlexResearchObservations,productionSnapshotDate,providerHealth,verifiedOrganizations,verifiedPolicies,verifiedRelationships,worldBankObservations } from "@/data/production/pilot";
import { runPilotIngestion } from "@/services/public-data/pipeline";
import { calibrationCoverage } from "@/simulation/calibration/calibration";
import { innovationEcosystemModelV1 } from "@/simulation/model/model-v1";
import { CaliforniaAIFlagshipSnapshot } from "@/data/cases/california-ai/snapshot";
import { californiaAICoverage } from "@/data/cases/california-ai/coverage";
import styles from "./data-status.module.css";
import pilotStyles from "./data-status-pilot.module.css";

const T={
 en:{back:"Intelligence overview",title:"NEXORA Data Status",tagline:"Know what is observed, derived, demo, stale or unavailable.",support:"Provider health, freshness, coverage, quality, licensing and provenance for the production pilot.",mode:"HYBRID MODE",provider:"Provider health",quality:"Promotion quality gate",sources:"Source & license registry",pilot:"Verified pilot records",coverage:"Coverage currently includes",limits:"Coverage limitations",demo:"Demo data remains available and never silently replaces production data.",records:"records",fresh:"Freshness",license:"License",last:"Last successful refresh",none:"No successful live refresh",ready:"PROMOTION READY",blocked:"PROMOTION BLOCKED",official:"Official source",orgs:"Official organization identities",policies:"Official policy and program records",footer:"PUBLIC DATA · TRACEABLE CLAIMS · NO PERSONAL PROFILES"},
 zh:{back:"返回情报总览",title:"NEXORA 数据状态",tagline:"明确区分公开观测、衍生、演示、过期与不可用数据。",support:"展示生产试点的数据源健康度、新鲜度、覆盖、质量、许可与来源链。",mode:"混合模式",provider:"数据源健康",quality:"晋级质量门禁",sources:"来源与许可注册表",pilot:"已核验试点记录",coverage:"当前覆盖范围",limits:"覆盖局限",demo:"演示数据继续可用，且绝不会静默替代生产数据。",records:"条记录",fresh:"新鲜度",license:"许可",last:"最近成功刷新",none:"尚无成功实时刷新",ready:"允许晋级",blocked:"禁止晋级",official:"官方来源",orgs:"官方组织身份",policies:"官方政策与项目记录",footer:"公共数据 · 可追溯声明 · 无个人画像"}
};
const labels={HEALTHY:{en:"Healthy",zh:"健康"},DEGRADED:{en:"Degraded",zh:"降级"},STALE:{en:"Stale",zh:"可能过期"},UNAVAILABLE:{en:"Unavailable",zh:"不可用"},NOT_CONFIGURED:{en:"Not configured",zh:"未配置"}} as const;

export function DataStatus(){
 const [lang,setLang]=useNexoraLanguage(),t=T[lang],runs=runPilotIngestion(true);
 const totals={research:openAlexResearchObservations.length,macro:worldBankObservations.length,organizations:verifiedOrganizations.length,policies:verifiedPolicies.length,catalog:dataGovCatalogRecords.length,relationships:verifiedRelationships.length};
 return <main className={styles.page}>
  <header><div><Link prefetch={false} href="/">N <b>NEXORA</b></Link><Link prefetch={false} href="/">← {t.back}</Link></div><div><span><i/>PUBLIC DATA PIPELINE / 07</span><nav aria-label="Language"><button className={lang==="en"?styles.on:""} onClick={()=>setLang("en")}>EN</button><button className={lang==="zh"?styles.on:""} onClick={()=>setLang("zh")}>中文</button></nav></div></header>
  <section className={styles.hero}><p>PROVENANCE · QUALITY · FRESHNESS · RELIABILITY</p><h1>{t.title}</h1><h2>{t.tagline}</h2><h3>{t.support}</h3><div className={styles.mode}><span>{t.mode}</span><b>{productionSnapshotDate}</b><small>PRODUCTION → CACHE → LAST KNOWN GOOD → DEMO → UNAVAILABLE</small></div></section>
  <section className={styles.coverage}><h2>{t.coverage}</h2><div>{Object.entries(totals).map(([k,v])=><span key={k}><b>{v}</b>{k.toUpperCase()}</span>)}</div><p>{t.demo}</p><small>{lang==="en"?"Trust vocabulary: Public Data · Normalized · Derived · Composite · Demo · Simulated · AI Interpretation · Unavailable · Degraded · Stale · Not Configured":"信任状态：公共数据 · 规范化 · 衍生 · 综合指标 · 演示 · 模拟 · AI 解读 · 不可用 · 降级 · 过期 · 未配置"}</small></section>
  <section className={styles.coverage}><h2>{lang==="en"?"Simulation Model":"模拟模型"}</h2><div><span><b>{innovationEcosystemModelV1.version}</b>MODEL VERSION</span><span><b>{innovationEcosystemModelV1.status}</b>MODEL STATUS</span><span><b>{calibrationCoverage.observed}%</b>OBSERVED CALIBRATION</span><span><b>{calibrationCoverage.derived}%</b>DERIVED CALIBRATION</span><span><b>{calibrationCoverage.assumption}%</b>ASSUMPTION SHARE</span></div><p>{lang==="en"?"Innovation Ecosystem Evolution Model v1 is a partially calibrated conceptual research model. Simulation is not prediction.":"创新生态演化模型 v1 是部分校准的概念研究模型。模拟不是预测。"} <Link href="/simulator">{lang==="en"?"Open Simulator":"打开模拟器"} →</Link></p></section>
  <section className={styles.coverage}><h2>{lang==="en"?"AI Provider Availability":"AI 服务可用性"}</h2><div><span><b>NOT CONFIGURED</b>MODEL PROVIDER</span><span><b>AVAILABLE</b>DETERMINISTIC RETRIEVAL</span><span><b>SERVER ONLY</b>FUTURE SECRETS</span></div><p>{lang==="en"?"No live model provider is configured. NEXORA AI uses an evidence-first deterministic fallback and never exposes provider secrets in the client bundle.":"当前未配置实时模型服务。NEXORA AI 使用证据优先的确定性回退，并且不会在客户端构建中暴露服务密钥。"} <Link href="/ai">{lang==="en"?"Open NEXORA AI":"打开 NEXORA AI"} →</Link></p></section>
  <section className={styles.coverage}><h2>{lang==="en"?"California AI Flagship Case":"加州 AI 旗舰案例"}</h2><div><span><b>{CaliforniaAIFlagshipSnapshot.snapshotDate}</b>SNAPSHOT</span><span><b>OBSERVED</b>OPENALEX · 2015–2025</span><span><b>PARTIAL</b>BLS OEWS · MAY 2025</span><span><b>{CaliforniaAIFlagshipSnapshot.fundingAwardCount}</b>NSF · 2025 AWARDS</span><span><b>{CaliforniaAIFlagshipSnapshot.organizationCount}</b>ORGANIZATIONS</span><span><b>{CaliforniaAIFlagshipSnapshot.relationshipCount}</b>RELATIONSHIPS</span><span><b>NOT CONFIGURED</b>USPTO PATENTS</span></div><p>{lang==="en"?"Versioned public-facing empirical snapshot. OpenAlex research is strong within a reproducible selected-institution frame; BLS workforce and NSF funding are context-only slices; organizations, policy and relationships are partial; patents and capital remain unavailable.":"面向公众的版本化实证快照。OpenAlex 科研在可复现的选定机构框架内较强；BLS 劳动力与 NSF 资金仅为背景切片；组织、政策与关系为部分覆盖；专利与资本仍不可用。"} <Link href="/cases/california-ai">{lang==="en"?"Open flagship evidence view":"打开旗舰证据视图"} →</Link></p><small>{californiaAICoverage.map(x=>`${x.label[lang]}: ${x.level}`).join(" · ")}</small></section>
  <section className={styles.section}><Title n="01" title={t.provider} sub="Semantic status text—not color alone."/><div className={styles.providers}>{providerHealth.map(p=><article key={p.provider} data-state={p.status}><div><span>{p.provider}</span><b>{labels[p.status][lang]}</b></div><strong>{p.recordCount} {t.records}</strong><p>{p.coverage[lang]}</p><dl><Fact k={t.last} v={p.lastSuccessAt?.slice(0,10)??t.none}/><Fact k={t.fresh} v={p.freshness}/><Fact k={t.license} v={p.licenseStatus.replaceAll("_"," ")}/></dl>{p.errorSummary&&<small>{p.errorSummary}</small>}</article>)}</div></section>
  <section className={styles.section}><Title n="02" title={t.quality} sub="Validate → quarantine → quality check → atomic promotion."/><div className={styles.quality}>{runs.map(({run,quality,checksum})=><article key={run.id}><span>{run.provider}</span><h3>{quality.promotionAllowed?t.ready:t.blocked}</h3><b>{quality.recordCount} / {quality.rejectedRecords}</b><p>ACCEPTED / REJECTED · CHECKSUM {checksum}</p><div>{[["Completeness",quality.completeness],["Validity",quality.validity],["Provenance",quality.provenanceCoverage],["Uniqueness",quality.uniqueness]].map(([k,v])=><span key={String(k)}>{k}<b>{v}%</b></span>)}</div></article>)}</div></section>
  <section className={styles.section}><Title n="03" title={t.sources} sub="Catalog availability never implies unrestricted reuse."/><div className={styles.sources}>{canonicalSources.map(s=><article key={s.id}><span>TIER {s.tier} · {s.provider}</span><h3>{s.name}</h3><p>{s.attributionText}</p><dl><Fact k={t.license} v={s.license.status.replaceAll("_"," ")}/><Fact k="Retrieved" v={s.retrievedAt}/></dl><a href={s.url} rel="noreferrer">{t.official} →</a></article>)}</div></section>
  <section className={styles.section}><Title n="04" title={t.pilot} sub="Identity and policy facts only; no personal profiles."/><div className={pilotStyles.pilot}><details open><summary>{t.orgs} · {verifiedOrganizations.length}</summary><div>{verifiedOrganizations.map(o=><a key={o.id} href={o.officialUrl} rel="noreferrer"><span>{o.status} · {o.countryCode}</span><b>{o.name[lang]}</b><small>{o.officialDomain}</small></a>)}</div></details><details open><summary>{t.policies} · {verifiedPolicies.length}</summary><div>{verifiedPolicies.map(p=><a key={p.id} href={p.officialUrl} rel="noreferrer"><span>{p.status} · {p.currentStatus}</span><b>{p.title[lang]}</b><small>{p.agency} · {p.lastVerified}</small></a>)}</div></details></div></section>
  <section className={styles.limits}><h2>{t.limits}</h2><p>{lang==="en"?"Not globally complete. OpenAlex topic mappings are curated proxies; World Bank values are country-level and may lag; Data.gov is catalog metadata; USPTO production access requires a key; official identities do not verify every activity; most ecosystem edges and product KPIs remain Demo.":"并非全球完整数据。OpenAlex 主题映射是策划代理；World Bank 数值属于国家层面且可能滞后；Data.gov 仅为目录元数据；USPTO 生产访问需要密钥；官方身份不代表所有活动均已验证；大部分生态关系与产品 KPI 仍为演示。"}</p><div><Link prefetch={false} href="/docs/PUBLIC_DATA_ARCHITECTURE.md">Architecture</Link><Link prefetch={false} href="/docs/DATA_PROVENANCE.md">Provenance</Link><Link prefetch={false} href="/docs/DATA_QUALITY.md">Quality</Link><Link prefetch={false} href="/docs/DATA_LICENSE_AUDIT.md">License Audit</Link></div></section>
  <footer><span>NEXORA DATA STATUS / SNAPSHOT {productionSnapshotDate}</span><span>{t.footer}</span></footer>
 </main>;
}
function Title({n,title,sub}:{n:string;title:string;sub:string}){return <div className={styles.title}><span>{n}</span><div><h2>{title}</h2><p>{sub}</p></div></div>}
function Fact({k,v}:{k:string;v:string}){return <div><dt>{k}</dt><dd>{v}</dd></div>}
