"use client";
import { FormEvent,useCallback,useEffect,useRef,useState } from "react";
import Link from "@/components/safe-link";
import type { AIAnswer,AILanguage,AIQueryContext,EvidenceItem,EvidencePack } from "@/domain/ai";
import styles from "./nexora-ai-workspace.module.css";
import { ResearchModuleShell } from "./editorial/ResearchModuleShell";
import { useNexoraLanguage } from "@/hooks/use-nexora-language";

type Result={answer:AIAnswer;evidencePack:EvidencePack;provider:{id:string;modelIdentifier:string|null;liveModelConfigured:boolean;generationMode:string}};
type Panel="evidence"|"sources"|"gaps";
const starter=[
 {en:"Which technologies have the strongest verified research momentum?",zh:"哪些技术拥有最强的已核验科研动能？"},
 {en:"What evidence does NEXORA have for quantum technology growth?",zh:"NEXORA 有哪些支持量子技术增长的证据？"},
 {en:"Which public policies support semiconductor innovation?",zh:"哪些公共政策支持半导体创新？"},
 {en:"Generate a research brief on advanced batteries.",zh:"生成一份先进电池研究简报。"},
 {en:"Which organizations connect research and commercialization?",zh:"哪些组织连接科研与商业化？"},
 {en:"What does NEXORA not yet know?",zh:"NEXORA 目前还不知道什么？"}
];
const caseStarter=[
 {en:"Generate an evidence-based research brief on the California AI ecosystem.",zh:"生成一份加州人工智能生态系统循证研究简报。"},
 {en:"What does the verified California AI research series show?",zh:"已核验的加州 AI 科研序列显示了什么？"},
 {en:"Which organizations appear in the verified California AI network?",zh:"加州 AI 已核验网络包含哪些组织？"},
 {en:"How do California AI policy mechanisms differ?",zh:"加州 AI 政策机制有何差异？"},
 {en:"What evidence gaps limit the California AI case?",zh:"哪些证据缺口限制了加州 AI 案例？"},
 {en:"Which California AI simulator inputs are observed or derived?",zh:"加州 AI 模拟器的哪些输入属于观测或衍生？"}
];
const C={en:{back:"Intelligence overview",eyebrow:"EVIDENCE-BASED RESEARCH COPILOT / 08",title:"NEXORA AI",tagline:"Evidence-based intelligence for emerging industries.",support:"Ask across research, patents, policy, organizations, regions, and innovation ecosystems — with transparent evidence.",session:"Research session",starters:"Suggested research questions",domains:"Available domains",composer:"Ask a research question",placeholder:"Ask what the available evidence means…",ask:"Research",clear:"Clear",working:"Finding and validating evidence…",empty:"Begin with a research question or select a grounded starter prompt.",evidence:"Evidence",sources:"Sources",gaps:"Data gaps",why:"Why this answer?",coverage:"Evidence coverage",sufficiency:"Sufficiency",model:"Live model",notConfigured:"Not configured · evidence-first mode",method:"How NEXORA AI works",status:"Data status",answer:"Research answer",follow:"Grounded follow-up questions",observed:"Observed",derived:"Derived",demo:"Demo excluded",copy:"Copy",print:"Print",context:"Active context",noSources:"No source citation is available for this response.",noGaps:"No additional data gap was recorded.",history:"This session",provider:"Provider boundary",error:"NEXORA could not complete this request safely.",mode:"Data mode"},zh:{back:"返回情报总览",eyebrow:"证据驱动研究助理 / 08",title:"NEXORA AI",tagline:"面向未来产业的证据驱动智能研究助手。",support:"基于科研、专利、政策、组织、区域与创新生态进行可溯源研究。",session:"研究会话",starters:"建议研究问题",domains:"可用领域",composer:"提出研究问题",placeholder:"询问现有证据意味着什么……",ask:"研究",clear:"清除",working:"正在检索并核验证据……",empty:"输入研究问题，或选择一个基于现有数据的建议问题。",evidence:"证据",sources:"来源",gaps:"数据缺口",why:"为什么这样回答？",coverage:"证据覆盖",sufficiency:"充分性",model:"实时模型",notConfigured:"未配置 · 证据优先模式",method:"NEXORA AI 如何工作",status:"数据状态",answer:"研究回答",follow:"基于证据的后续问题",observed:"公开观测",derived:"衍生指标",demo:"已排除 Demo",copy:"复制",print:"打印",context:"当前上下文",noSources:"该回答没有可用来源引用。",noGaps:"未记录其他数据缺口。",history:"本次会话",provider:"供应商边界",error:"NEXORA 无法安全完成该请求。",mode:"数据模式"}};
const coverageLabels={STRONG:{en:"Strong",zh:"强"},PARTIAL:{en:"Partial",zh:"部分"},WEAK:{en:"Weak",zh:"弱"},UNAVAILABLE:{en:"Unavailable",zh:"不可用"},DEGRADED:{en:"Degraded",zh:"降级"}} as const;
const emptyContext:AIQueryContext={caseIds:[],technologyIds:[],regionIds:[],organizationIds:[],policyIds:[],industryIds:[],timeWindow:"ALL",dataMode:"HYBRID",allowDemoEvidence:false};

function queryContextFromUrl(){const p=new URLSearchParams(window.location.search),one=(key:string)=>{const v=p.get(key);return v&&/^[a-z0-9-]{1,80}$/.test(v)?[v]:[]},caseIds=one("case"),isCaliforniaAICase=caseIds.includes("california-ai"),dataMode:AIQueryContext["dataMode"]=isCaliforniaAICase?"PRODUCTION":"HYBRID";return {q:(p.get("q")??"").slice(0,600),context:{...emptyContext,caseIds,dataMode,allowDemoEvidence:false,technologyIds:one("technology"),regionIds:one("region"),organizationIds:one("organization"),policyIds:one("policy"),industryIds:one("industry")}}}

export function NexoraAIWorkspace(){const [lang,setLang]=useNexoraLanguage(),[question,setQuestion]=useState(""),[context,setContext]=useState<AIQueryContext>(emptyContext),[result,setResult]=useState<Result|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(""),[panel,setPanel]=useState<Panel>("evidence"),[showWhy,setShowWhy]=useState(false),[history,setHistory]=useState<{q:string;at:string}[]>([]),booted=useRef(false),t=lang==="zh"?{...C.zh,tagline:"面向未来产业的证据驱动研究助理"}:C.en;
 const run=useCallback(async(text:string,ctx:AIQueryContext,answerLang:AILanguage)=>{const clean=text.trim();if(!clean)return;setLoading(true);setError("");setShowWhy(false);try{const response=await fetch("/api/ai",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({text:clean,language:answerLang,context:ctx})});const data=await response.json() as Result&{message?:string};if(!response.ok)throw new Error(data.message??"SAFE_FAILURE");setResult(data);setHistory(h=>[{q:clean,at:new Date().toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})},...h].slice(0,6));setPanel("evidence")}catch{setError(t.error)}finally{setLoading(false)}},[t.error]);
 useEffect(()=>{if(booted.current)return;booted.current=true;const timer=window.setTimeout(()=>{const initial=queryContextFromUrl();setContext(initial.context);if(initial.q){setQuestion(initial.q);void run(initial.q,initial.context,lang)}},0);return()=>window.clearTimeout(timer)},[lang,run]);
 const submit=(e:FormEvent)=>{e.preventDefault();void run(question,context,lang)},selectStarter=(q:string)=>{setQuestion(q);void run(q,context,lang)},clear=()=>{setQuestion("");setResult(null);setError("");setContext(emptyContext)};
 const activeContext=[...context.caseIds,...context.technologyIds,...context.regionIds,...context.organizationIds,...context.policyIds,...context.industryIds],answer=result?.answer,evidence=result?.evidencePack.items.filter(x=>!["DATA_STATUS"].includes(x.kind))??[],coverage=result?.evidencePack.coverage,starters=context.caseIds.includes("california-ai")?caseStarter:starter;
 return <main className={styles.page}>
  <ResearchModuleShell image="/ai-og.png" eyebrow="NEXORA / FUTURE INDUSTRY INTELLIGENCE" title={lang==="en"?"NEXORA AI":"NEXORA AI"} subtitle={lang==="en"?"Evidence-based intelligence for emerging industries":"面向未来产业的循证智能"} description={lang==="en"?"Ask cross-domain questions and inspect the evidence, sources and gaps behind every answer.":"提出跨领域问题，并查看每项回答背后的证据、来源与缺口。"} enterLabel={lang==="en"?"Enter data workspace":"进入数据工作台"} insightLabel={lang==="en"?"Methods & evidence":"方法与证据"} lang={lang}/>
  <div id="workspace"/>
  <header className={styles.header}><div><Link prefetch={false} href="/" className={styles.brand}><span>N</span>NEXORA</Link><Link prefetch={false} href="/" className={styles.back}>← {t.back}</Link></div><nav aria-label="Language"><button className={lang==="en"?styles.on:""} onClick={()=>setLang("en")}>EN</button><button className={lang==="zh"?styles.on:""} onClick={()=>setLang("zh")}>中文</button></nav></header>
  <section className={styles.hero}><p>{t.eyebrow}</p><h1>{t.title}</h1><h2>{t.tagline}</h2><h3>{t.support}</h3><div className={styles.readiness}><span><i/>{t.model}<b>{t.notConfigured}</b></span><span>RESEARCH<b>PUBLIC DATA</b></span><span>PATENTS<b>NOT CONFIGURED</b></span><span>POLICY · ORGS<b>VERIFIED PILOT</b></span></div></section>
  <div className={styles.workspace}>
   <aside className={styles.left} aria-label={t.session}><div className={styles.panelTitle}><span>01</span><h2>{t.session}</h2></div>{history.length>0&&<section><h3>{t.history}</h3>{history.map((h,i)=><button key={`${h.at}-${i}`} onClick={()=>{setQuestion(h.q);void run(h.q,context,lang)}}><span>{h.q}</span><small>{h.at}</small></button>)}</section>}<section><h3>{t.starters}</h3>{starters.map((s,i)=><button key={s.en} onClick={()=>selectStarter(s[lang])}><i>0{i+1}</i><span>{s[lang]}</span></button>)}</section><section className={styles.domains}><h3>{t.domains}</h3><div>{["ATLAS","RADAR","ECOSYSTEMS","POLICY","ORGANIZATIONS","PUBLIC DATA"].map(x=><span key={x}>{x}</span>)}</div></section><footer><Link prefetch={false} href="/data-status">{t.status} →</Link><Link prefetch={false} href="/docs/AI_ARCHITECTURE.md">{t.method} →</Link></footer></aside>
   <section className={styles.center} aria-label={t.answer}><form onSubmit={submit} className={styles.composer}><label htmlFor="nexora-question">{t.composer}</label>{activeContext.length>0&&<div className={styles.context}><span>{t.context}</span>{activeContext.map(x=><i key={x}>{x}</i>)}</div>}<textarea id="nexora-question" value={question} onChange={e=>setQuestion(e.target.value.slice(0,600))} placeholder={t.placeholder} rows={3}/><div><span>{question.length} / 600</span><label>{t.mode}<select value={context.dataMode} onChange={e=>setContext(c=>({...c,dataMode:e.target.value as AIQueryContext["dataMode"]}))}><option>HYBRID</option><option>PRODUCTION</option><option>DEMO</option></select></label><button type="button" onClick={clear}>{t.clear}</button><button className={styles.submit} disabled={loading||!question.trim()}>{loading?t.working:t.ask} →</button></div></form>
    <div className={styles.liveRegion} aria-live="polite">{loading&&<div className={styles.loading}><i/><span>{t.working}<small>UNDERSTANDING → RETRIEVAL → CITATION CHECK → GROUNDING</small></span></div>}{error&&<div className={styles.error}>{error}</div>}{!loading&&!error&&!answer&&<div className={styles.empty}><div className={styles.node}><i/><i/><i/><b>NX·AI</b></div><h2>{t.empty}</h2><p>CANONICAL DATA → EVIDENCE PACK → VALIDATED RESPONSE</p></div>}{!loading&&answer&&<AnswerView answer={answer} lang={lang} t={t} showWhy={showWhy} setShowWhy={setShowWhy} pack={result!.evidencePack} onFollow={selectStarter}/>}</div>
   </section>
   <aside className={styles.right} aria-label={t.evidence}><div className={styles.panelTabs} role="tablist">{(["evidence","sources","gaps"] as Panel[]).map(x=><button role="tab" aria-selected={panel===x} className={panel===x?styles.active:""} onClick={()=>setPanel(x)} key={x}>{t[x]}</button>)}</div>{!result?<div className={styles.panelEmpty}><span>NO ACTIVE EVIDENCE PACK</span><small>{t.coverage} · {t.sufficiency}</small><p>{t.empty}</p></div>:<>{panel==="evidence"&&<><div className={styles.sufficiency}><span>{t.sufficiency}</span><b>{result.evidencePack.sufficiency.state}</b><small>{result.evidencePack.sufficiency.directEvidenceCount} OBSERVED · {result.evidencePack.sufficiency.sourceTypeCount} DIMENSIONS</small></div>{coverage&&<div className={styles.coverage}><h3>{t.coverage}</h3>{(Object.entries(coverage) as [string,keyof typeof coverageLabels][]).map(([k,v])=><span key={k}>{k.replaceAll(/([A-Z])/g," $1")}<b data-level={v}>{coverageLabels[v][lang]}</b></span>)}</div>}<div className={styles.evidenceList}>{evidence.slice(0,12).map(x=><EvidenceCard key={x.id} item={x} lang={lang}/>)}</div></>}{panel==="sources"&&<div className={styles.sourceList}>{answer?.citations.length?answer.citations.map((c,i)=><a key={c.id} href={c.url} rel="noreferrer"><span>[{i+1}] · {c.dataStatus}</span><b>{c.title}</b><small>{c.publisher} · retrieved {c.retrievedAt}</small></a>):<p>{t.noSources}</p>}</div>}{panel==="gaps"&&<div className={styles.gapList}>{answer?.dataGaps.length?answer.dataGaps.map((g,i)=><article key={i}><span>GAP 0{i+1}</span><p>{g[lang]}</p></article>):<p>{t.noGaps}</p>}</div>}</>}</aside>
  </div>
  <footer className={styles.globalFooter}><span>NEXORA AI / EVIDENCE LAYER / PUBLIC RC 1.0</span><nav>{[["/atlas","ATLAS"],["/radar","RADAR"],["/ecosystems","ECOSYSTEMS"],["/policy","POLICY"],["/companies","ORGANIZATIONS"],["/simulator","SIMULATOR"],["/data-status","DATA STATUS"]].map(x=><Link prefetch={false} href={x[0]} key={x[1]}>{x[1]}</Link>)}</nav></footer>
 </main>}

function AnswerView({answer,lang,t,showWhy,setShowWhy,pack,onFollow}:{answer:AIAnswer;lang:AILanguage;t:typeof C[AILanguage];showWhy:boolean;setShowWhy:(x:boolean)=>void;pack:EvidencePack;onFollow:(q:string)=>void}){const cite=(claimIds:string[])=>answer.citations.map((c,i)=>c.relatedClaimIds.some(id=>claimIds.includes(id))?<a key={c.id} href={c.url} aria-label={`Source ${i+1}: ${c.title}`}>[{i+1}]</a>:null);return <article className={styles.answer}><header><span>{answer.metadata.answerType.replaceAll("_"," ")} · {answer.metadata.generationMode.replaceAll("_"," ")}</span><div><button onClick={()=>void navigator.clipboard?.writeText(`${answer.title[lang]}\n\n${answer.summary[lang]}`)}>{t.copy}</button><button onClick={()=>window.print()}>{t.print}</button></div></header><h1>{answer.title[lang]}</h1><p className={styles.summary}>{answer.summary[lang]}</p><div className={styles.answerMeta}><span>{t.sufficiency}<b>{answer.metadata.evidenceSufficiency}</b></span><span>{t.observed}<b>{pack.sufficiency.directEvidenceCount}</b></span><span>{t.demo}<b>DEFAULT</b></span></div>{answer.sections.map(s=><section key={s.id}><h2>{s.title[lang]} <small>{cite(s.claimIds)}</small></h2>{s.body[lang].split("\n").map((p,i)=><p key={i}>{p}</p>)}</section>)}<button className={styles.why} onClick={()=>setShowWhy(!showWhy)} aria-expanded={showWhy}>{t.why} {showWhy?"−":"+"}</button>{showWhy&&<section className={styles.whyPanel}><p>NEXORA used {pack.sufficiency.directEvidenceCount} observed records across {pack.sufficiency.sourceTypeCount} evidence dimensions. The response used snapshots {pack.snapshotIds.join(" · ")} and prompt {answer.metadata.promptVersion}. This is user-facing evidence basis, not hidden reasoning.</p></section>}<section className={styles.limitations}><h2>{lang==="en"?"What NEXORA does not yet know":"NEXORA 目前还不知道什么"}</h2>{answer.dataGaps.slice(0,3).map((x,i)=><p key={i}>△ {x[lang]}</p>)}</section><section className={styles.follow}><h2>{t.follow}</h2>{answer.followUps.map(f=><button onClick={()=>onFollow(f.text[lang])} key={f.id}>{f.text[lang]} →</button>)}</section><footer><span>QUERY {answer.metadata.queryId}</span><span>{answer.metadata.groundingStatus} · {answer.metadata.promptVersion}</span></footer></article>}
function EvidenceCard({item,lang}:{item:EvidenceItem;lang:AILanguage}){return <article><span>{item.kind} · {item.status}</span><b>{item.title[lang]}</b><p>{item.summary[lang]}</p><small>{item.publisher} · {item.period??item.retrievedAt}</small></article>}
