"use client";
import Link from "@/components/safe-link";
import { useEffect, useMemo, useState, type CSSProperties } from "react";
import { calculateOpportunityScore, technologyMatchesFilters } from "@/lib/radar-score";
import { parseRadarQuery } from "@/lib/product-query";
import { useNexoraLanguage } from "@/hooks/use-nexora-language";
import { opportunityScoreConfig, radarIndustries, radarSignals, radarSnapshot, radarTechnologies } from "@/data/demo/radar";
import type { ConfidenceLevel, EmergingTechnology, OpportunityDimensionKey, SignalCategory, TechnologyStage, TrendDirection } from "@/domain/radar";
import styles from "./radar.module.css";
import { ModuleLanding } from "./module-landing";

type Lang="en"|"zh"; type Window="1Y"|"3Y"|"5Y"; type PanelTab="overview"|"score"|"evidence";
const copy={
 en:{back:"Intelligence overview",status:"PROTOTYPE / DEMO",title:"NEXORA Radar",tagline:"Detect the signals shaping tomorrow.",support:"Research. Patents. Startups. Capital. Policy. Talent. See where momentum is building.",snapshot:"Last snapshot",method:"Methodology",watch:"Watchlist-ready architecture",filters:"Intelligence filters",allIndustries:"All industries",allRegions:"All regions",allSignals:"All signal categories",allStages:"All stages",allConfidence:"All confidence levels",allMomentum:"All momentum",reset:"Reset filters",canvas:"Emerging Opportunity Radar",canvasSub:"Maturity moves from established at the center to frontier at the edge",frontier:"FRONTIER",mature:"MATURE",noData:"No technologies match this evidence filter.",noDataSub:"Broaden a filter to restore the analytical view.",textView:"Accessible technology view",leaderboard:"Momentum leaderboard",leaderSub:"Composite momentum ranked with explainable evidence",sort:"Sort by",columns:["Technology","Industry","Momentum","Change","Primary signal","Stage","Confidence"],signalExplorer:"Signal Explorer",signalSub:"Trace directional observations to their evidence and status",direction:"All directions",period:"Time window",technology:"Technology intelligence",close:"Close intelligence panel",tabs:["Overview","Why this score?","Evidence"],demo:"DEMO DATA",composite:"Composite score",uncertainty:"Illustrative interpretation based on prototype data.",primaryDrivers:"Primary drivers",moderated:"Missing or moderating evidence",signalBreakdown:"Signal breakdown",regional:"Emerging regional hotspots",viewAtlas:"View global geography",related:"Related technologies",risks:"Risks / uncertainties",overall:"Overall momentum",contribution:"Dimension contributions",available:"Available evidence weight",missing:"Missing evidence",confidence:"Confidence assessment",sources:"Evidence records",observed:"Observation type",methodology:"Methodology & trust",methodSub:"Transparent signals, explicit uncertainty, no investment recommendations",taxonomy:"Signal taxonomy",confidenceModel:"Confidence model",states:"Intentional data states",dataStatus:"Data Status",footer:"PUBLIC SIGNALS · TRACEABLE DERIVATIONS · EXPLAINABLE COMPOSITES",provider:"Provider unavailable",insufficient:"Insufficient evidence",loading:"Loading signal snapshot",mobileHint:"Select a technology for intelligence",scoreDisclosure:"Scores use configurable weights and renormalize only across available evidence."},
 zh:{back:"返回情报总览",status:"原型 / 演示数据",title:"NEXORA 未来产业雷达",tagline:"识别正在塑造未来的产业信号。",support:"科研 · 专利 · 创业 · 资本 · 政策 · 人才，洞察未来产业动能正在何处形成。",snapshot:"最近快照",method:"方法说明",watch:"已预留观察列表架构",filters:"情报筛选",allIndustries:"全部产业",allRegions:"全部地区",allSignals:"全部信号类型",allStages:"全部阶段",allConfidence:"全部置信度",allMomentum:"全部动能",reset:"重置筛选",canvas:"未来产业机会雷达",canvasSub:"中心代表较成熟阶段，外圈代表更早期的技术前沿",frontier:"前沿",mature:"成熟",noData:"当前证据筛选下没有匹配技术。",noDataSub:"请放宽筛选条件以恢复分析视图。",textView:"可访问技术列表",leaderboard:"动能排行榜",leaderSub:"基于可解释证据的综合动能排序",sort:"排序方式",columns:["技术","产业","动能","变化","主要信号","阶段","置信度"],signalExplorer:"趋势信号探索",signalSub:"将方向性观察追溯至证据与数据状态",direction:"全部方向",period:"时间窗口",technology:"技术情报",close:"关闭技术情报",tabs:["概览","评分解释","证据"],demo:"演示数据",composite:"综合评分",uncertainty:"基于原型数据的说明性解读。",primaryDrivers:"主要驱动因素",moderated:"缺失或限制性证据",signalBreakdown:"信号分解",regional:"新兴区域热点",viewAtlas:"查看全球创新地理",related:"相关技术",risks:"风险与不确定性",overall:"综合动能",contribution:"维度贡献",available:"可用证据权重",missing:"缺失证据",confidence:"置信度评估",sources:"证据记录",observed:"观测类型",methodology:"方法与可信度",methodSub:"透明信号、明确不确定性，不提供投资建议",taxonomy:"信号分类",confidenceModel:"置信度模型",states:"明确的数据状态",dataStatus:"数据状态",footer:"公共信号 · 可追溯衍生 · 可解释综合评分",provider:"数据源不可用",insufficient:"证据不足",loading:"正在加载信号快照",mobileHint:"选择技术以查看情报",scoreDisclosure:"评分采用可配置权重，并仅在已有证据维度之间重新归一化。"}
} as const;
const stages:Record<TechnologyStage,{en:string;zh:string;radius:number;rank:number}>={FRONTIER_RESEARCH:{en:"Frontier Research",zh:"前沿研究",radius:42,rank:1},EMERGING:{en:"Emerging",zh:"萌芽",radius:35,rank:2},EARLY_COMMERCIALIZATION:{en:"Early Commercialization",zh:"早期商业化",radius:27,rank:3},SCALING:{en:"Scaling",zh:"规模化",radius:19,rank:4},ESTABLISHED:{en:"Established",zh:"成熟阶段",radius:11,rank:5}};
const directions:Record<TrendDirection,{en:string;zh:string;mark:string}>={ACCELERATING:{en:"Accelerating",zh:"加速",mark:"↗"},RISING:{en:"Rising",zh:"上升",mark:"↑"},STABLE:{en:"Stable",zh:"稳定",mark:"→"},COOLING:{en:"Cooling",zh:"降温",mark:"↓"},UNCERTAIN:{en:"Uncertain",zh:"不确定",mark:"?"}};
const confidences:Record<ConfidenceLevel,{en:string;zh:string}>={HIGH:{en:"High",zh:"高"},MEDIUM:{en:"Medium",zh:"中"},LOW:{en:"Low",zh:"低"},INSUFFICIENT:{en:"Insufficient Evidence",zh:"证据不足"}};
const categories:Record<SignalCategory,{en:string;zh:string;dimension?:OpportunityDimensionKey}>={RESEARCH:{en:"Research",zh:"科研",dimension:"research"},PATENTS:{en:"Patents",zh:"专利",dimension:"patents"},STARTUPS:{en:"Startups",zh:"创业",dimension:"startups"},CAPITAL:{en:"Capital",zh:"资本",dimension:"capital"},POLICY:{en:"Policy",zh:"政策",dimension:"policy"},TALENT:{en:"Talent",zh:"人才",dimension:"talent"},MARKET:{en:"Market",zh:"市场",dimension:"marketReadiness"},TECHNOLOGY_MATURITY:{en:"Technology Maturity",zh:"技术成熟度",dimension:"technologyMaturity"},ECOSYSTEM_ACTIVITY:{en:"Ecosystem Activity",zh:"创新生态活动",dimension:"ecosystemStrength"}};
const regions=[...new Set(radarTechnologies.flatMap(t=>t.regions))].sort();
const dimensionName=(key:OpportunityDimensionKey,lang:Lang)=>opportunityScoreConfig.dimensions.find(d=>d.key===key)!.label[lang];
const nodePosition=(tech:EmergingTechnology)=>{const industry=radarIndustries.find(i=>i.id===tech.industryId)!;const peers=radarTechnologies.filter(t=>t.industryId===tech.industryId);const offset=(peers.findIndex(t=>t.id===tech.id)-(peers.length-1)/2)*7;const angle=(-90+industry.sectorIndex*40+offset)*Math.PI/180;const radius=stages[tech.stage].radius;return {"--x":`${50+Math.cos(angle)*radius}%`,"--y":`${50+Math.sin(angle)*radius}%`} as CSSProperties};

export function Radar(){
 const [lang,setLang]=useNexoraLanguage(),[industry,setIndustry]=useState("all"),[region,setRegion]=useState("all"),[category,setCategory]=useState<SignalCategory|"all">("all"),[stage,setStage]=useState<TechnologyStage|"all">("all"),[confidence,setConfidence]=useState<ConfidenceLevel|"all">("all"),[minimum,setMinimum]=useState("all"),[direction,setDirection]=useState<TrendDirection|"all">("all"),[window,setWindow]=useState<Window>("3Y"),[selectedId,setSelectedId]=useState("ai-agents"),[panelTab,setPanelTab]=useState<PanelTab>("overview"),[panelOpen,setPanelOpen]=useState(true),[sort,setSort]=useState("overall");
 useEffect(()=>{const timer=globalThis.setTimeout(()=>{const query=parseRadarQuery(globalThis.location.search);if(query.technologyId){setSelectedId(query.technologyId);setPanelOpen(true)}if(query.region)setRegion(query.region)},0);return()=>globalThis.clearTimeout(timer)},[]);
 const t=lang==="zh"?{...copy.zh,tagline:"识别塑造产业未来的关键信号"}:copy.en,selected=radarTechnologies.find(x=>x.id===selectedId)??radarTechnologies[0],score=(tech:EmergingTechnology)=>calculateOpportunityScore(tech.metrics,opportunityScoreConfig);
 const filtered=useMemo(()=>radarTechnologies.filter(tech=>technologyMatchesFilters(tech,{industry:industry==="all"?undefined:industry,region:region==="all"?undefined:region,stage:stage==="all"?undefined:stage,confidence:confidence==="all"?undefined:confidence,categoryKey:category==="all"?undefined:categories[category].dimension,minimumMomentum:minimum==="all"?undefined:Number(minimum)},opportunityScoreConfig)),[industry,region,stage,confidence,category,minimum]);
 const leaderboard=useMemo(()=>[...filtered].sort((a,b)=>{if(sort==="stage")return stages[b.stage].rank-stages[a.stage].rank;const key=sort==="overall"?null:sort as OpportunityDimensionKey;const av=key?a.metrics.find(m=>m.key===key)?.value:score(a).value;const bv=key?b.metrics.find(m=>m.key===key)?.value:score(b).value;return (bv??-1)-(av??-1)}),[filtered,sort]);
 const signals=radarSignals.filter(s=>filtered.some(x=>x.id===s.technologyId)&&(category==="all"||s.category===category)&&(region==="all"||s.region===region)&&(direction==="all"||s.direction===direction));
 const reset=()=>{setIndustry("all");setRegion("all");setCategory("all");setStage("all");setConfidence("all");setMinimum("all");setDirection("all")};
 const select=(id:string)=>{setSelectedId(id);setPanelTab("overview");setPanelOpen(true)};
 return <main className={styles.radar}>
  <ModuleLanding image="/radar-og.png" eyebrow="NEXORA / FUTURE INDUSTRY INTELLIGENCE" title={lang==="en"?"NEXORA RADAR":"NEXORA 未来产业雷达"} subtitle={lang==="en"?"Detect the signals shaping tomorrow":"识别塑造产业未来的关键信号"} description={lang==="en"?"Explore emerging technologies, momentum, maturity and the evidence behind each signal.":"探索新兴技术、发展动能、成熟度及每项信号背后的证据。"} enterLabel={lang==="en"?"Enter data workspace":"进入数据工作台"} insightLabel={lang==="en"?"Methods & evidence":"方法与证据"} lang={lang}/>
  <div id="workspace"/>
  <header className={styles.header}><div><Link href="/" className={styles.brand}><span>N</span>NEXORA</Link><i/><Link href="/" className={styles.back}>← {t.back}</Link></div><div><span className={styles.status}><i/>{t.status}</span><span className={styles.language}><button className={lang==="en"?styles.on:""} onClick={()=>setLang("en")}>EN</button><button className={lang==="zh"?styles.on:""} onClick={()=>setLang("zh")}>中文</button></span></div></header>
  <section className={styles.hero}><div><p>FUTURE INDUSTRY SIGNAL SYSTEM / 03</p><h1>{t.title}</h1><h2>{t.tagline}</h2><h3>{t.support}</h3></div><div className={styles.heroMeta}><span>{t.snapshot}<b>{radarSnapshot.capturedAt.slice(0,10)}</b></span><a href="#method">{t.method} ↘</a><span>{t.watch}<b>ARCHITECTURE READY</b></span></div></section>
  <section className={styles.filterSection} aria-label={t.filters}><div className={styles.filterLabel}>{t.filters}<span>06 DIMENSIONS / 18 TECHNOLOGIES</span></div><div className={styles.filterGrid}><select aria-label={t.allIndustries} value={industry} onChange={e=>setIndustry(e.target.value)}><option value="all">{t.allIndustries}</option>{radarIndustries.map(i=><option key={i.id} value={i.id}>{i.name[lang]}</option>)}</select><select aria-label={t.allRegions} value={region} onChange={e=>setRegion(e.target.value)}><option value="all">{t.allRegions}</option>{regions.map(r=><option key={r}>{r}</option>)}</select><select aria-label={t.allSignals} value={category} onChange={e=>setCategory(e.target.value as SignalCategory|"all")}><option value="all">{t.allSignals}</option>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v[lang]}</option>)}</select><select aria-label={t.allStages} value={stage} onChange={e=>setStage(e.target.value as TechnologyStage|"all")}><option value="all">{t.allStages}</option>{Object.entries(stages).map(([k,v])=><option key={k} value={k}>{v[lang]}</option>)}</select><select aria-label={t.allMomentum} value={minimum} onChange={e=>setMinimum(e.target.value)}><option value="all">{t.allMomentum}</option><option value="85">85+</option><option value="75">75+</option><option value="65">65+</option></select><select aria-label={t.allConfidence} value={confidence} onChange={e=>setConfidence(e.target.value as ConfidenceLevel|"all")}><option value="all">{t.allConfidence}</option>{Object.entries(confidences).map(([k,v])=><option key={k} value={k}>{v[lang]}</option>)}</select><button onClick={reset}>{t.reset} ×</button></div></section>
  <section className={styles.radarSection}><div className={styles.sectionTitle}><span>01 / OPPORTUNITY FIELD</span><div><h2>{t.canvas}</h2><p>{t.canvasSub}</p></div></div><div className={styles.radarLayout}><div className={styles.canvas} aria-label={t.canvas}><div className={styles.rings}>{[1,2,3,4,5].map(n=><i key={n}/>)}</div><div className={styles.sectors}>{radarIndustries.map((i,n)=><i key={i.id} style={{transform:`rotate(${n*40}deg)`}}/>)}</div><div className={styles.sweep}/><span className={styles.centerLabel}>{t.mature}</span><span className={styles.frontierLabel}>{t.frontier}</span>{filtered.map(tech=>{const s=score(tech);return <button title={`${tech.name[lang]} — ${s.value??t.insufficient}`} key={tech.id} onClick={()=>select(tech.id)} className={`${styles.node} ${styles[tech.direction.toLowerCase()]} ${tech.id===selectedId?styles.nodeActive:""}`} style={{...nodePosition(tech),"--size":`${11+(s.value??50)/8}px`} as CSSProperties}><i>{directions[tech.direction].mark}</i><span>{tech.name[lang]}<b>{s.value??"—"}</b></span></button>})}{filtered.length===0&&<div className={styles.empty}><b>{t.noData}</b><span>{t.noDataSub}</span><button onClick={reset}>{t.reset}</button></div>}<div className={styles.canvasLegend}>{Object.entries(stages).map(([k,v])=><span key={k}><i/>{v[lang]}</span>)}</div></div><div className={styles.accessibleList}><h3>{t.textView}</h3>{filtered.map(tech=><button key={tech.id} onClick={()=>select(tech.id)}><span>{directions[tech.direction].mark}</span><b>{tech.name[lang]}</b><em>{stages[tech.stage][lang]}</em><strong>{score(tech).value??"—"}</strong></button>)}</div>{panelOpen&&<TechnologyPanel tech={selected} lang={lang} t={t} tab={panelTab} setTab={setPanelTab} close={()=>setPanelOpen(false)} window={window} setWindow={setWindow}/>}</div></section>
  <section className={styles.analysis}><div className={styles.sectionTitle}><span>02 / MOMENTUM</span><div><h2>{t.leaderboard}</h2><p>{t.leaderSub}</p></div></div><div className={styles.sorter}><span>{t.sort}</span><select value={sort} onChange={e=>setSort(e.target.value)}><option value="overall">{t.overall}</option><option value="research">{categories.RESEARCH[lang]}</option><option value="patents">{categories.PATENTS[lang]}</option><option value="startups">{categories.STARTUPS[lang]}</option><option value="policy">{categories.POLICY[lang]}</option><option value="stage">{lang==="en"?"Technology Stage":"技术阶段"}</option></select></div><div className={styles.table} role="table"><div className={styles.tableHead} role="row">{t.columns.map(x=><span key={x}>{x}</span>)}</div>{leaderboard.slice(0,10).map((tech,i)=><button className={styles.tableRow} role="row" key={tech.id} onClick={()=>select(tech.id)}><span><i>0{i+1}</i><b>{tech.name[lang]}</b></span><span>{radarIndustries.find(x=>x.id===tech.industryId)!.name[lang]}</span><span><strong>{score(tech).value??"—"}</strong><em><i style={{width:`${score(tech).value??0}%`}}/></em></span><span className={styles[tech.direction.toLowerCase()]}>{tech.change===null?"—":`${tech.change>0?"+":""}${tech.change}%`}</span><span>{categories[tech.primarySignal][lang]}</span><span>{stages[tech.stage][lang]}</span><span>{confidences[tech.confidence.level][lang]}</span></button>)}</div></section>
  <section className={`${styles.analysis} ${styles.signalSection}`}><div className={styles.sectionTitle}><span>03 / EVIDENCE</span><div><h2>{t.signalExplorer}</h2><p>{t.signalSub}</p></div></div><div className={styles.signalToolbar}><div><button className={window==="1Y"?styles.active:""} onClick={()=>setWindow("1Y")}>1Y</button><button className={window==="3Y"?styles.active:""} onClick={()=>setWindow("3Y")}>3Y</button><button className={window==="5Y"?styles.active:""} onClick={()=>setWindow("5Y")}>5Y</button></div><select value={direction} onChange={e=>setDirection(e.target.value as TrendDirection|"all")}><option value="all">{t.direction}</option>{Object.entries(directions).map(([k,v])=><option key={k} value={k}>{v[lang]}</option>)}</select></div><div className={styles.signals}>{signals.length?signals.slice(0,12).map(signal=>{const tech=radarTechnologies.find(x=>x.id===signal.technologyId)!;return <button key={signal.id} onClick={()=>select(signal.technologyId)}><span className={styles.directionMark}>{directions[signal.direction].mark}<i>{directions[signal.direction][lang]}</i></span><span><b>{tech.name[lang]}</b><small>{categories[signal.category][lang]} · {signal.region}</small></span><span>{signal.observationPeriod}<small>{signal.dataStatus}</small></span><span>{confidences[signal.confidence][lang]}<small>{t.demo}</small></span></button>}):<div className={styles.signalEmpty}>{t.noData}<button onClick={reset}>{t.reset}</button></div>}</div></section>
  <section id="method" className={`${styles.analysis} ${styles.method}`}><div className={styles.sectionTitle}><span>04 / TRUST</span><div><h2>{t.methodology}</h2><p>{t.methodSub}</p></div></div><div className={styles.methodGrid}><article><span>01</span><h3>{t.taxonomy}</h3><p>OBSERVED PUBLIC SIGNAL → DERIVED MOMENTUM → NEXORA COMPOSITE → AI INTERPRETATION</p></article><article><span>02</span><h3>{t.confidenceModel}</h3><p>COMPLETENESS · SOURCE DIVERSITY · RECENCY · CONSISTENCY</p></article><article><span>03</span><h3>{t.states}</h3><p>{t.loading} · {t.noData} · {t.insufficient} · {t.provider}</p></article></div><div className={styles.disclosure}><span>{t.dataStatus}: <b>{t.status}</b></span><span>{t.scoreDisclosure}</span><Link href="/docs/RADAR_METHOD.md">{t.method} →</Link></div></section>
  <footer className={styles.footer}><span>NEXORA RADAR / METHODOLOGY v0.3</span><span>{t.footer}</span></footer>
 </main>
}

function TechnologyPanel({tech,lang,t,tab,setTab,close,window,setWindow}:{tech:EmergingTechnology;lang:Lang;t:typeof copy[Lang];tab:PanelTab;setTab:(x:PanelTab)=>void;close:()=>void;window:Window;setWindow:(x:Window)=>void}){
 const result=calculateOpportunityScore(tech.metrics,opportunityScoreConfig),industry=radarIndustries.find(x=>x.id===tech.industryId)!;const drivers=[...result.contributions].sort((a,b)=>b.weightedValue-a.weightedValue).slice(0,3);const points=tech.timeSeries[window],max=Math.max(...points.map(p=>p.value??0));
 return <aside className={styles.panel}><div className={styles.panelHead}><span>{t.technology}<i>{t.demo}</i></span><button onClick={close} aria-label={t.close}>×</button></div><div className={styles.panelTitle}><small>{industry.name[lang]} / {categories[tech.primarySignal][lang]}</small><h2>{tech.name[lang]}</h2><p>{tech.summary[lang]}</p><div><b>{result.value??"—"}</b><span>{t.composite}<i>{directions[tech.direction].mark} {directions[tech.direction][lang]}</i></span></div></div><div className={styles.panelTabs}>{(["overview","score","evidence"] as PanelTab[]).map((x,i)=><button key={x} className={tab===x?styles.active:""} onClick={()=>setTab(x)}>{t.tabs[i]}</button>)}</div>
 {tab==="overview"&&<div className={styles.panelBody}><p className={styles.demoNote}>{t.uncertainty}</p><PanelLabel>{t.signalBreakdown}</PanelLabel><div className={styles.breakdown}>{tech.metrics.map(m=><div key={m.key}><span>{m.label[lang]}<i>{m.value===null?t.insufficient:directions[m.direction][lang]}</i></span><b>{m.value??"—"}</b><em><i style={{width:`${m.value??0}%`}}/></em></div>)}</div><PanelLabel>{t.regional}</PanelLabel><div className={styles.regionLinks}>{tech.regions.map(r=><Link key={r} href={`/atlas?region=${encodeURIComponent(r)}&technology=${tech.id}`}>{r}<span>↗</span></Link>)}</div><Link href={`/atlas?technology=${tech.id}`} className={styles.atlasLink}>{t.viewAtlas} →</Link><Link href={`/ecosystems?technology=${tech.id}`} className={styles.atlasLink}>{lang==="en"?"View ecosystem network":"查看创新生态网络"} →</Link><Link href={`/policy?technology=${tech.id}`} className={styles.atlasLink}>{lang==="en"?"View policy signals":"查看政策信号"} →</Link><Link href={`/companies?technology=${tech.id}&industry=${tech.industryId}`} className={styles.atlasLink}>{lang==="en"?"View Organizations":"查看相关组织"} →</Link><Link href={`/ai?technology=${tech.id}`} className={styles.atlasLink}>{lang==="en"?"Ask NEXORA why this signal matters":"询问 NEXORA 此信号为何重要"} →</Link><Link href={`/simulator?technology=${tech.id}&industry=${tech.industryId}`} className={styles.atlasLink}>{lang==="en"?"Explore future scenario":"探索未来情景"} →</Link><PanelLabel>{t.related}</PanelLabel><div className={styles.related}>{tech.related.map((r,i)=><span key={r.id}><i>{i+1}</i>{radarTechnologies.find(x=>x.id===r.toId)?.name[lang]??r.toId}</span>)}</div><PanelLabel>{t.risks}</PanelLabel>{tech.risks.map(r=><p className={styles.risk} key={r.en}>△ {r[lang]}</p>)}</div>}
 {tab==="score"&&<div className={styles.panelBody}><div className={styles.scoreHero}><b>{result.value??"—"}</b><span>{t.overall}<i>{t.demo}</i></span></div><PanelLabel>{t.contribution}</PanelLabel><div className={styles.contributions}>{drivers.map(c=><div key={c.key}><span>{dimensionName(c.key,lang)}</span><b>{c.rawValue}</b><em>{Math.round(c.effectiveWeight*100)}%</em></div>)}</div><PanelLabel>{t.primaryDrivers}</PanelLabel><p className={styles.interpretation}>{drivers.map(d=>dimensionName(d.key,lang)).join(" · ")}</p><PanelLabel>{t.moderated}</PanelLabel><p className={styles.interpretation}>{result.missing.length?result.missing.map(k=>dimensionName(k,lang)).join(" · "):lang==="en"?"No configured dimension is missing in this prototype snapshot.":"当前原型快照中没有缺失的配置维度。"}</p><div className={styles.coverage}><span>{t.available}</span><b>{Math.round(result.availableWeight*100)}%</b></div><PanelLabel>{t.confidence}</PanelLabel><div className={styles.confidenceBars}>{[[lang==="en"?"Completeness":"完整度",tech.confidence.completeness],[lang==="en"?"Source diversity":"来源多样性",tech.confidence.sourceDiversity],[lang==="en"?"Recency":"时效性",tech.confidence.recency],[lang==="en"?"Consistency":"一致性",tech.confidence.consistency]].map(x=><span key={String(x[0])}>{x[0]}<i><em style={{width:`${x[1]}%`}}/></i><b>{x[1]}</b></span>)}</div></div>}
 {tab==="evidence"&&<div className={styles.panelBody}><div className={styles.timeControl}><span>{t.period}</span>{(["1Y","3Y","5Y"] as Window[]).map(x=><button className={window===x?styles.active:""} onClick={()=>setWindow(x)} key={x}>{x}</button>)}</div><div className={styles.timeSeries}>{points.map((p,i)=><div key={p.period}><i style={{height:`${((p.value??0)/max)*100}%`}}/><span>{p.period}</span>{i===points.length-1&&<b>{p.value??"—"}</b>}</div>)}</div><PanelLabel>{t.sources}</PanelLabel>{tech.evidence.map(e=><article className={styles.evidence} key={e.id}><span>{e.sourceName}<i>{e.isDemo?t.demo:e.observationType}</i></span><h3>{e.title[lang]}</h3><p>{e.geography} · {e.timePeriod}</p><a href={e.sourceUrl}>{t.method} ↗</a></article>)}</div>}
 </aside>
}
function PanelLabel({children}:{children:React.ReactNode}){return <h3 className={styles.panelLabel}>{children}</h3>}
