import type { EcosystemContext,OutputId,ParameterId,SensitivityResult,SensitivityRun } from "../../domain/simulation.ts";
import type { Scenario } from "../../domain/simulation.ts";
import { modelParameters } from "../parameters/parameters.ts";
import { runSimulation } from "../solver/solver.ts";

const round=(v:number,d=2)=>Number(v.toFixed(d));
const hash=(s:string)=>{let h=0;for(const c of s)h=Math.imul(31,h)+c.charCodeAt(0)|0;return (h>>>0).toString(16)};
export function oneWaySensitivity(scenario:Scenario,parameterId:ParameterId,outputId:OutputId="innovationOutput",context:EcosystemContext={regionId:null,industryId:null,technologyId:null,ecosystemId:null,policyId:null},baseOverrides:Partial<Record<ParameterId,number>>={}):SensitivityResult{const def=modelParameters.find(x=>x.id===parameterId);if(!def)throw new Error("UNKNOWN_PARAMETER");const [low,high]=def.sensitivityRange,step=(high-low)/4,points=Array.from({length:5},(_,i)=>round(low+step*i,4)).map(parameterValue=>({parameterValue,outputValue:runSimulation(scenario,{...baseOverrides,[parameterId]:parameterValue},context).outputs.finalValues[outputId]}));const values=points.map(x=>x.outputValue),outputRange:[number,number]=[Math.min(...values),Math.max(...values)];return {parameterId,parameterName:def.name,range:[low,high],outputId,points,outputRange,sensitivityStrength:round(outputRange[1]-outputRange[0],2)}}
export function sensitivityRanking(scenario:Scenario,outputId:OutputId="innovationOutput",context:EcosystemContext={regionId:null,industryId:null,technologyId:null,ecosystemId:null,policyId:null},limit=8,baseOverrides:Partial<Record<ParameterId,number>>={}):SensitivityRun{const results=modelParameters.filter(x=>!x.id.endsWith("Lag")).map(x=>oneWaySensitivity(scenario,x.id,outputId,context,baseOverrides)).sort((a,b)=>b.sensitivityStrength-a.sensitivityStrength).slice(0,limit);const seed=JSON.stringify({scenario:scenario.id,outputId,baseOverrides,results:results.map(x=>[x.parameterId,x.outputRange])});return {id:`sens-${hash(seed)}`,scenarioId:scenario.id,outputId,results,modelVersion:"sim-model-v1.0.0",reproducibilityHash:hash(seed)}}
