import type { EcosystemEdge, EcosystemFilter, EcosystemGraph, EcosystemGraphValidation, EcosystemHealthConfig, EcosystemHealthDimensionKey, EcosystemHealthResult, EcosystemNode } from "../domain/ecosystems";

export function validateEcosystemGraph(graph:EcosystemGraph,validRegions:Set<string>):EcosystemGraphValidation{
 const nodes=new Set(graph.nodes.map(n=>n.id)),seen=new Set<string>(),orphans:string[]=[],self:string[]=[],dupes:string[]=[],missing:string[]=[],invalidRegions:string[]=[];
 for(const node of graph.nodes)if(!validRegions.has(node.regionId))invalidRegions.push(node.id);
 for(const edge of graph.edges){if(!nodes.has(edge.sourceNodeId)||!nodes.has(edge.targetNodeId))orphans.push(edge.id);if(edge.sourceNodeId===edge.targetNodeId)self.push(edge.id);const key=[edge.sourceNodeId,edge.targetNodeId,edge.relationshipType].join("|");if(seen.has(key))dupes.push(edge.id);seen.add(key);if(!edge.isDemo&&edge.evidenceIds.length===0)missing.push(edge.id);}
 return {valid:![orphans,self,dupes,missing,invalidRegions].some(x=>x.length),orphanEdgeIds:orphans,selfEdgeIds:self,duplicateEdgeIds:dupes,missingEvidenceEdgeIds:missing,invalidRegionNodeIds:invalidRegions};
}
export function adjacency(nodes:EcosystemNode[],edges:EcosystemEdge[]){const map=new Map(nodes.map(n=>[n.id,new Set<string>()]));for(const e of edges){map.get(e.sourceNodeId)?.add(e.targetNodeId);map.get(e.targetNodeId)?.add(e.sourceNodeId)}return map;}
export function degreeCentrality(nodes:EcosystemNode[],edges:EcosystemEdge[]){const adj=adjacency(nodes,edges),den=Math.max(1,nodes.length-1);return new Map(nodes.map(n=>[n.id,(adj.get(n.id)?.size??0)/den]));}
export function betweennessCentrality(nodes:EcosystemNode[],edges:EcosystemEdge[]){
 const adj=adjacency(nodes,edges),score=new Map(nodes.map(n=>[n.id,0]));
 for(const s of nodes.map(n=>n.id)){const stack:string[]=[],pred=new Map(nodes.map(n=>[n.id,[] as string[]])),sigma=new Map(nodes.map(n=>[n.id,0])),dist=new Map(nodes.map(n=>[n.id,-1]));sigma.set(s,1);dist.set(s,0);const q=[s];while(q.length){const v=q.shift()!;stack.push(v);for(const w of adj.get(v)??[]){if(dist.get(w)===-1){q.push(w);dist.set(w,dist.get(v)!+1)}if(dist.get(w)===dist.get(v)!+1){sigma.set(w,sigma.get(w)!+sigma.get(v)!);pred.get(w)!.push(v)}}}const delta=new Map(nodes.map(n=>[n.id,0]));while(stack.length){const w=stack.pop()!;for(const v of pred.get(w)!)delta.set(v,delta.get(v)!+(sigma.get(v)!/sigma.get(w)!)*(1+delta.get(w)!));if(w!==s)score.set(w,score.get(w)!+delta.get(w)!);}}
 const scale=nodes.length>2?1/((nodes.length-1)*(nodes.length-2)):1;for(const [k,v] of score)score.set(k,v*scale);return score;
}
export function neighborhood(nodeId:string,edges:EcosystemEdge[],hops:1|2){const adj=adjacency([...new Set(edges.flatMap(e=>[e.sourceNodeId,e.targetNodeId]))].map(id=>({id} as EcosystemNode)),edges);const found=new Set([nodeId]);let frontier=new Set([nodeId]);for(let i=0;i<hops;i++){const next=new Set<string>();for(const id of frontier)for(const n of adj.get(id)??[])if(!found.has(n)){found.add(n);next.add(n)}frontier=next}return found;}
export function filterGraph(graph:EcosystemGraph,filter:EcosystemFilter){
 const q=filter.search?.trim().toLowerCase();const nodes=graph.nodes.filter(n=>(!filter.regionId||n.regionId===filter.regionId)&&(!filter.industryId||n.industryIds.includes(filter.industryId))&&(!filter.technologyId||n.technologyIds.includes(filter.technologyId))&&(!filter.nodeType||n.nodeType===filter.nodeType)&&(!filter.evidenceStatus||n.evidenceStatus===filter.evidenceStatus)&&(!q||`${n.name.en} ${n.name.zh} ${n.regionId} ${n.industryIds.join(" ")} ${n.technologyIds.join(" ")}`.toLowerCase().includes(q)));const ids=new Set(nodes.map(n=>n.id));const edges=graph.edges.filter(e=>ids.has(e.sourceNodeId)&&ids.has(e.targetNodeId)&&(!filter.relationshipType||e.relationshipType===filter.relationshipType)&&(!filter.confidence||e.confidence===filter.confidence)&&(filter.layers.length===0||e.layers.some(l=>filter.layers.includes(l))));return {...graph,nodes,edges};
}
export function calculateHealth(values:Partial<Record<EcosystemHealthDimensionKey,number|null>>,config:EcosystemHealthConfig):EcosystemHealthResult{const available=config.dimensions.filter(d=>values[d.key]!==null&&values[d.key]!==undefined),total=available.reduce((s,d)=>s+d.weight,0),missing=config.dimensions.filter(d=>values[d.key]===null||values[d.key]===undefined).map(d=>d.key);if(total===0)return {value:null,contributions:[],missing,availableWeight:0,isDemoComposite:true};const contributions=available.map(d=>({key:d.key,value:values[d.key]!,effectiveWeight:d.weight/total,weightedValue:values[d.key]!*(d.weight/total)}));return {value:Math.round(contributions.reduce((s,c)=>s+c.weightedValue,0)*10)/10,contributions,missing,availableWeight:total,isDemoComposite:true};}
export function parseEcosystemQuery(query:string){const p=new URLSearchParams(query),rawRegion=p.get("region"),rawIndustry=p.get("industry");return {regionId:rawRegion==="sf-bay-area"||rawRegion==="california"?"sf":rawRegion==="los-angeles"?"la":rawRegion||undefined,industryId:rawIndustry==="artificial-intelligence"?"ai":rawIndustry||undefined,technologyId:p.get("technology")||undefined,layer:p.get("layer")||undefined,nodeId:p.get("node")||undefined};}
