import type { OrganizationComparisonRow, OrganizationFilter, OrganizationMetric, OrganizationProfile, OrganizationQuery, OrganizationRelationship, OrganizationRole, OrganizationSort, OrganizationSource, OrganizationType, OrganizationValidationResult } from "../domain/organizations.ts";

export const ORGANIZATION_TYPES=new Set<OrganizationType>(["STARTUP","CORPORATION","UNIVERSITY","RESEARCH_INSTITUTION","INVESTOR","GOVERNMENT_AGENCY","PUBLIC_PROGRAM","NONPROFIT","INDUSTRY_ASSOCIATION","PUBLIC_LAB","OTHER_ORGANIZATION"]);
export const ORGANIZATION_ROLES=new Set<OrganizationRole>(["RESEARCH","TECHNOLOGY_DEVELOPMENT","COMMERCIALIZATION","MANUFACTURING","INVESTMENT","POLICY","PUBLIC_FUNDING","INFRASTRUCTURE","EDUCATION","STANDARDIZATION","SUPPLY_CHAIN","MARKET_DEVELOPMENT","ECOSYSTEM_COORDINATION"]);

export function organizationMetrics(profile:OrganizationProfile,relationships:OrganizationRelationship[]):OrganizationMetric{
 const connected=relationships.filter(r=>r.sourceOrganizationId===profile.id||r.targetOrganizationId===profile.id),relationshipDiversity=new Set(connected.map(r=>r.relationshipType)).size;
 const evidenceDimensions=[profile.sourceIds.length>0,profile.roles.some(r=>r.evidenceIds.length>0),profile.industryLinks.some(x=>x.evidenceIds.length>0),profile.technologyLinks.some(x=>x.evidenceIds.length>0),profile.regionLinks.some(x=>x.evidenceIds.length>0),profile.policyLinks.some(x=>x.evidenceIds.length>0),connected.some(x=>x.evidenceIds.length>0)];
 return {organizationId:profile.id,connectivity:connected.length,relationshipDiversity,evidenceCoverage:Math.round(evidenceDimensions.filter(Boolean).length/evidenceDimensions.length*100),isDerived:true,isDemo:profile.isDemo};
}
export function filterOrganizations(profiles:OrganizationProfile[],filter:OrganizationFilter){const q=filter.search?.trim().toLowerCase();return profiles.filter(p=>(!filter.type||p.organizationType===filter.type)&&(!filter.role||p.roles.some(r=>r.role===filter.role))&&(!filter.industryId||p.industryLinks.some(x=>x.industryId===filter.industryId))&&(!filter.technologyId||p.technologyLinks.some(x=>x.technologyId===filter.technologyId))&&(!filter.regionId||p.regionLinks.some(x=>x.regionId===filter.regionId))&&(!filter.country||p.country===filter.country)&&(!filter.city||p.city===filter.city)&&(!filter.ecosystemId||p.ecosystemIds.includes(filter.ecosystemId))&&(!filter.evidenceStatus||p.evidenceStatus===filter.evidenceStatus)&&(!filter.confidence||p.confidence.level===filter.confidence)&&(!q||[p.name,p.localizedName.zh,p.country,p.region,p.city,p.organizationType,...p.roles.map(x=>x.role),...p.industryLinks.map(x=>x.industryId),...p.technologyLinks.map(x=>x.technologyId)].filter(Boolean).join(" ").toLowerCase().includes(q)));}
export function sortOrganizations(profiles:OrganizationProfile[],sort:OrganizationSort,relationships:OrganizationRelationship[]){return [...profiles].sort((a,b)=>{if(sort==="NAME")return a.name.localeCompare(b.name);if(sort==="TYPE")return a.organizationType.localeCompare(b.organizationType)||a.name.localeCompare(b.name);if(sort==="REGION")return (a.region??"").localeCompare(b.region??"")||a.name.localeCompare(b.name);if(sort==="FOUNDED_YEAR")return (b.foundedYear??-1)-(a.foundedYear??-1);const am=organizationMetrics(a,relationships),bm=organizationMetrics(b,relationships);return sort==="CONNECTIVITY"?bm.connectivity-am.connectivity:bm.evidenceCoverage-am.evidenceCoverage;});}
export function parseOrganizationQuery(query:string):OrganizationQuery{const p=new URLSearchParams(query);return {organizationId:p.get("organization")||undefined,industryId:p.get("industry")||undefined,technologyId:p.get("technology")||undefined,regionId:p.get("region")||undefined,type:(p.get("type")||undefined) as OrganizationType|undefined,ecosystemId:p.get("ecosystem")||undefined};}
const join=(xs:string[])=>xs.length?xs.join(" · "):null;
export function compareOrganizations(left:OrganizationProfile,right:OrganizationProfile,relationships:OrganizationRelationship[]):OrganizationComparisonRow[]{const lm=organizationMetrics(left,relationships),rm=organizationMetrics(right,relationships),same=left.organizationType===right.organizationType?left.organizationType:"CROSS_TYPE";const rows:OrganizationComparisonRow[]=[
 {key:"type",label:{en:"Organization Type",zh:"组织类型"},left:left.organizationType,right:right.organizationType,appliesTo:"ALL"},
 {key:"regions",label:{en:"Regions",zh:"区域"},left:join(left.regionLinks.map(x=>x.regionId)),right:join(right.regionLinks.map(x=>x.regionId)),appliesTo:"ALL"},
 {key:"industries",label:{en:"Industries",zh:"产业"},left:join(left.industryLinks.map(x=>x.industryId)),right:join(right.industryLinks.map(x=>x.industryId)),appliesTo:"ALL"},
 {key:"technologies",label:{en:"Technologies",zh:"技术"},left:join(left.technologyLinks.map(x=>x.technologyId)),right:join(right.technologyLinks.map(x=>x.technologyId)),appliesTo:"ALL"},
 {key:"roles",label:{en:"Ecosystem Roles",zh:"生态角色"},left:join(left.roles.map(x=>x.role)),right:join(right.roles.map(x=>x.role)),appliesTo:"ALL"},
 {key:"connectivity",label:{en:"Connectivity (relationships)",zh:"连接度（关系数）"},left:lm.connectivity,right:rm.connectivity,appliesTo:"ALL"},
 {key:"diversity",label:{en:"Relationship Diversity",zh:"关系多样性"},left:lm.relationshipDiversity,right:rm.relationshipDiversity,appliesTo:"ALL"},
 {key:"coverage",label:{en:"Evidence Coverage",zh:"证据覆盖"},left:`${lm.evidenceCoverage}%`,right:`${rm.evidenceCoverage}%`,appliesTo:"ALL"},
 ];
 if(["UNIVERSITY","RESEARCH_INSTITUTION","CROSS_TYPE"].includes(same))rows.push({key:"research",label:{en:"Research Links",zh:"科研链接"},left:left.researchLinks.length,right:right.researchLinks.length,appliesTo:"RESEARCH"},{key:"patents",label:{en:"Patent Links",zh:"专利链接"},left:left.patentLinks.length,right:right.patentLinks.length,appliesTo:"RESEARCH"});
 if(["STARTUP","CORPORATION","CROSS_TYPE"].includes(same))rows.push({key:"policy",label:{en:"Public Policy / Program Links",zh:"公共政策 / 项目链接"},left:left.policyLinks.length,right:right.policyLinks.length,appliesTo:"COMMERCIAL"});
 if(["INVESTOR","CROSS_TYPE"].includes(same))rows.push({key:"exposure",label:{en:"Technology Exposure",zh:"技术覆盖"},left:left.technologyLinks.length,right:right.technologyLinks.length,appliesTo:"INVESTOR"});
 return rows;
}
export function oneHopRelationships(id:string,relationships:OrganizationRelationship[]){return relationships.filter(r=>r.sourceOrganizationId===id||r.targetOrganizationId===id);}
export function validateOrganizationData(profiles:OrganizationProfile[],relationships:OrganizationRelationship[],sources:OrganizationSource[],validIndustryIds:Set<string>,validTechnologyIds:Set<string>,validRegionIds:Set<string>,currentDate="2026-08-10"):OrganizationValidationResult{
 const ids=new Set<string>(),duplicateIds:string[]=[],invalidTypeIds:string[]=[],invalidRoleIds:string[]=[],invalidIndustryIds:string[]=[],invalidTechnologyIds:string[]=[],invalidRegionIds:string[]=[],invalidSourceIds:string[]=[],verifiedWithoutSourceIds:string[]=[],futureUpdatedIds:string[]=[],invalidFoundedYearIds:string[]=[];const sourceIds=new Set(sources.map(s=>s.id));
 for(const p of profiles){if(ids.has(p.id))duplicateIds.push(p.id);ids.add(p.id);if(!ORGANIZATION_TYPES.has(p.organizationType))invalidTypeIds.push(p.id);if(p.roles.some(r=>!ORGANIZATION_ROLES.has(r.role)))invalidRoleIds.push(p.id);if(p.industryLinks.some(x=>!validIndustryIds.has(x.industryId)))invalidIndustryIds.push(p.id);if(p.technologyLinks.some(x=>!validTechnologyIds.has(x.technologyId)))invalidTechnologyIds.push(p.id);if(p.regionLinks.some(x=>!validRegionIds.has(x.regionId)))invalidRegionIds.push(p.id);if(p.sourceIds.some(id=>!sourceIds.has(id)))invalidSourceIds.push(p.id);if(p.entityStatus==="VERIFIED_PUBLIC_ENTITY"&&(!p.website||p.sourceIds.length===0||p.evidenceStatus!=="VERIFIED_PUBLIC_SOURCE"))verifiedWithoutSourceIds.push(p.id);if(p.lastUpdated>currentDate)futureUpdatedIds.push(p.id);if(p.foundedYear!==null&&(p.foundedYear<1600||p.foundedYear>Number(currentDate.slice(0,4))))invalidFoundedYearIds.push(p.id);}
 const seenRelationships=new Set<string>(),semantic=new Set<string>(),duplicateRelationshipIds:string[]=[],orphanRelationshipIds:string[]=[];for(const r of relationships){const sig=[r.sourceOrganizationId,r.targetOrganizationId].sort().join("|")+`|${r.relationshipType}`;if(seenRelationships.has(r.id)||semantic.has(sig))duplicateRelationshipIds.push(r.id);seenRelationships.add(r.id);semantic.add(sig);if(!ids.has(r.sourceOrganizationId)||!ids.has(r.targetOrganizationId))orphanRelationshipIds.push(r.id);}
 const result={duplicateIds,invalidTypeIds,invalidRoleIds,invalidIndustryIds,invalidTechnologyIds,invalidRegionIds,duplicateRelationshipIds,orphanRelationshipIds,invalidSourceIds,verifiedWithoutSourceIds,futureUpdatedIds,invalidFoundedYearIds};return {valid:!Object.values(result).some(x=>x.length),...result};
}
