import type { PolicyComparisonConfig, PolicyComparisonValues, PolicyFilter, PolicyRecord, PolicySort, PolicyStatus, PolicyValidationResult } from "../domain/policy.ts";

const POLICY_STATUSES:Set<PolicyStatus>=new Set(["PROPOSED","ANNOUNCED","ENACTED","ACTIVE","AMENDED","SUPERSEDED","EXPIRED","SUSPENDED","UNKNOWN"]);

export function filterPolicies(records:PolicyRecord[],filter:PolicyFilter){
 const q=filter.search?.trim().toLowerCase();
 return records.filter(p=>(!filter.jurisdictionId||p.jurisdictionId===filter.jurisdictionId)&&(!filter.policyLevel||p.policyLevel===filter.policyLevel)&&(!filter.industryId||p.industryIds.includes(filter.industryId))&&(!filter.technologyId||p.technologyIds.includes(filter.technologyId))&&(!filter.policyType||p.policyType===filter.policyType)&&(!filter.status||p.status===filter.status)&&(!filter.effectType||p.effectTypes.includes(filter.effectType))&&(!filter.agency||p.agency.en===filter.agency)&&(!filter.publishedYear||p.publishedAt.startsWith(filter.publishedYear))&&(!filter.effectiveDateState||(filter.effectiveDateState==="HAS_DATE"?p.effectiveFrom!==null:p.effectiveFrom===null))&&(!filter.evidenceStatus||p.evidenceStatus===filter.evidenceStatus)&&(!q||`${p.localizedTitle.en} ${p.localizedTitle.zh} ${p.agency.en} ${p.agency.zh} ${p.jurisdictionId} ${p.industryIds.join(" ")} ${p.technologyIds.join(" ")}`.toLowerCase().includes(q)));
}
export function sortPolicies(records:PolicyRecord[],sort:PolicySort){return [...records].sort((a,b)=>{if(sort==="OLDEST")return a.publishedAt.localeCompare(b.publishedAt);if(sort==="EFFECTIVE_DATE")return (b.effectiveFrom??"").localeCompare(a.effectiveFrom??"");if(sort==="JURISDICTION")return a.jurisdictionId.localeCompare(b.jurisdictionId);if(sort==="POLICY_TYPE")return a.policyType.localeCompare(b.policyType);if(sort==="STATUS")return a.status.localeCompare(b.status);return b.publishedAt.localeCompare(a.publishedAt)});}
export function orderTimeline(records:PolicyRecord[]){return records.flatMap(p=>p.timeline).sort((a,b)=>a.date.localeCompare(b.date));}
export function policyInstrumentMix(records:PolicyRecord[]){const counts=new Map<string,number>();for(const p of records)for(const m of p.mechanisms)counts.set(m,(counts.get(m)??0)+1);return [...counts].sort((a,b)=>b[1]-a[1]);}
export function parsePolicyQuery(query:string){const p=new URLSearchParams(query),industry=p.get("industry");return {jurisdictionId:p.get("jurisdiction")||undefined,industryId:industry==="artificial-intelligence"?"ai":industry||undefined,technologyId:p.get("technology")||undefined,policyId:p.get("policy")||undefined};}
export function comparisonRows(left:PolicyComparisonValues|undefined,right:PolicyComparisonValues|undefined,config:PolicyComparisonConfig){return config.dimensions.map(d=>({dimension:d,left:left?.[d.key]??null,right:right?.[d.key]??null}));}
export function validatePolicyData(records:PolicyRecord[],jurisdictions:Set<string>,industries:Set<string>,technologies:Set<string>,sourceUrls:Map<string,string|null>):PolicyValidationResult{
 const seen=new Set<string>(),duplicates:string[]=[],invalidStatus:string[]=[],invalidJurisdiction:string[]=[],missingEvidence:string[]=[],invalidDates:string[]=[],invalidFunding:string[]=[],missingVerifiedSource:string[]=[],invalidIndustry:string[]=[],invalidTechnology:string[]=[];
 for(const p of records){if(seen.has(p.id))duplicates.push(p.id);seen.add(p.id);if(!POLICY_STATUSES.has(p.status))invalidStatus.push(p.id);if(!jurisdictions.has(p.jurisdictionId))invalidJurisdiction.push(p.id);if(p.sourceIds.length===0||!p.evidenceStatus)missingEvidence.push(p.id);if((p.effectiveFrom&&p.effectiveFrom<p.publishedAt)||(p.effectiveFrom&&p.effectiveTo&&p.effectiveTo<p.effectiveFrom))invalidDates.push(p.id);if((p.funding.amount!==null&&!p.funding.currency)||(p.funding.amount===null&&p.funding.currency!==null))invalidFunding.push(p.id);if(p.evidenceStatus==="VERIFIED_PUBLIC_SOURCE"&&(!p.officialSourceUrl||p.sourceIds.some(id=>!sourceUrls.get(id))))missingVerifiedSource.push(p.id);if(p.industryIds.some(id=>!industries.has(id)))invalidIndustry.push(p.id);if(p.technologyIds.some(id=>!technologies.has(id)))invalidTechnology.push(p.id);}
 return {valid:![duplicates,invalidStatus,invalidJurisdiction,missingEvidence,invalidDates,invalidFunding,missingVerifiedSource,invalidIndustry,invalidTechnology].some(x=>x.length),duplicatePolicyIds:duplicates,invalidStatusPolicyIds:invalidStatus,invalidJurisdictionPolicyIds:invalidJurisdiction,missingEvidencePolicyIds:missingEvidence,invalidDatePolicyIds:invalidDates,invalidFundingPolicyIds:invalidFunding,missingVerifiedSourcePolicyIds:missingVerifiedSource,invalidIndustryPolicyIds:invalidIndustry,invalidTechnologyPolicyIds:invalidTechnology};
}
