import type { CanonicalObservation, DataMode, DataQualityReport, DatasetSnapshot, IngestionRun, OrganizationIdentityCandidate, OrganizationIdentityMatch, ProviderId, RejectedRecord } from "../../domain/public-data.ts";
import { openAlexResearchObservations, worldBankObservations } from "../../data/production/pilot.ts";
import { openAlexTopicMappings } from "../../data/mappings/openalex-topics.ts";
import { countryCodeToGeographyId } from "../../data/mappings/geographies.ts";

export const fingerprint=(value:unknown)=>{const text=JSON.stringify(value,Object.keys(value as object).sort());let hash=2166136261;for(let i=0;i<text.length;i++){hash^=text.charCodeAt(i);hash=Math.imul(hash,16777619)}return (hash>>>0).toString(16).padStart(8,"0")};
export const validateObservations=(provider:ProviderId,records:CanonicalObservation[])=>{const accepted:CanonicalObservation[]=[],rejected:RejectedRecord[]=[],seen=new Set<string>();for(const record of records){let reason:string|null=null;if(!record.id||seen.has(record.id))reason="DUPLICATE_OR_MISSING_ID";else if(!record.sourceRecordIds.length)reason="MISSING_PROVENANCE";else if(!/^\d{4}([-QM].+)?$/.test(record.period))reason="INVALID_PERIOD";else if(record.value!==null&&!Number.isFinite(record.value))reason="INVALID_VALUE";else if(record.geographyType&&!record.geographyId)reason="MISSING_GEOGRAPHY";if(reason)rejected.push({id:`reject-${provider}-${rejected.length+1}`,provider,sourceId:record.sourceRecordIds[0]??null,reason,retrievedAt:record.retrievedAt,rawMetadataSummary:`record=${record.id}; metric=${record.metricKey}`});else{seen.add(record.id);accepted.push(record)}}return {accepted,rejected};};
export const createQualityReport=(provider:ProviderId,datasetId:string,records:CanonicalObservation[],rejected:RejectedRecord[]):DataQualityReport=>{const ids=new Set(records.map(x=>x.id)),withSource=records.filter(x=>x.sourceRecordIds.length).length,withTaxonomy=records.filter(x=>!x.entityId||openAlexTopicMappings.some(m=>x.entityId?.endsWith(m.topicIds[0]))).length,geoRelevant=records.filter(x=>x.geographyType).length,geoMapped=records.filter(x=>!x.geographyType||Boolean(x.geographyId&&countryCodeToGeographyId[x.geographyId]||x.geographyId?.startsWith("country-"))).length;const duplicateRate=records.length?(records.length-ids.size)/records.length:0;const validity=records.length?Math.round(records.filter(x=>x.value===null||Number.isFinite(x.value)).length/records.length*100):0,provenanceCoverage=records.length?Math.round(withSource/records.length*100):0,taxonomyCoverage=records.length?Math.round(withTaxonomy/records.length*100):0,geographyCoverage=geoRelevant?Math.round(geoMapped/records.length*100):100;const warnings:string[]=[];if(!records.length)warnings.push("EMPTY_DATASET");if(provenanceCoverage<100)warnings.push("PROVENANCE_GAP");if(duplicateRate>0)warnings.push("DUPLICATE_IDS");if(rejected.length)warnings.push("REJECTED_RECORDS");return {id:`quality-${datasetId}-2026-08-10`,datasetId,provider,calculatedAt:"2026-08-10T00:00:00Z",recordCount:records.length,completeness:records.length?100:0,validity,consistency:100,freshness:100,uniqueness:Math.round((1-duplicateRate)*100),provenanceCoverage,taxonomyCoverage,geographyCoverage,missingRequired:records.filter(x=>!x.id||!x.metricKey).length,duplicateRate,unmappedTaxonomyRate:(100-taxonomyCoverage)/100,unresolvedOrganizations:0,staleRecords:0,rejectedRecords:rejected.length,warnings,promotionAllowed:Boolean(records.length&&validity===100&&provenanceCoverage===100&&duplicateRate===0&&rejected.length/Math.max(records.length,1)<.1)};};
export class OrganizationIdentityResolver {resolve(candidate:OrganizationIdentityCandidate,canonicals:OrganizationIdentityCandidate[]):OrganizationIdentityMatch{const domain=candidate.officialDomain?.toLowerCase(),external=Object.entries(candidate.externalIds);const exact=canonicals.find(x=>domain&&x.officialDomain?.toLowerCase()===domain||external.some(([k,v])=>x.externalIds[k]===v));if(exact)return {candidateId:candidate.providerRecordId,canonicalOrganizationId:exact.providerRecordId,confidence:"EXACT",signals:[domain?"official_domain":"external_id"],requiresReview:false};const named=canonicals.find(x=>normalizeName(x.officialName)===normalizeName(candidate.officialName)&&x.countryCode===candidate.countryCode);if(named)return {candidateId:candidate.providerRecordId,canonicalOrganizationId:named.providerRecordId,confidence:"HIGH",signals:["normalized_name","country"],requiresReview:false};return {candidateId:candidate.providerRecordId,canonicalOrganizationId:null,confidence:"UNRESOLVED",signals:[],requiresReview:true};}}
const normalizeName=(x:string)=>x.normalize("NFKD").toLowerCase().replace(/[^a-z0-9]/g,"").replace(/(inc|corp|corporation|university)$/g,"");

export class AtomicSnapshotStore {private active=new Map<string,{snapshot:DatasetSnapshot;records:CanonicalObservation[]}>();private staged=new Map<string,{snapshot:DatasetSnapshot;records:CanonicalObservation[]}>();stage(snapshot:DatasetSnapshot,records:CanonicalObservation[]){this.staged.set(snapshot.datasetId,{snapshot,records:[...records]})}promote(datasetId:string,quality:DataQualityReport){const candidate=this.staged.get(datasetId);if(!candidate||!quality.promotionAllowed)throw new Error("PROMOTION_GATE_REJECTED");this.active.set(datasetId,{snapshot:{...candidate.snapshot,promotedAt:"2026-08-10T00:00:00Z"},records:[...candidate.records]});this.staged.delete(datasetId)}getActive(datasetId:string){return this.active.get(datasetId)??null}rollback(datasetId:string,previous:{snapshot:DatasetSnapshot;records:CanonicalObservation[]}){this.active.set(datasetId,previous)}}

export const runPilotIngestion=(dryRun=true)=>{const sets=[{provider:"OPENALEX" as const,dataset:"openalex-topic-activity",records:openAlexResearchObservations},{provider:"WORLD_BANK" as const,dataset:"world-bank-rd-context",records:worldBankObservations}];return sets.map(({provider,dataset,records})=>{const {accepted,rejected}=validateObservations(provider,records),quality=createQualityReport(provider,dataset,accepted,rejected);const run:IngestionRun={id:`run-${provider.toLowerCase()}-20260810`,provider,startedAt:"2026-08-10T00:00:00Z",completedAt:"2026-08-10T00:00:01Z",status:quality.promotionAllowed?"SUCCESS":"FAILED",recordsFetched:records.length,recordsAccepted:accepted.length,recordsRejected:rejected.length,recordsUpdated:0,recordsUnchanged:accepted.length,errors:quality.promotionAllowed?[]:["PROMOTION_GATE_REJECTED"],warnings:quality.warnings,schemaVersion:"1.0.0",parserVersion:"1.0.0",dryRun};return {run,quality,rejected,checksum:fingerprint(accepted)}})};

export class NexoraDataService {private mode:DataMode;constructor(mode:DataMode="HYBRID"){this.mode=mode}getMode(){return this.mode}setMode(mode:DataMode){this.mode=mode}resolve<T>(production:T|null,cached:T|null,lastKnownGood:T|null,demo:T|null){if(this.mode==="DEMO")return {value:demo,layer:demo?"DEMO":"UNAVAILABLE"};for(const [value,layer] of [[production,"PRODUCTION"],[cached,"CACHED_PRODUCTION"],[lastKnownGood,"LAST_KNOWN_GOOD"],[demo,"DEMO"]] as const)if(value!==null)return {value,layer};return {value:null,layer:"UNAVAILABLE" as const}}}
export const diffRecordIds=(before:{id:string}[],after:{id:string}[])=>{const a=new Set(before.map(x=>x.id)),b=new Set(after.map(x=>x.id));return {added:[...b].filter(x=>!a.has(x)),deprecated:[...a].filter(x=>!b.has(x)),unchanged:[...b].filter(x=>a.has(x))}};
