import type { EcosystemContext,ModelValidationResult,OutputId,ParameterId,SimulationOutput,SimulationPoint,SimulationRun,StockId } from "../../domain/simulation.ts";
import { calibrationCoverage,SIMULATION_SNAPSHOT_IDS } from "../calibration/calibration.ts";
import { innovationEcosystemModelV1 } from "../model/model-v1.ts";
import { defaultParameters,modelParameters } from "../parameters/parameters.ts";
import type { Scenario } from "../../domain/simulation.ts";

const round=(v:number,d=2)=>Number(v.toFixed(d));
const hash=(text:string)=>{let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,"0")};
const clamp=(value:number,min=0,max=120)=>Math.min(max,Math.max(min,value));
const stockIds:StockId[]=["researchCapacity","knowledgeStock","commercializationCapacity","startupBase","talentPool","infrastructure","policySupport","connectivity","marketAdoption"];
const nameMap=Object.fromEntries(innovationEcosystemModelV1.stocks.map(x=>[x.id,x.name])) as Record<StockId,{en:string;zh:string}>;
const outputNames:Record<OutputId,{en:string;zh:string}>={...nameMap,innovationOutput:{en:"Innovation Output Index",zh:"创新产出指数"},talentPressure:{en:"Talent Pressure",zh:"人才压力"}};

export function validateScenario(scenario:Scenario,overrides:Partial<Record<ParameterId,number>>={},horizon=scenario.timeHorizon):ModelValidationResult{const errors:string[]=[],warnings:ModelValidationResult["warnings"]=[];if(scenario.modelVersion!==innovationEcosystemModelV1.version)errors.push("MODEL_VERSION_MISMATCH");if(![5,10,15].includes(horizon))errors.push("UNSUPPORTED_TIME_HORIZON");for(const def of modelParameters){const value=overrides[def.id]??scenario.parameters[def.id]??def.defaultValue;if(!Number.isFinite(value))errors.push(`NON_FINITE_PARAMETER:${def.id}`);else if(value<def.min||value>def.max)errors.push(`PARAMETER_OUT_OF_RANGE:${def.id}`);if(value<def.sensitivityRange[0]||value>def.sensitivityRange[1])warnings.push({code:"OUTSIDE_CALIBRATION_RANGE",severity:"WARNING",message:{en:`${def.name.en} is outside the review range.`,zh:`${def.name.zh}超出审查范围。`}})}return {valid:errors.length===0,errors,warnings}}

function lagged(points:SimulationPoint[],id:StockId,lag:number,fallback:number){const index=Math.max(0,points.length-1-Math.round(lag));return points[index]?.values[id]??fallback}
function laggedParameter(history:Record<ParameterId,number>[],id:ParameterId,lag:number,fallback:number){const index=Math.max(0,history.length-1-Math.round(lag));return history[index]?.[id]??fallback}
function auxiliaries(values:Record<StockId,number>,researchCreation=0,commercializationFlow=0,startupFormation=0){const innovationOutput=.28*values.researchCapacity+.22*values.knowledgeStock+.18*values.commercializationCapacity+.12*values.startupBase+.10*values.connectivity+.10*values.marketAdoption;const talentPressure=clamp((values.researchCapacity+values.commercializationCapacity-values.talentPool)/1.6,0,100);return {innovationOutput:round(innovationOutput),talentPressure:round(talentPressure),researchCreation:round(researchCreation),commercializationFlow:round(commercializationFlow),startupFormation:round(startupFormation)}}

const cache=new Map<string,SimulationRun>();
export function runSimulation(scenario:Scenario,overrides:Partial<Record<ParameterId,number>>={},context:EcosystemContext={regionId:null,industryId:null,technologyId:null,ecosystemId:null,policyId:null},horizon:5|10|15=scenario.timeHorizon):SimulationRun{const parameters={...defaultParameters,...scenario.parameters,...overrides};const validation=validateScenario(scenario,overrides,horizon);const cacheKey=hash(JSON.stringify({model:innovationEcosystemModelV1.version,snapshot:SIMULATION_SNAPSHOT_IDS,scenario:scenario.id,parameters,context,horizon}));const cached=cache.get(cacheKey);if(cached)return cached;if(!validation.valid)throw new Error(validation.errors.join("|"));
 const initial=Object.fromEntries(innovationEcosystemModelV1.stocks.map(x=>[x.id,x.initialValue])) as Record<StockId,number>;const points:SimulationPoint[]=[{year:0,values:{...initial},auxiliaries:auxiliaries(initial)}],parameterHistory=[{...defaultParameters}];let clampedCount=0;
 for(let year=1;year<=horizon;year++){const prev=points[points.length-1].values,p=parameters;const policyLag=laggedParameter(parameterHistory,"publicResearchSupport",p.policyImplementationLag,p.publicResearchSupport);const infraLag=laggedParameter(parameterHistory,"researchInfrastructure",p.infrastructureLag,p.researchInfrastructure);const workforceLag=laggedParameter(parameterHistory,"workforceDevelopment",p.talentDevelopmentLag,p.workforceDevelopment);const knowledgeLag=lagged(points,"knowledgeStock",p.researchCommercializationLag,prev.knowledgeStock);const bundle=(policyLag+p.commercializationGrants+p.taxIncentiveStrength+p.publicProcurement+p.coordinationSupport)/5;const policySaturation=Math.max(.12,1-prev.policySupport/140);const policyImplementation=p.policyImplementationEfficiency*(bundle*100-prev.policySupport)*.12*policySaturation-prev.policySupport*.01;const infrastructureExpansion=.08*infraLag*(110-prev.infrastructure)*Math.max(.1,1-prev.infrastructure/145)-prev.infrastructure*.01;const talentInflow=p.talentGrowthRate*workforceLag*(110-prev.talentPool);const talentOutflow=p.talentConstraint*.02*prev.talentPool;const talentFactor=Math.max(.35,1-p.talentConstraint*(1-prev.talentPool/120));const researchCreation=prev.researchCapacity*p.researchProductivity*(.55+.45*prev.policySupport/100)*(.65+.35*prev.infrastructure/100)*talentFactor*Math.max(.08,1-prev.researchCapacity/140);const researchAttrition=.015*prev.researchCapacity;const networkModifier=(1+prev.connectivity/100*p.networkConnectivityEffect)*(1-.25*p.bridgeDependency);const knowledgeCreation=researchCreation*(.55+p.knowledgeDiffusionRate*networkModifier);const knowledgeDecay=(1-p.knowledgeRetention)*prev.knowledgeStock;const commercializationFlow=knowledgeLag*p.technologyTransferRate*p.commercializationEfficiency*6*networkModifier*(.5+.5*p.commercializationGrants)*Math.max(.08,1-prev.commercializationCapacity/135);const commercializationDecay=.02*prev.commercializationCapacity;const marketFactor=.45+.55*prev.marketAdoption/100;const startupFormation=prev.commercializationCapacity*p.startupFormationRate*marketFactor*(.45+.55*p.capitalAvailability)*(1+.25*p.taxIncentiveStrength);const startupAttrition=prev.startupBase*(1-p.startupSurvivalRate)*(1+.35*p.talentConstraint);const connectivityFormation=.04*p.coordinationSupport*p.relationshipDiversity*(115-prev.connectivity)-.025*p.bridgeDependency*prev.connectivity;const technologyAdoption=p.marketAdoptionRate*(prev.commercializationCapacity+p.publicProcurement*35)*(110-prev.marketAdoption)/100-prev.marketAdoption*.01;
  const raw:Record<StockId,number>={researchCapacity:prev.researchCapacity+researchCreation-researchAttrition,knowledgeStock:prev.knowledgeStock+knowledgeCreation-knowledgeDecay,commercializationCapacity:prev.commercializationCapacity+commercializationFlow-commercializationDecay,startupBase:prev.startupBase+startupFormation-startupAttrition,talentPool:prev.talentPool+talentInflow-talentOutflow,infrastructure:prev.infrastructure+infrastructureExpansion,policySupport:prev.policySupport+policyImplementation,connectivity:prev.connectivity+connectivityFormation,marketAdoption:prev.marketAdoption+technologyAdoption};const values={} as Record<StockId,number>;for(const id of stockIds){const v=clamp(raw[id]);if(v!==raw[id])clampedCount++;values[id]=round(v)}points.push({year,values,auxiliaries:auxiliaries(values,researchCreation,commercializationFlow,startupFormation)});parameterHistory.push({...parameters});
 }
 const series=[...stockIds,"innovationOutput","talentPressure" as const].map(id=>({id:id as OutputId,name:outputNames[id as OutputId],unit:"simulated index",points:points.map(x=>({year:x.year,value:id==="innovationOutput"||id==="talentPressure"?x.auxiliaries[id]:x.values[id as StockId]}))}));const finalValues=Object.fromEntries(series.map(x=>[x.id,x.points.at(-1)!.value])) as Record<OutputId,number>;const bottleneckCandidates:[string,{en:string;zh:string},number][]=[["talentPool",outputNames.talentPool,finalValues.talentPool],["commercializationCapacity",outputNames.commercializationCapacity,finalValues.commercializationCapacity],["infrastructure",outputNames.infrastructure,finalValues.infrastructure],["marketAdoption",outputNames.marketAdoption,finalValues.marketAdoption],["connectivity",outputNames.connectivity,finalValues.connectivity],["policySupport",outputNames.policySupport,finalValues.policySupport]];const bottleneck=bottleneckCandidates.sort((a,b)=>a[2]-b[2])[0];const output:SimulationOutput={series,finalValues,bottleneck:{id:bottleneck[0],label:bottleneck[1],value:round(bottleneck[2],1),rule:"Lowest final bounded capacity among six declared constraint dimensions."}};const warnings=[...validation.warnings,{code:"ASSUMPTION_HEAVY" as const,severity:"WARNING" as const,message:{en:"This scenario relies heavily on explicit model assumptions.",zh:"该情景高度依赖明确的模型假设。"}},{code:"MISSING_PATENT_CALIBRATION" as const,severity:"INFO" as const,message:{en:"Patent calibration is unavailable; USPTO missing is not treated as zero.",zh:"专利校准不可用；USPTO 缺失不会被视为零。"}},...(context.regionId?[{code:"LOW_DATA_COVERAGE" as const,severity:"WARNING" as const,message:{en:"Selected region is not metro-calibrated; the generic prototype model is used.",zh:"所选区域未进行城市群校准；当前使用通用原型模型。"}}]:[]),...(clampedCount?[{code:"CLAMPED_STOCK" as const,severity:"WARNING" as const,message:{en:`${clampedCount} stock updates reached declared semantic bounds.`,zh:`${clampedCount} 次存量更新触及已声明的语义边界。`}}]:[])];const run:SimulationRun={id:`sim-${cacheKey}`,scenarioId:scenario.id,modelVersion:innovationEcosystemModelV1.version,inputSnapshotIds:SIMULATION_SNAPSHOT_IDS,startedAt:"2026-08-10T00:00:00Z",completedAt:"2026-08-10T00:00:00Z",status:clampedCount?"PARTIAL":"SUCCESS",timeHorizon:horizon,timeStep:"ANNUAL",parameters,assumptions:[...scenario.assumptions,"The model structure itself is an assumption.","Simulation is not prediction."],outputs:output,warnings,quality:{finite:series.every(s=>s.points.every(x=>Number.isFinite(x.value))),nonNegative:series.every(s=>s.points.every(x=>x.value>=0)),timeOrdered:points.every((x,i)=>i===0||x.year>points[i-1].year),clampedCount,coverage:calibrationCoverage},reproducibilityHash:cacheKey,context};cache.set(cacheKey,run);return run}

export function compareToBaseline(run:SimulationRun,baseline:SimulationRun):SimulationRun{const deltas={} as Record<OutputId,{absolute:number;relative:number|null}>;for(const [id,value] of Object.entries(run.outputs.finalValues) as [OutputId,number][]){const base=baseline.outputs.finalValues[id],absolute=round(value-base,1);deltas[id]={absolute,relative:base===0?null:round(absolute/base*100,1)}}return {...run,outputs:{...run.outputs,baselineDeltas:deltas}}}
export function clearSimulationCache(){cache.clear()}
