import type { CalibrationCoverage,ParameterId,Scenario } from "../../domain/simulation.ts";
import { calibrationCoverage } from "../calibration/calibration.ts";

const scenario=(id:string,en:string,zh:string,descriptionEn:string,descriptionZh:string,parameters:Partial<Record<ParameterId,number>>,assumptions:string[]=[],timeHorizon:5|10|15=10):Scenario=>({id,name:{en,zh},description:{en:descriptionEn,zh:descriptionZh},baseSnapshotId:"nexora-production-pilot-2026-08-10",modelVersion:"sim-model-v1.0.0",timeHorizon,parameters,assumptions,createdAt:"2026-08-10T00:00:00Z",dataCoverage:calibrationCoverage as CalibrationCoverage,isDemo:true,isSaved:false});
export const scenarios:Scenario[]=[
 scenario("baseline","Baseline","基准情景","Reference parameter set for comparison—not the most likely future.","用于比较的参考参数集，并非最可能的未来。",{},["All uncalibrated initial values and coefficients are explicit model assumptions."]),
 scenario("research-led","Research Investment Expansion","科研投入扩张","Tests stronger public research support and research productivity.","检验更强公共科研支持与科研生产率。",{publicResearchSupport:.75,researchProductivity:.07,researchInfrastructure:.60}),
 scenario("commercialization-led","Commercialization Support","商业化支持","Tests stronger transfer and commercialization capacity support.","检验更强技术转移与商业化能力支持。",{commercializationGrants:.75,technologyTransferRate:.13,commercializationEfficiency:.20}),
 scenario("talent-led","Talent Expansion","人才扩张","Tests stronger workforce development and lower talent constraints.","检验更强人才发展与更低人才约束。",{workforceDevelopment:.75,talentGrowthRate:.06,talentConstraint:.15}),
 scenario("infrastructure-acceleration","Infrastructure Acceleration","基础设施加速","Tests accelerated infrastructure support with an explicit implementation lag.","检验具有明确实施时滞的基础设施加速支持。",{researchInfrastructure:.80,infrastructureLag:1}),
 scenario("balanced-policy","Balanced Innovation Policy","平衡创新政策","A bundled policy experiment across research, commercialization, talent and infrastructure.","涵盖科研、商业化、人才和基础设施的组合政策实验。",{publicResearchSupport:.60,commercializationGrants:.60,researchInfrastructure:.58,workforceDevelopment:.58,publicProcurement:.48,coordinationSupport:.55}),
 scenario("capital-heavy","Capital-Heavy Growth","资本驱动增长","Tests capital availability without treating unverified capital data as observed.","检验资本可得性，但不把未经核验的资本数据当作观测。",{capitalAvailability:.85,startupFormationRate:.12},["Capital availability is an assumption-only input."]),
 scenario("policy-retrenchment","Policy Retrenchment","政策收缩","Tests lower support across policy channels; not a political recommendation.","检验多项政策渠道支持下降；不构成政治建议。",{publicResearchSupport:.20,commercializationGrants:.18,researchInfrastructure:.22,workforceDevelopment:.24,publicProcurement:.15,coordinationSupport:.22}),
 scenario("research-commercialization-bridge","Research–Commercialization Bridge","科研—商业化桥梁","Tests stronger transfer, diffusion and ecosystem linkage assumptions.","检验更强技术转移、知识扩散与生态连接假设。",{technologyTransferRate:.15,commercializationEfficiency:.20,knowledgeDiffusionRate:.18,networkConnectivityEffect:.25,relationshipDiversity:.70}),
 scenario("supply-constraint","Supply Constraint","供给约束","Tests high talent pressure, lower survival and slower infrastructure response.","检验高人才压力、较低存续率与更慢基础设施响应。",{talentConstraint:.68,startupSurvivalRate:.78,infrastructureLag:4,talentDevelopmentLag:4}),
];
export const scenarioById=(id:string)=>scenarios.find(x=>x.id===id)??scenarios[0];
