import type { AIAnswer, AICitation, AIAnswerSection, AIFollowUpSuggestion, EvidenceItem, EvidencePack, GroundedClaim } from "../../domain/ai.ts";
import { AI_PROMPT_VERSION } from "./config.ts";
import { GroundingValidator,validateAnswerSchema } from "./validation.ts";

const hash=(text:string)=>{let h=5381;for(const c of text)h=(h*33)^c.charCodeAt(0);return (h>>>0).toString(16)};
const substantive=(pack:EvidencePack)=>pack.items.filter(x=>!["DATA_STATUS","METHODOLOGY"].includes(x.kind));
const claimFrom=(item:EvidenceItem,index:number):GroundedClaim=>({id:`claim-${index+1}`,claim:{en:`${item.title.en}: ${item.summary.en}`,zh:`${item.title.zh}：${item.summary.zh}`},supportIds:[item.id],claimType:item.status==="DERIVED"?"DERIVED":"OBSERVED",confidence:item.directness>=90?"HIGH":item.directness>=70?"MEDIUM":"LOW"});
const titles:Record<string,{en:string;zh:string}>={QUICK_ANSWER:{en:"Evidence-based answer",zh:"证据驱动回答"},EVIDENCE_SUMMARY:{en:"Evidence summary",zh:"证据摘要"},COMPARISON:{en:"Evidence-based comparison",zh:"证据驱动比较"},RESEARCH_BRIEF:{en:"NEXORA research brief",zh:"NEXORA 研究简报"},METHODOLOGY_EXPLANATION:{en:"Methodology explanation",zh:"方法说明"},SOURCE_VERIFICATION:{en:"Source verification",zh:"来源核验"},DATA_AVAILABILITY:{en:"Data availability",zh:"数据可用性"},TREND_EXPLANATION:{en:"Trend evidence",zh:"趋势证据"},ECOSYSTEM_ANALYSIS:{en:"Ecosystem evidence",zh:"创新生态证据"},POLICY_ANALYSIS:{en:"Policy evidence",zh:"政策证据"}};

function makeClaims(pack:EvidencePack){const rows=substantive(pack);if(pack.query.intent==="TREND_EXPLANATION"||pack.query.intent==="TECHNOLOGY_COMPARISON"||pack.query.intent==="GENERAL_RESEARCH"){const derived=rows.filter(x=>x.kind==="RESEARCH"&&x.status==="DERIVED").sort((a,b)=>(b.value??-Infinity)-(a.value??-Infinity));if(derived.length)return derived.slice(0,4).map(claimFrom)}return rows.slice(0,6).map(claimFrom)}
function citationsFor(claims:GroundedClaim[],pack:EvidencePack):AICitation[]{const citations:AICitation[]=[],seen=new Set<string>();for(const claim of claims)for(const supportId of claim.supportIds){const item=pack.items.find(x=>x.id===supportId);if(!item)continue;const key=`${item.sourceId}:${item.sourceUrl}`;const existing=citations.find(x=>`${x.sourceId}:${x.url}`===key);if(existing){if(!existing.relatedClaimIds.includes(claim.id))existing.relatedClaimIds.push(claim.id);continue}if(seen.has(key))continue;seen.add(key);citations.push({id:`citation-${citations.length+1}`,sourceId:item.sourceId,title:item.sourceTitle,publisher:item.publisher,url:item.sourceUrl,sourceType:item.sourceType,publishedAt:item.publishedAt,retrievedAt:item.retrievedAt,relatedClaimIds:[claim.id],dataStatus:item.status})}return citations}

function summary(pack:EvidencePack,claims:GroundedClaim[]){const lang=pack.query.language;if(pack.query.safetyFlags.length)return {en:"This request cannot bypass NEXORA grounding, privacy, secret-protection or retrieval boundaries. Ask a research question about the evidence NEXORA currently holds.",zh:"该请求不能绕过 NEXORA 的证据约束、隐私、密钥保护或检索边界。请针对 NEXORA 当前持有的证据提出研究问题。"};if(pack.query.ambiguity)return {en:"The geography is ambiguous. Please specify which Cambridge and comparison geography you mean.",zh:"地理实体存在歧义。请明确你指的是哪个剑桥以及比较区域。"};if(pack.sufficiency.state==="INSUFFICIENT")return {en:"NEXORA does not currently have enough verified evidence to answer this reliably. The available evidence and missing dimensions are shown below.",zh:"NEXORA 目前没有足够的已核验证据来可靠回答这一问题。下方列出了现有证据与缺失维度。"};const lead=claims[0]?.claim[lang];return {en:`Based on the current production evidence, ${lead??"NEXORA can provide a bounded evidence summary"} Available Demo dimensions are excluded by default.`,zh:`基于当前生产证据，${lead??"NEXORA 可以提供有限的证据摘要"}。现有 Demo 维度默认不纳入回答。`}}

function sections(pack:EvidencePack,claims:GroundedClaim[]):AIAnswerSection[]{const lang=pack.query.language,byKind=(kind:EvidenceItem["kind"])=>claims.filter(c=>c.supportIds.some(id=>pack.items.find(x=>x.id===id)?.kind===kind));const section=(id:string,en:string,zh:string,rows:GroundedClaim[])=>rows.length?{id,title:{en,zh},body:{en:rows.map(x=>x.claim.en).join("\n"),zh:rows.map(x=>x.claim.zh).join("\n")},claimIds:rows.map(x=>x.id)}:null;const built=[section("research","What NEXORA observes","NEXORA 当前观测",byKind("RESEARCH")),section("policy","Official policy evidence","官方政策证据",byKind("POLICY")),section("organizations","Verified organizations","已核验组织",byKind("ORGANIZATION")),section("relationships","Evidence-backed relationships","有证据支持的关系",byKind("RELATIONSHIP")),section("regional","Regional context","区域背景",byKind("REGIONAL_CONTEXT")),section("method","Method","方法",byKind("METHODOLOGY"))].filter((x):x is AIAnswerSection=>Boolean(x));if(pack.query.answerType==="COMPARISON"&&built.length)built.unshift({id:"comparison-boundary",title:{en:"Comparison boundary",zh:"比较边界"},body:{en:"Only compatible production dimensions are compared. Country-level context is not treated as metro-level evidence, and unavailable patent evidence is omitted.",zh:"仅比较兼容的生产证据维度。国家级背景不会被当作城市群证据，缺失的专利证据不会被纳入。"},claimIds:[]});if(pack.query.answerType==="RESEARCH_BRIEF")built.push({id:"uncertainties",title:{en:"Uncertainties and data gaps",zh:"不确定性与数据缺口"},body:{en:pack.missingData.map(x=>x.en).join("\n"),zh:pack.missingData.map(x=>x.zh).join("\n")},claimIds:[]});if(!built.length)built.push({id:"boundary",title:{en:"Evidence boundary",zh:"证据边界"},body:{en:lang==="en"?"No supported production claim can be made from the current evidence pack.":"当前证据包无法支持生产事实声明。",zh:"当前证据包无法支持生产事实声明。"},claimIds:[]});return built}

function followUps(pack:EvidencePack):AIFollowUpSuggestion[]{const tech=pack.query.resolvedEntities.find(x=>x.type==="TECHNOLOGY");const suggestions=[{en:"Show the production data coverage for this question",zh:"显示该问题的生产数据覆盖",query:"What production data is available and what is missing?"},{en:tech?`Show the verified sources for ${tech.name.en}`:"Which technologies have the strongest verified research momentum?",zh:tech?`显示${tech.name.zh}的已核验来源`:"哪些技术拥有最强的已核验科研动能？",query:tech?`What verified evidence does NEXORA have for ${tech.name.en}?`:"Which technologies have the strongest verified research momentum?"},{en:"Explain how NEXORA separates observed facts and Demo scores",zh:"解释 NEXORA 如何区分公开事实与 Demo 评分",query:"How does NEXORA separate observed public data from Demo scores?"}];return suggestions.map((x,i)=>({id:`follow-${i+1}`,text:{en:x.en,zh:x.zh},query:x.query,context:{technologyIds:tech?[tech.id]:[]}}))}

function fallback(pack:EvidencePack,errors:string[]):AIAnswer{const rows=substantive(pack).filter(x=>x.status==="OBSERVED"&&!x.isDemo).slice(0,5),claims=rows.map(claimFrom),citations=citationsFor(claims,pack);return {id:`answer-fallback-${pack.query.id}`,language:pack.query.language,title:{en:"Verified evidence only",zh:"仅显示已核验证据"},summary:{en:"I found relevant NEXORA evidence, but I could not produce a sufficiently grounded synthesis. Here are the verified observations instead.",zh:"NEXORA 找到了相关证据，但无法生成充分可靠的综合结论。以下仅显示已核验观测。"},sections:sections(pack,claims),claims,citations,limitations:pack.limitations,dataGaps:pack.missingData.map(x=>({en:x.en,zh:x.zh})),uncertainties:[{code:"GROUNDING_FALLBACK",severity:"WARNING",message:{en:"The synthesized response failed grounding validation.",zh:"综合回答未通过证据约束校验。"}},{code:"VALIDATION_DETAIL",severity:"INFO",message:{en:`Validation checks: ${errors.length}.`,zh:`校验问题数量：${errors.length}。`}}],followUps:followUps(pack),metadata:{queryId:pack.query.id,intent:pack.query.intent,answerType:pack.query.answerType,createdAt:pack.createdAt,provider:"nexora-evidence-first",modelIdentifier:null,promptVersion:AI_PROMPT_VERSION,dataSnapshotIds:pack.snapshotIds,retrievalVersion:pack.plan.retrievalVersion,evidenceCount:pack.items.length,evidenceSufficiency:pack.sufficiency.state,dataCoverage:pack.coverage,groundingStatus:"FALLBACK",generationMode:"SAFE_FALLBACK",cacheKey:hash(`${pack.query.normalizedText}:${pack.snapshotIds.join(":")}:${pack.query.language}:${AI_PROMPT_VERSION}`)}}}

export function generateEvidenceFirstAnswer(pack:EvidencePack):AIAnswer{const claims=makeClaims(pack),citations=citationsFor(claims,pack),answer:AIAnswer={id:`answer-${pack.query.id}`,language:pack.query.language,title:titles[pack.query.answerType]??titles.QUICK_ANSWER,summary:summary(pack,claims),sections:sections(pack,claims),claims,citations,limitations:pack.limitations,dataGaps:pack.missingData.map(x=>({en:x.en,zh:x.zh})),uncertainties:[...(pack.sufficiency.state!=="SUFFICIENT"?[{code:"LIMITED_EVIDENCE",severity:pack.sufficiency.state==="INSUFFICIENT"?"CRITICAL":"WARNING",message:{en:`Evidence sufficiency is ${pack.sufficiency.state.toLowerCase()}.`,zh:`证据充分性为 ${pack.sufficiency.state}。`}} as const]:[]),...(pack.items.some(x=>x.status==="STALE")?[{code:"STALE_DATA",severity:"WARNING",message:{en:"Relevant data may be stale.",zh:"相关数据可能已经过期。"}} as const]:[])],followUps:followUps(pack),metadata:{queryId:pack.query.id,intent:pack.query.intent,answerType:pack.query.answerType,createdAt:pack.createdAt,provider:"nexora-evidence-first",modelIdentifier:null,promptVersion:AI_PROMPT_VERSION,dataSnapshotIds:pack.snapshotIds,retrievalVersion:pack.plan.retrievalVersion,evidenceCount:pack.items.length,evidenceSufficiency:pack.sufficiency.state,dataCoverage:pack.coverage,groundingStatus:"VALID",generationMode:"EVIDENCE_FIRST",cacheKey:hash(`${pack.query.normalizedText}:${pack.snapshotIds.join(":")}:${pack.query.language}:${AI_PROMPT_VERSION}`)}};if(!validateAnswerSchema(answer))return fallback(pack,["OUTPUT_SCHEMA_INVALID"]);const validation=new GroundingValidator().validate(answer,pack);return validation.valid?answer:fallback(pack,validation.errors)}
