import type { AIAnswerType, AIEntityReference, AILanguage, AIPlanOperation, AIQuery, AIQueryContext, AIQueryIntent, AIQueryPlan } from "../../domain/ai.ts";
import { verifiedOrganizations,verifiedPolicies } from "../../data/production/pilot.ts";
import { AI_RETRIEVAL_VERSION,aiConfig } from "./config.ts";

type RegistryEntry={type:AIEntityReference["type"];id:string;en:string;zh:string;aliases:string[]};
const technologies:RegistryEntry[]=[
 ["multimodal-ai","Multimodal AI","多模态人工智能",["multimodal ai","artificial intelligence","ai research","人工智能","多模态 ai"]],
 ["ai-agents","AI Agents","AI 智能体",["ai agents","agentic ai","ai agent","智能体","智能体 ai"]],
 ["humanoid-robotics","Humanoid Robotics","人形机器人",["humanoid robotics","humanoid robot","人形机器人"]],
 ["quantum-computing","Quantum Computing","量子计算",["quantum computing","quantum technology","量子计算","量子技术"]],
 ["synthetic-biology","Synthetic Biology","合成生物学",["synthetic biology","biotechnology","biotech","合成生物学","生物技术"]],
 ["solid-state-batteries","Solid-state Batteries","固态电池",["solid state batteries","solid-state battery","advanced batteries","固态电池","先进电池"]],
 ["advanced-packaging","Advanced Semiconductor Packaging","先进半导体封装",["semiconductors","semiconductor development","advanced packaging","chips","半导体","芯片","先进封装"]],
 ["grid-storage","Grid-scale Energy Storage","电网级储能",["grid storage","energy storage","电网储能","储能"]],
 ["green-hydrogen","Green Hydrogen","绿氢",["green hydrogen","绿氢"]],
 ["photonic-computing","Photonic Computing","光子计算",["photonic computing","光子计算"]]
].map(([id,en,zh,aliases])=>({type:"TECHNOLOGY",id,en,zh,aliases})) as RegistryEntry[];
const regions:RegistryEntry[]=[
 ["sf","San Francisco Bay Area","旧金山湾区",["san francisco bay area","sf bay area","bay area","silicon valley","旧金山湾区","硅谷"]],
 ["shenzhen","Shenzhen","深圳",["shenzhen","深圳"]],
 ["boston","Boston","波士顿",["boston","波士顿"]],
 ["beijing","Beijing","北京",["beijing","北京"]],
 ["london","London","伦敦",["london","伦敦"]],
 ["tokyo","Tokyo","东京",["tokyo","东京"]],
 ["seoul","Seoul","首尔",["seoul","首尔"]],
 ["singapore","Singapore","新加坡",["singapore","新加坡"]]
].map(([id,en,zh,aliases])=>({type:"REGION",id,en,zh,aliases})) as RegistryEntry[];
const industries:RegistryEntry[]=[["ai","Artificial Intelligence","人工智能",["ai industry","artificial intelligence industry","人工智能产业"]],["semiconductors","Semiconductors","半导体",["semiconductor industry","semiconductors","半导体产业"]],["batteries","Advanced Batteries","先进电池",["battery industry","batteries","电池产业"]],["biotech","Biotechnology","生物技术",["biotech industry","biotechnology","生物技术产业"]]].map(([id,en,zh,aliases])=>({type:"INDUSTRY",id,en,zh,aliases})) as RegistryEntry[];
const organizationAliases:Record<string,string[]>={"org-mit":["mit"],"org-ibm-research":["ibm","ibm research"]};
const registry:RegistryEntry[]=[...technologies,...regions,...industries,...verifiedOrganizations.map(o=>({type:"ORGANIZATION" as const,id:o.id,en:o.name.en,zh:o.name.zh,aliases:[o.name.en.toLowerCase(),o.name.zh,o.officialDomain,...(organizationAliases[o.id]??[])]})),...verifiedPolicies.map(p=>({type:"POLICY" as const,id:p.id,en:p.title.en,zh:p.title.zh,aliases:[p.title.en.toLowerCase(),p.title.zh,p.agency.toLowerCase()]}))];

const hash=(text:string)=>{let h=2166136261;for(const c of text){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0).toString(16).padStart(8,"0")};
const detectLanguage=(text:string,fallback?:AILanguage):AILanguage=>fallback??(/[\u3400-\u9fff]/.test(text)?"zh":"en");
const normalize=(text:string)=>text.normalize("NFKC").toLowerCase().replace(/[’']/g,"'").replace(/\s+/g," ").trim();

function inspectSafety(text:string){const flags:string[]=[];if(/ignore (?:all |previous |system )?(?:instructions|rules)|reveal (?:the )?(?:system prompt|hidden prompt)|show hidden (?:prompt|reasoning)|api[_ -]?key|authorization header/i.test(text))flags.push("PROMPT_INJECTION_OR_SECRET_REQUEST");if(/https?:\/\//i.test(text)||/fetch (?:an |the )?(?:url|website)|browse the web/i.test(text))flags.push("ARBITRARY_EXTERNAL_ACCESS_REQUEST");if(/buy|sell|target price|guaranteed return|investment recommendation/i.test(text))flags.push("INVESTMENT_ADVICE_REQUEST");return flags}

function resolveEntities(normalizedText:string,context:Partial<AIQueryContext>):AIEntityReference[]{const found=new Map<string,AIEntityReference>();for(const item of registry){const aliases=[item.en.toLowerCase(),item.zh,...item.aliases].sort((a,b)=>b.length-a.length);const alias=aliases.find(a=>a&&normalizedText.includes(a.toLowerCase()));if(alias)found.set(`${item.type}:${item.id}`,{type:item.type,id:item.id,name:{en:item.en,zh:item.zh},confidence:alias===item.en.toLowerCase()||alias===item.zh?"EXACT":"HIGH",matchedAlias:alias});}
 for(const [type,ids] of [["TECHNOLOGY",context.technologyIds],["REGION",context.regionIds],["ORGANIZATION",context.organizationIds],["POLICY",context.policyIds],["INDUSTRY",context.industryIds]] as const)for(const id of ids??[]){const item=registry.find(x=>x.type===type&&x.id===id);if(item)found.set(`${type}:${id}`,{type,id,name:{en:item.en,zh:item.zh},confidence:"EXACT",matchedAlias:"URL_CONTEXT"});}
 return [...found.values()];}

function classifyIntent(text:string,entities:AIEntityReference[],safetyFlags:string[]):AIQueryIntent{if(safetyFlags.length)return "UNSUPPORTED";if(/make the most money|predict.*financial|will win|most powerful/i.test(text))return "UNSUPPORTED";if(/what (?:data|evidence).*(?:available|missing)|data coverage|what .*not know|真实公开数据|哪些.*demo|缺少.*数据|专利.*(?:available|可用)/i.test(text))return "DATA_AVAILABILITY";if(/how does nexora|method|methodology|calculate|what does .* mean|why is .*score|方法|如何计算|什么意思/i.test(text))return "METHODOLOGY";if(/source support|verify.*source|what source|来源|核验.*来源/i.test(text))return "SOURCE_VERIFICATION";if(/research brief|brief on|研究简报|研究报告/i.test(text))return "RESEARCH_BRIEF";if(/compare|comparison|versus|\bvs\b|比较|对比|差异/i.test(text)){if(entities.filter(x=>x.type==="REGION").length>1)return "REGIONAL_COMPARISON";if(entities.filter(x=>x.type==="POLICY").length>1)return "POLICY_COMPARISON";return "TECHNOLOGY_COMPARISON";}if(/policy|policies|regulation|incentive|政策|监管|激励/i.test(text))return "POLICY_ANALYSIS";if(/ecosystem|network|bridge|connected|生态|网络|桥接/i.test(text))return "ECOSYSTEM_ANALYSIS";if(/organization|institution|company|university|组织|机构|公司|大学/i.test(text))return "ORGANIZATION_RESEARCH";if(/evidence.*(?:have|support)|show the evidence|what public data|证据|公开数据支持/i.test(text))return "EVIDENCE_SUMMARY";if(/accelerat|momentum|trend|growth|rising|增长|动能|趋势|加速/i.test(text))return "TREND_EXPLANATION";if(entities.some(x=>x.type==="TECHNOLOGY"))return "TECHNOLOGY_OVERVIEW";return "GENERAL_RESEARCH"}

function answerType(intent:AIQueryIntent):AIAnswerType{const map:Partial<Record<AIQueryIntent,AIAnswerType>>={RESEARCH_BRIEF:"RESEARCH_BRIEF",REGIONAL_COMPARISON:"COMPARISON",TECHNOLOGY_COMPARISON:"COMPARISON",POLICY_COMPARISON:"COMPARISON",EVIDENCE_SUMMARY:"EVIDENCE_SUMMARY",SOURCE_VERIFICATION:"SOURCE_VERIFICATION",METHODOLOGY:"METHODOLOGY_EXPLANATION",METRIC_EXPLANATION:"METHODOLOGY_EXPLANATION",DATA_AVAILABILITY:"DATA_AVAILABILITY",TREND_EXPLANATION:"TREND_EXPLANATION",ECOSYSTEM_ANALYSIS:"ECOSYSTEM_ANALYSIS",POLICY_ANALYSIS:"POLICY_ANALYSIS"};return map[intent]??aiConfig.defaultAnswerMode}

export function understandQuery(text:string,context:Partial<AIQueryContext>={},language?:AILanguage):AIQuery{const clean=text.slice(0,aiConfig.maxQueryLength).trim(),normalizedText=normalize(clean),safetyFlags=inspectSafety(clean);const fullContext:AIQueryContext={caseIds:[],technologyIds:context.technologyIds??[],regionIds:context.regionIds??[],organizationIds:context.organizationIds??[],policyIds:context.policyIds??[],industryIds:context.industryIds??[],timeWindow:context.timeWindow??(/\b1\s*(?:year|yr)|1年/i.test(clean)?"1Y":/\b3\s*(?:year|yr)|3年/i.test(clean)?"3Y":/\b5\s*(?:year|yr)|5年/i.test(clean)?"5Y":"ALL"),dataMode:context.dataMode??"HYBRID",allowDemoEvidence:context.allowDemoEvidence===true};const resolvedEntities=resolveEntities(normalizedText,fullContext),intent=classifyIntent(normalizedText,resolvedEntities,safetyFlags);const regionsFound=resolvedEntities.filter(x=>x.type==="REGION");const ambiguity=/cambridge/i.test(clean)&&regionsFound.length<1?"CAMBRIDGE_GEOGRAPHY":null;return {id:`aiq-${hash(`${normalizedText}:${JSON.stringify(fullContext)}`)}`,text:clean,normalizedText,language:detectLanguage(clean,language),intent:ambiguity?"UNSUPPORTED":intent,answerType:answerType(ambiguity?"UNSUPPORTED":intent),context:fullContext,resolvedEntities,ambiguity,safetyFlags,createdAt:"2026-08-10T00:00:00Z"}}

export class NexoraQueryPlanner {plan(query:AIQuery):AIQueryPlan{const operations:AIPlanOperation[]=[],ids=query.resolvedEntities.map(x=>x.id);const add=(type:AIPlanOperation["type"],required=true,metricKeys:string[]=[],limit=8)=>operations.push({id:`op-${operations.length+1}`,type,entityIds:ids,metricKeys,timeWindow:query.context.timeWindow,required,limit});add("GET_ENTITY");if(["TREND_EXPLANATION","TECHNOLOGY_OVERVIEW","TECHNOLOGY_COMPARISON","RESEARCH_BRIEF","EVIDENCE_SUMMARY","GENERAL_RESEARCH","CROSS_DOMAIN_SYNTHESIS"].includes(query.intent)){add("GET_METRICS",true,["publication_count"]);add("GET_TIMESERIES",true,["publication_count"],12);add("GET_SIGNALS",false)}if(query.intent.includes("POLICY")||["RESEARCH_BRIEF","CROSS_DOMAIN_SYNTHESIS","GENERAL_RESEARCH"].includes(query.intent))add("GET_POLICIES",query.intent.includes("POLICY"));if(["ORGANIZATION_RESEARCH","ECOSYSTEM_ANALYSIS","RESEARCH_BRIEF","CROSS_DOMAIN_SYNTHESIS"].includes(query.intent)){add("GET_ORGANIZATIONS",false);add("GET_RELATIONSHIPS",false)}if(query.intent.includes("ECOSYSTEM")||query.intent.includes("REGIONAL"))add("GET_ECOSYSTEM",false);if(query.intent.includes("METHODOLOGY")||query.intent==="METRIC_EXPLANATION")add("GET_METHODOLOGY");add("GET_SOURCES",false);add("GET_PROVENANCE",false);add("GET_LINEAGE",false);add("GET_DATA_STATUS",true);if(query.answerType==="COMPARISON")add("COMPARE_ENTITIES");return {id:`plan-${query.id}`,queryId:query.id,intent:query.intent,operations,retrievalVersion:AI_RETRIEVAL_VERSION,maxEvidenceItems:aiConfig.maxEvidenceItems}}}
