import type { AIAnswer, AIValidationResult, EvidencePack, GroundedClaim } from "../../domain/ai.ts";

export const isSafeSourceUrl=(url:string)=>{if(url.startsWith("/docs/")||url==="/data-status")return true;try{const parsed=new URL(url);return parsed.protocol==="https:"&&!parsed.username&&!parsed.password}catch{return false}};
const numbers=(text:string)=>text.match(/\b\d+(?:\.\d+)?%?\b/g)??[];
const evidenceText=(ids:string[],pack:EvidencePack)=>pack.items.filter(x=>ids.includes(x.id)).map(x=>[x.title.en,x.title.zh,x.summary.en,x.summary.zh,x.period,x.value,x.unit].join(" ")).join(" ");

export class CitationValidator {validate(answer:AIAnswer,pack:EvidencePack){const errors:string[]=[],seen=new Set<string>(),invalidCitationIds:string[]=[];for(const citation of answer.citations){const matching=pack.items.filter(x=>x.sourceId===citation.sourceId&&x.sourceUrl===citation.url);if(!matching.length){errors.push(`CITATION_NOT_RETRIEVED:${citation.id}`);invalidCitationIds.push(citation.id)}if(!isSafeSourceUrl(citation.url)){errors.push(`UNSAFE_CITATION_URL:${citation.id}`);invalidCitationIds.push(citation.id)}if(matching.some(x=>x.isDemo)){errors.push(`DEMO_CITATION:${citation.id}`);invalidCitationIds.push(citation.id)}if(seen.has(`${citation.sourceId}:${citation.url}`)){errors.push(`DUPLICATE_CITATION:${citation.id}`);invalidCitationIds.push(citation.id)}seen.add(`${citation.sourceId}:${citation.url}`);for(const claimId of citation.relatedClaimIds){const claim=answer.claims.find(x=>x.id===claimId);if(!claim||!claim.supportIds.some(id=>matching.some(item=>item.id===id))){errors.push(`CITATION_CLAIM_MISMATCH:${citation.id}:${claimId}`);invalidCitationIds.push(citation.id)}}}return {errors,invalidCitationIds:[...new Set(invalidCitationIds)]}}}

export class GroundingValidator {validate(answer:AIAnswer,pack:EvidencePack):AIValidationResult{const errors:string[]=[],unsupportedClaimIds:string[]=[],demoLeakageIds:string[]=[];for(const claim of answer.claims){const support=pack.items.filter(x=>claim.supportIds.includes(x.id));if(!claim.supportIds.length||support.length!==claim.supportIds.length){errors.push(`UNSUPPORTED_CLAIM:${claim.id}`);unsupportedClaimIds.push(claim.id);continue}if(!pack.query.context.allowDemoEvidence&&support.some(x=>x.isDemo)){errors.push(`DEMO_AS_PRODUCTION:${claim.id}`);demoLeakageIds.push(claim.id)}const text=evidenceText(claim.supportIds,pack);for(const token of numbers(`${claim.claim.en} ${claim.claim.zh}`))if(!text.includes(token.replace("%",""))&&!text.includes(token)){errors.push(`UNSUPPORTED_NUMBER:${claim.id}:${token}`);unsupportedClaimIds.push(claim.id)}}const citations=new CitationValidator().validate(answer,pack);errors.push(...citations.errors);if(answer.metadata.queryId!==pack.query.id)errors.push("QUERY_METADATA_MISMATCH");if(answer.metadata.dataSnapshotIds.some(id=>!pack.snapshotIds.includes(id)))errors.push("SNAPSHOT_METADATA_MISMATCH");return {valid:errors.length===0,errors,unsupportedClaimIds:[...new Set(unsupportedClaimIds)],invalidCitationIds:citations.invalidCitationIds,demoLeakageIds:[...new Set(demoLeakageIds)]}}
 validateClaim(claim:GroundedClaim,pack:EvidencePack){return this.validate({...emptyAnswer,claims:[claim],metadata:{...emptyAnswer.metadata,queryId:pack.query.id,dataSnapshotIds:pack.snapshotIds}} as AIAnswer,pack)}}

export function validateAnswerSchema(value:unknown):value is AIAnswer{if(!value||typeof value!=="object")return false;const a=value as AIAnswer;return typeof a.id==="string"&&["en","zh"].includes(a.language)&&typeof a.title?.en==="string"&&typeof a.title?.zh==="string"&&typeof a.summary?.en==="string"&&typeof a.summary?.zh==="string"&&Array.isArray(a.sections)&&Array.isArray(a.claims)&&Array.isArray(a.citations)&&Array.isArray(a.limitations)&&Array.isArray(a.dataGaps)&&Array.isArray(a.followUps)&&typeof a.metadata?.promptVersion==="string"}

const emptyAnswer={id:"",language:"en",title:{en:"",zh:""},summary:{en:"",zh:""},sections:[],claims:[],citations:[],limitations:[],dataGaps:[],uncertainties:[],followUps:[],metadata:{queryId:"",intent:"UNSUPPORTED",answerType:"QUICK_ANSWER",createdAt:"",provider:"",modelIdentifier:null,promptVersion:"",dataSnapshotIds:[],retrievalVersion:"",evidenceCount:0,evidenceSufficiency:"INSUFFICIENT",dataCoverage:{research:"UNAVAILABLE",patents:"UNAVAILABLE",policy:"UNAVAILABLE",organizations:"UNAVAILABLE",relationships:"UNAVAILABLE",regionalContext:"UNAVAILABLE",methodology:"UNAVAILABLE"},groundingStatus:"VALID",generationMode:"EVIDENCE_FIRST",cacheKey:""}} satisfies AIAnswer;
